use crate::gitcomp::*;

/// `options[]` (builtin/am.c:2331-2446).
pub(super) const AM_OPTIONS: &[Opt] = &[
    OPT_BOOL("interactive"),
    OPT_BOOL("no-verify"),
    OPT_HIDDEN_BOOL("binary"),
    OPT_BOOL("3way"),
    OPT__QUIET(),
    OPT_SET_INT("signoff"),
    OPT_BOOL("utf8"),
    OPT_SET_INT("keep"),
    OPT_SET_INT("keep-non-patch"),
    OPT_BOOL("message-id"),
    OPT_SET_INT("keep-cr"),
    OPT_BOOL("scissors"),
    OPT_CALLBACK_F("quoted-cr", PARSE_OPT_NONEG),
    OPT_PASSTHRU_ARGV("whitespace", 0),
    OPT_PASSTHRU_ARGV("ignore-space-change", PARSE_OPT_NOARG),
    OPT_PASSTHRU_ARGV("ignore-whitespace", PARSE_OPT_NOARG),
    OPT_PASSTHRU_ARGV("directory", 0),
    OPT_PASSTHRU_ARGV("exclude", 0),
    OPT_PASSTHRU_ARGV("include", 0),
    OPT_PASSTHRU_ARGV(NULL, 0),
    OPT_PASSTHRU_ARGV(NULL, 0),
    OPT_CALLBACK("patch-format"),
    OPT_PASSTHRU_ARGV("reject", PARSE_OPT_NOARG),
    OPT_STRING("resolvemsg"),
    OPT_CMDMODE("continue"),
    OPT_CMDMODE("resolved"),
    OPT_CMDMODE("skip"),
    OPT_CMDMODE("abort"),
    OPT_CMDMODE("quit"),
    option(Type::Callback, "show-current-patch", PARSE_OPT_CMDMODE | PARSE_OPT_OPTARG | PARSE_OPT_NONEG | PARSE_OPT_LITERAL_ARGHELP),
    OPT_CMDMODE("retry"),
    OPT_CMDMODE("allow-empty"),
    OPT_BOOL("committer-date-is-author-date"),
    OPT_BOOL("ignore-date"),
    OPT_RERERE_AUTOUPDATE(),
    option(Type::String, "gpg-sign", PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("empty", PARSE_OPT_NONEG),
    OPT_HIDDEN_BOOL("rebasing"),
];
