use crate::gitcomp::*;

/// `options[]` (builtin/branch.c:730-781).
pub(super) const BRANCH_OPTIONS: &[Opt] = &[
    OPT_GROUP(),
    OPT__VERBOSE(),
    OPT__QUIET(),
    OPT_CALLBACK_F("track", PARSE_OPT_OPTARG),
    OPT_SET_INT_F("set-upstream", PARSE_OPT_HIDDEN),
    OPT_STRING("set-upstream-to"),
    OPT_BOOL("unset-upstream"),
    OPT__COLOR(),
    OPT_SET_INT_F("remotes", PARSE_OPT_NONEG),
    OPT_CONTAINS(),
    OPT_NO_CONTAINS(),
    OPT_WITH(),
    OPT_WITHOUT(),
    OPT__ABBREV(),
    OPT_GROUP(),
    OPT_SET_INT_F("all", PARSE_OPT_NONEG),
    OPT_BIT("delete"),
    OPT_BIT(NULL),
    OPT_BIT("move"),
    OPT_BIT(NULL),
    OPT_BOOL("omit-empty"),
    OPT_BIT("copy"),
    OPT_BIT(NULL),
    OPT_BOOL("list"),
    OPT_BOOL("show-current"),
    OPT_BOOL("create-reflog"),
    OPT_BOOL("edit-description"),
    OPT__FORCE(PARSE_OPT_NOCOMPLETE),
    OPT_MERGED(),
    OPT_NO_MERGED(),
    OPT_COLUMN("column"),
    OPT_REF_SORT(),
    OPT_CALLBACK("points-at"),
    OPT_BOOL("ignore-case"),
    OPT_BOOL("recurse-submodules"),
    OPT_STRING("format"),
];
