use crate::gitcomp::*;

/// `builtin_clone_options[]` (builtin/clone.c:922-1001).
pub(super) const BUILTIN_CLONE_OPTIONS: &[Opt] = &[
    // OPT__VERBOSITY (parse-options.h:545-560)
    OPT_CALLBACK_F("verbose", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("quiet", PARSE_OPT_NOARG),
    OPT_BOOL("progress"),
    OPT_BOOL("reject-shallow"),
    OPT_BOOL("no-checkout"),
    OPT_BOOL("bare"),
    OPT_HIDDEN_BOOL("naked"),
    OPT_BOOL("mirror"),
    OPT_BOOL("local"),
    OPT_BOOL("no-hardlinks"),
    OPT_BOOL("shared"),
    option(Type::Callback, "recurse-submodules", PARSE_OPT_OPTARG),
    OPT_ALIAS("recursive", "recurse-submodules"),
    OPT_INTEGER("jobs"),
    OPT_STRING("template"),
    OPT_STRING_LIST("reference"),
    OPT_STRING_LIST("reference-if-able"),
    OPT_BOOL("dissociate"),
    OPT_STRING("origin"),
    OPT_STRING("branch"),
    OPT_STRING("revision"),
    OPT_STRING("upload-pack"),
    OPT_STRING("depth"),
    OPT_STRING("shallow-since"),
    OPT_STRING_LIST("shallow-exclude"),
    OPT_BOOL("single-branch"),
    OPT_BOOL("tags"),
    OPT_BOOL("shallow-submodules"),
    OPT_STRING("separate-git-dir"),
    OPT_STRING("ref-format"),
    OPT_STRING_LIST("config"),
    OPT_STRING_LIST("server-option"),
    // OPT_IPVERSION (parse-options.h:630-634)
    OPT_SET_INT_F("ipv4", PARSE_OPT_NONEG),
    OPT_SET_INT_F("ipv6", PARSE_OPT_NONEG),
    OPT_PARSE_LIST_OBJECTS_FILTER(),
    OPT_BOOL("also-filter-submodules"),
    OPT_BOOL("remote-submodules"),
    OPT_BOOL("sparse"),
    OPT_STRING("bundle-uri"),
];
