use crate::gitcomp::*;

/// `builtin_status_options[]` (builtin/commit.c:1548-1600).
pub(super) const BUILTIN_STATUS_OPTIONS: &[Opt] = &[
    OPT__VERBOSE(),
    OPT_SET_INT("short"),
    OPT_BOOL("branch"),
    OPT_BOOL("show-stash"),
    OPT_BOOL("ahead-behind"),
    OPT_CALLBACK_F("porcelain", PARSE_OPT_OPTARG),
    OPT_SET_INT("long"),
    OPT_BOOL("null"),
    option(Type::String, "untracked-files", PARSE_OPT_OPTARG),
    option(Type::String, "ignored", PARSE_OPT_OPTARG),
    option(Type::String, "ignore-submodules", PARSE_OPT_OPTARG),
    OPT_COLUMN("column"),
    OPT_BOOL("no-renames"),
    OPT_CALLBACK_F("find-renames", PARSE_OPT_OPTARG | PARSE_OPT_NONEG),
];

/// `builtin_commit_options[]` (builtin/commit.c:1705-1786).
pub(super) const BUILTIN_COMMIT_OPTIONS: &[Opt] = &[
    OPT__QUIET(),
    OPT__VERBOSE(),
    OPT_GROUP(),
    OPT_FILENAME("file"),
    OPT_STRING("author"),
    OPT_STRING("date"),
    OPT_CALLBACK("message"),
    OPT_STRING("reedit-message"),
    OPT_STRING("reuse-message"),
    OPT_STRING("fixup"),
    OPT_STRING("squash"),
    OPT_BOOL("reset-author"),
    OPT_STRVEC("trailer"),
    OPT_BOOL("signoff"),
    OPT_FILENAME("template"),
    OPT_BOOL("edit"),
    OPT_CLEANUP(),
    OPT_BOOL("status"),
    option(Type::String, "gpg-sign", PARSE_OPT_OPTARG),
    OPT_GROUP(),
    OPT_BOOL("all"),
    OPT_BOOL("include"),
    OPT_BOOL("interactive"),
    OPT_BOOL("patch"),
    OPT_DIFF_UNIFIED(),
    OPT_DIFF_INTERHUNK_CONTEXT(),
    OPT_BOOL("only"),
    OPT_BOOL("no-verify"),
    OPT_BOOL("dry-run"),
    OPT_SET_INT("short"),
    OPT_BOOL("branch"),
    OPT_BOOL("ahead-behind"),
    OPT_SET_INT("porcelain"),
    OPT_SET_INT("long"),
    OPT_BOOL("null"),
    OPT_BOOL("amend"),
    OPT_BOOL("no-post-rewrite"),
    option(Type::String, "untracked-files", PARSE_OPT_OPTARG),
    OPT_PATHSPEC_FROM_FILE(),
    OPT_PATHSPEC_FILE_NUL(),
    OPT_HIDDEN_BOOL("allow-empty"),
    OPT_HIDDEN_BOOL("allow-empty-message"),
];
