//! `add_diff_options()` (diff.c:6038-6322), the diff option table
//! `parse_options_concat()` appends to a caller's own array. `diff_opt_parse()`
//! (diff.c:6324-6341) appends it to an empty one.
use crate::gitcomp::*;

/// `parseopts[]` (diff.c:6041-6319).
pub(super) const PARSEOPTS: &[Opt] = &[
    OPT_GROUP(),
    OPT_BITOP("patch"),
    OPT_SET_INT("no-patch"),
    OPT_BITOP(NULL),
    OPT_CALLBACK_F("unified", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_BOOL("function-context"),
    OPT_BITOP("raw"),
    OPT_BITOP("patch-with-raw"),
    OPT_BITOP("patch-with-stat"),
    OPT_BITOP("numstat"),
    OPT_BITOP("shortstat"),
    OPT_CALLBACK_F("dirstat", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("cumulative", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_CALLBACK_F("dirstat-by-file", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_BIT_F("check", PARSE_OPT_NONEG),
    OPT_BITOP("summary"),
    OPT_BIT_F("name-only", PARSE_OPT_NONEG),
    OPT_BIT_F("name-status", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("stat", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("stat-width", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("stat-name-width", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("stat-graph-width", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("stat-count", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("compact-summary", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("binary", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_BOOL("full-index"),
    OPT_COLOR_FLAG("color"),
    OPT_CALLBACK_F("ws-error-highlight", PARSE_OPT_NONEG),
    OPT_SET_INT(NULL),
    OPT__ABBREV(),
    OPT_STRING_F("src-prefix", PARSE_OPT_NONEG),
    OPT_STRING_F("dst-prefix", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("line-prefix", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("no-prefix", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_CALLBACK_F("default-prefix", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_UNSIGNED("inter-hunk-context"),
    OPT_CALLBACK_F("output-indicator-new", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("output-indicator-old", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("output-indicator-context", PARSE_OPT_NONEG),
    OPT_GROUP(),
    OPT_CALLBACK_F("break-rewrites", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("find-renames", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_SET_INT_F("irreversible-delete", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("find-copies", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_BOOL("find-copies-harder"),
    OPT_SET_INT_F("no-renames", PARSE_OPT_NONEG),
    OPT_BOOL("rename-empty"),
    OPT_CALLBACK_F("follow", PARSE_OPT_NOARG),
    OPT_INTEGER(NULL),
    OPT_GROUP(),
    OPT_CALLBACK_F("minimal", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_BIT_F("ignore-all-space", PARSE_OPT_NONEG),
    OPT_BIT_F("ignore-space-change", PARSE_OPT_NONEG),
    OPT_BIT_F("ignore-space-at-eol", PARSE_OPT_NONEG),
    OPT_BIT_F("ignore-cr-at-eol", PARSE_OPT_NONEG),
    OPT_BIT_F("ignore-blank-lines", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("ignore-matching-lines", 0),
    OPT_BIT("indent-heuristic"),
    OPT_CALLBACK_F("patience", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_CALLBACK_F("histogram", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_CALLBACK_F("diff-algorithm", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("anchored", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("word-diff", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("word-diff-regex", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("color-words", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("color-moved", PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("color-moved-ws", 0),
    OPT_GROUP(),
    OPT_CALLBACK_F("relative", PARSE_OPT_OPTARG),
    OPT_BOOL("text"),
    OPT_BOOL(NULL),
    OPT_BOOL("exit-code"),
    OPT_BOOL("quiet"),
    OPT_BOOL("ext-diff"),
    OPT_CALLBACK_F("textconv", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("ignore-submodules", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_CALLBACK_F("submodule", PARSE_OPT_NONEG | PARSE_OPT_OPTARG),
    OPT_SET_INT_F("ita-invisible-in-index", PARSE_OPT_NONEG),
    OPT_SET_INT_F("ita-visible-in-index", PARSE_OPT_NONEG),
    OPT_CALLBACK_F(NULL, 0),
    OPT_CALLBACK_F(NULL, 0),
    OPT_BIT_F("pickaxe-all", PARSE_OPT_NONEG),
    OPT_BIT_F("pickaxe-regex", PARSE_OPT_NONEG),
    OPT_FILENAME(NULL),
    OPT_CALLBACK_F("rotate-to", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("skip-to", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("find-object", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("diff-filter", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("max-depth", PARSE_OPT_NONEG),
    option(Type::Callback, "output", PARSE_OPT_NONEG),
];
