use crate::gitcomp::*;

/// `builtin_fetch_options[]` (builtin/fetch.c:2500-2591).
pub(super) const BUILTIN_FETCH_OPTIONS: &[Opt] = &[
    // OPT__VERBOSITY (parse-options.h:545-560)
    OPT_CALLBACK_F("verbose", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("quiet", PARSE_OPT_NOARG),
    OPT_BOOL("all"),
    OPT_BOOL("set-upstream"),
    OPT_BOOL("append"),
    OPT_BOOL("atomic"),
    OPT_STRING("upload-pack"),
    OPT__FORCE(0),
    OPT_BOOL("multiple"),
    OPT_SET_INT("tags"),
    OPT_SET_INT(NULL),
    OPT_INTEGER("jobs"),
    OPT_BOOL("prefetch"),
    OPT_BOOL("prune"),
    OPT_BOOL("prune-tags"),
    OPT_CALLBACK_F("recurse-submodules", PARSE_OPT_OPTARG),
    OPT_BOOL("dry-run"),
    OPT_BOOL("porcelain"),
    OPT_BOOL("write-fetch-head"),
    OPT_BOOL("keep"),
    OPT_BOOL("update-head-ok"),
    OPT_BOOL("progress"),
    OPT_STRING("depth"),
    OPT_STRING("shallow-since"),
    OPT_STRING_LIST("shallow-exclude"),
    OPT_INTEGER("deepen"),
    OPT_SET_INT_F("unshallow", PARSE_OPT_NONEG),
    OPT_SET_INT_F("refetch", PARSE_OPT_NONEG),
    option(Type::String, "submodule-prefix", PARSE_OPT_HIDDEN),
    OPT_CALLBACK_F("recurse-submodules-default", PARSE_OPT_HIDDEN),
    OPT_BOOL("update-shallow"),
    OPT_CALLBACK_F("refmap", PARSE_OPT_NONEG),
    OPT_STRING_LIST("server-option"),
    // OPT_IPVERSION (parse-options.h:630-634)
    OPT_SET_INT_F("ipv4", PARSE_OPT_NONEG),
    OPT_SET_INT_F("ipv6", PARSE_OPT_NONEG),
    OPT_STRING_LIST("negotiation-restrict"),
    OPT_ALIAS("negotiation-tip", "negotiation-restrict"),
    OPT_STRING_LIST("negotiation-include"),
    OPT_BOOL("negotiate-only"),
    OPT_PARSE_LIST_OBJECTS_FILTER(),
    OPT_BOOL("auto-maintenance"),
    OPT_BOOL("auto-gc"),
    OPT_BOOL("show-forced-updates"),
    OPT_BOOL("write-commit-graph"),
    OPT_BOOL("stdin"),
];
