use crate::gitcomp::*;

/// `options[]` (builtin/grep.c:1056-1178).
pub(super) const GREP_OPTIONS: &[Opt] = &[
    OPT_BOOL("cached"),
    OPT_NEGBIT("no-index"),
    OPT_BOOL("untracked"),
    OPT_SET_INT("exclude-standard"),
    OPT_BOOL("recurse-submodules"),
    OPT_GROUP(),
    OPT_BOOL("invert-match"),
    OPT_BOOL("ignore-case"),
    OPT_BOOL("word-regexp"),
    OPT_SET_INT("text"),
    OPT_SET_INT(NULL),
    OPT_BOOL("textconv"),
    OPT_SET_INT("recursive"),
    OPT_INTEGER_F("max-depth", PARSE_OPT_NONEG),
    OPT_GROUP(),
    OPT_SET_INT("extended-regexp"),
    OPT_SET_INT("basic-regexp"),
    OPT_SET_INT("fixed-strings"),
    OPT_SET_INT("perl-regexp"),
    OPT_GROUP(),
    OPT_BOOL("line-number"),
    OPT_BOOL("column"),
    OPT_NEGBIT(NULL),
    OPT_BIT(NULL),
    OPT_NEGBIT("full-name"),
    OPT_BOOL("files-with-matches"),
    OPT_BOOL("name-only"),
    OPT_BOOL("files-without-match"),
    OPT_BOOL_F("null", PARSE_OPT_NOCOMPLETE),
    OPT_BOOL("only-matching"),
    OPT_BOOL("count"),
    OPT__COLOR(),
    OPT_BOOL("break"),
    OPT_BOOL("heading"),
    OPT_GROUP(),
    OPT_CALLBACK("context"),
    OPT_UNSIGNED("before-context"),
    OPT_UNSIGNED("after-context"),
    OPT_INTEGER("threads"),
    OPT_NUMBER_CALLBACK(),
    OPT_BOOL("show-function"),
    OPT_BOOL("function-context"),
    OPT_GROUP(),
    OPT_CALLBACK(NULL),
    OPT_CALLBACK_F(NULL, PARSE_OPT_NONEG),
    OPT_CALLBACK_F("and", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_BOOL_F("or", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("not", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_CALLBACK_F(NULL, PARSE_OPT_NOARG | PARSE_OPT_NONEG | PARSE_OPT_NODASH),
    OPT_CALLBACK_F(NULL, PARSE_OPT_NOARG | PARSE_OPT_NONEG | PARSE_OPT_NODASH),
    OPT__QUIET(),
    OPT_BOOL("all-match"),
    OPT_GROUP(),
    option(Type::String, "open-files-in-pager", PARSE_OPT_OPTARG | PARSE_OPT_NOCOMPLETE),
    OPT_BOOL_F("ext-grep", PARSE_OPT_NOCOMPLETE),
    OPT_INTEGER("max-count"),
];
