use crate::gitcomp::*;

/// `builtin_ls_files_options[]` (builtin/ls-files.c:600-667).
pub(super) const BUILTIN_LS_FILES_OPTIONS: &[Opt] = &[
    OPT_SET_INT(NULL),
    OPT_BOOL(NULL),
    OPT_BOOL(NULL),
    OPT_BOOL(NULL),
    OPT_BOOL("cached"),
    OPT_BOOL("deleted"),
    OPT_BOOL("modified"),
    OPT_BOOL("others"),
    OPT_BIT("ignored"),
    OPT_BOOL("stage"),
    OPT_BOOL("killed"),
    OPT_BIT("directory"),
    OPT_BOOL("eol"),
    OPT_NEGBIT("empty-directory"),
    OPT_BOOL("unmerged"),
    OPT_BOOL("resolve-undo"),
    OPT_CALLBACK_F("exclude", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("exclude-from", PARSE_OPT_NONEG),
    OPT_STRING("exclude-per-directory"),
    OPT_CALLBACK_F("exclude-standard", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_SET_INT_F("full-name", PARSE_OPT_NONEG),
    OPT_BOOL("recurse-submodules"),
    OPT_BOOL("error-unmatch"),
    OPT_STRING("with-tree"),
    OPT__ABBREV(),
    OPT_BOOL("debug"),
    OPT_BOOL("deduplicate"),
    OPT_BOOL("sparse"),
    OPT_STRING_F("format", PARSE_OPT_NONEG),
];
