use crate::gitcomp::*;

/// `pack_objects_options[]` (builtin/pack-objects.c:5045-5155).
pub(super) const PACK_OBJECTS_OPTIONS: &[Opt] = &[
    OPT_CALLBACK_F("quiet", PARSE_OPT_NOARG),
    OPT_SET_INT("progress"),
    OPT_SET_INT("all-progress"),
    OPT_BOOL("all-progress-implied"),
    OPT_CALLBACK_F("index-version", PARSE_OPT_NONEG),
    OPT_UNSIGNED("max-pack-size"),
    OPT_BOOL("local"),
    OPT_BOOL("incremental"),
    OPT_INTEGER("window"),
    OPT_UNSIGNED("window-memory"),
    OPT_INTEGER("depth"),
    OPT_BOOL("reuse-delta"),
    OPT_BOOL("reuse-object"),
    OPT_BOOL("delta-base-offset"),
    OPT_INTEGER("threads"),
    OPT_BOOL("non-empty"),
    OPT_BOOL("revs"),
    OPT_SET_INT_F("unpacked", PARSE_OPT_NONEG),
    OPT_SET_INT_F("all", PARSE_OPT_NONEG),
    OPT_SET_INT_F("reflog", PARSE_OPT_NONEG),
    OPT_SET_INT_F("indexed-objects", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("stdin-packs", PARSE_OPT_OPTARG),
    OPT_BOOL("stdout"),
    OPT_BOOL("include-tag"),
    OPT_BOOL("keep-unreachable"),
    OPT_BOOL("pack-loose-unreachable"),
    OPT_CALLBACK_F("unpack-unreachable", PARSE_OPT_OPTARG),
    OPT_BOOL("cruft"),
    OPT_CALLBACK_F("cruft-expiration", PARSE_OPT_OPTARG),
    OPT_BOOL("sparse"),
    OPT_BOOL("thin"),
    OPT_BOOL("path-walk"),
    OPT_BOOL("shallow"),
    OPT_BOOL("honor-pack-keep"),
    OPT_STRING_LIST("keep-pack"),
    OPT_INTEGER("compression"),
    OPT_BOOL("keep-true-parents"),
    OPT_BOOL("use-bitmap-index"),
    OPT_SET_INT("write-bitmap-index"),
    OPT_SET_INT_F("write-bitmap-index-quiet", PARSE_OPT_HIDDEN),
    OPT_PARSE_LIST_OBJECTS_FILTER(),
    OPT_CALLBACK_F("missing", PARSE_OPT_NONEG),
    OPT_BOOL("exclude-promisor-objects"),
    OPT_BOOL("exclude-promisor-objects-best-effort"),
    OPT_BOOL("delta-islands"),
    OPT_STRING_LIST("uri-protocol"),
    OPT_INTEGER("name-hash-version"),
];
