use crate::gitcomp::*;

/// `pull_options[]` (builtin/pull.c:869-1013).
pub(super) const PULL_OPTIONS: &[Opt] = &[
    // OPT__VERBOSITY (parse-options.h:545-560)
    OPT_CALLBACK_F("verbose", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("quiet", PARSE_OPT_NOARG),
    OPT_PASSTHRU("progress", PARSE_OPT_NOARG),
    OPT_CALLBACK_F("recurse-submodules", PARSE_OPT_OPTARG),
    OPT_GROUP(),
    OPT_CALLBACK_F("rebase", PARSE_OPT_OPTARG),
    OPT_PASSTHRU(NULL, PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_PASSTHRU("stat", PARSE_OPT_NOARG),
    OPT_PASSTHRU("summary", PARSE_OPT_NOARG | PARSE_OPT_HIDDEN),
    OPT_PASSTHRU("compact-summary", PARSE_OPT_NOARG),
    OPT_PASSTHRU("log", PARSE_OPT_OPTARG),
    OPT_PASSTHRU("signoff", PARSE_OPT_OPTARG),
    OPT_PASSTHRU("squash", PARSE_OPT_NOARG),
    OPT_PASSTHRU("commit", PARSE_OPT_NOARG),
    OPT_PASSTHRU("edit", PARSE_OPT_NOARG),
    OPT_CLEANUP(),
    OPT_PASSTHRU("ff", PARSE_OPT_NOARG),
    OPT_PASSTHRU("ff-only", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_PASSTHRU("verify", PARSE_OPT_NOARG),
    OPT_PASSTHRU("verify-signatures", PARSE_OPT_NOARG),
    OPT_BOOL("autostash"),
    OPT_PASSTHRU_ARGV("strategy", 0),
    OPT_PASSTHRU_ARGV("strategy-option", 0),
    OPT_PASSTHRU("gpg-sign", PARSE_OPT_OPTARG),
    OPT_SET_INT("allow-unrelated-histories"),
    OPT_GROUP(),
    OPT_PASSTHRU("all", PARSE_OPT_NOARG),
    OPT_PASSTHRU("append", PARSE_OPT_NOARG),
    OPT_PASSTHRU("upload-pack", 0),
    OPT__FORCE(0),
    OPT_PASSTHRU("tags", PARSE_OPT_NOARG),
    OPT_PASSTHRU("prune", PARSE_OPT_NOARG),
    OPT_PASSTHRU("jobs", PARSE_OPT_OPTARG),
    OPT_BOOL("dry-run"),
    OPT_PASSTHRU("keep", PARSE_OPT_NOARG),
    OPT_PASSTHRU("depth", 0),
    OPT_PASSTHRU_ARGV("shallow-since", 0),
    OPT_PASSTHRU_ARGV("shallow-exclude", 0),
    OPT_PASSTHRU_ARGV("deepen", 0),
    OPT_PASSTHRU("unshallow", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_PASSTHRU("update-shallow", PARSE_OPT_NOARG),
    OPT_PASSTHRU("refmap", PARSE_OPT_NONEG),
    OPT_PASSTHRU_ARGV("server-option", 0),
    OPT_PASSTHRU("ipv4", PARSE_OPT_NOARG),
    OPT_PASSTHRU("ipv6", PARSE_OPT_NOARG),
    OPT_PASSTHRU_ARGV("negotiation-restrict", 0),
    OPT_ALIAS("negotiation-tip", "negotiation-restrict"),
    OPT_PASSTHRU_ARGV("negotiation-include", 0),
    OPT_BOOL("show-forced-updates"),
    OPT_PASSTHRU("set-upstream", PARSE_OPT_NOARG),
];
