use crate::gitcomp::*;

/// `builtin_rebase_options[]` (builtin/rebase.c:1120-1248).
pub(super) const BUILTIN_REBASE_OPTIONS: &[Opt] = &[
    OPT_STRING("onto"),
    OPT_BOOL("keep-base"),
    OPT_BOOL("no-verify"),
    OPT_NEGBIT("quiet"),
    OPT_BIT("verbose"),
    option(Type::NegBit, "no-stat", PARSE_OPT_NOARG),
    OPT_STRVEC("trailer"),
    OPT_BOOL("signoff"),
    OPT_BOOL("committer-date-is-author-date"),
    OPT_BOOL("reset-author-date"),
    OPT_HIDDEN_BOOL("ignore-date"),
    OPT_PASSTHRU_ARGV(NULL, 0),
    OPT_BOOL("ignore-whitespace"),
    OPT_PASSTHRU_ARGV("whitespace", 0),
    OPT_BIT("force-rebase"),
    OPT_BIT("no-ff"),
    OPT_CMDMODE("continue"),
    OPT_CMDMODE("skip"),
    OPT_CMDMODE("abort"),
    OPT_CMDMODE("quit"),
    OPT_CMDMODE("edit-todo"),
    OPT_CMDMODE("show-current-patch"),
    OPT_CALLBACK_F("apply", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_CALLBACK_F("merge", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_CALLBACK_F("interactive", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_SET_INT_F("preserve-merges", PARSE_OPT_HIDDEN),
    OPT_RERERE_AUTOUPDATE(),
    OPT_CALLBACK_F("empty", PARSE_OPT_NONEG),
    OPT_CALLBACK_F("keep-empty", PARSE_OPT_NOARG | PARSE_OPT_HIDDEN),
    OPT_BOOL("autosquash"),
    OPT_BOOL("update-refs"),
    option(Type::String, "gpg-sign", PARSE_OPT_OPTARG),
    OPT_AUTOSTASH(),
    OPT_STRING_LIST("exec"),
    OPT_BOOL_F("allow-empty-message", PARSE_OPT_HIDDEN),
    OPT_CALLBACK_F("rebase-merges", PARSE_OPT_OPTARG),
    OPT_BOOL("fork-point"),
    OPT_STRING("strategy"),
    OPT_STRING_LIST("strategy-option"),
    OPT_BOOL("root"),
    OPT_BOOL("reschedule-failed-exec"),
    OPT_BOOL("reapply-cherry-picks"),
];
