use crate::gitcomp::*;

/// `builtin_repack_options[]` (builtin/repack.c:167-236).
pub(super) const BUILTIN_REPACK_OPTIONS: &[Opt] = &[
    OPT_BIT(NULL),
    OPT_BIT(NULL),
    OPT_BIT("cruft"),
    OPT_STRING("cruft-expiration"),
    OPT_UNSIGNED("combine-cruft-below-size"),
    OPT_UNSIGNED("max-cruft-size"),
    OPT_BOOL(NULL),
    OPT_BOOL(NULL),
    OPT_BOOL(NULL),
    OPT_INTEGER("name-hash-version"),
    OPT_BOOL("path-walk"),
    OPT_NEGBIT(NULL),
    OPT__QUIET(),
    OPT_BOOL("local"),
    OPT_BOOL("write-bitmap-index"),
    OPT_BOOL("delta-islands"),
    OPT_STRING("unpack-unreachable"),
    OPT_BOOL("keep-unreachable"),
    OPT_STRING("window"),
    OPT_STRING("window-memory"),
    OPT_STRING("depth"),
    OPT_STRING("threads"),
    OPT_UNSIGNED("max-pack-size"),
    OPT_PARSE_LIST_OBJECTS_FILTER(),
    OPT_BOOL("pack-kept-objects"),
    OPT_STRING_LIST("keep-pack"),
    OPT_INTEGER("geometric"),
    OPT_CALLBACK_F("write-midx", PARSE_OPT_OPTARG),
    OPT_SET_INT_F(NULL, PARSE_OPT_HIDDEN),
    OPT_STRING("expire-to"),
    OPT_STRING("filter-to"),
];
