use crate::gitcomp::*;

/// `options[]` (builtin/tag.c:481-538).
pub(super) const TAG_OPTIONS: &[Opt] = &[
    OPT_CMDMODE("list"),
    option(Type::Integer, NULL, PARSE_OPT_OPTARG),
    OPT_CMDMODE("delete"),
    OPT_CMDMODE("verify"),
    OPT_GROUP(),
    OPT_BOOL("annotate"),
    OPT_CALLBACK_F("message", PARSE_OPT_NONEG),
    OPT_FILENAME("file"),
    OPT_STRVEC("trailer"),
    OPT_BOOL("edit"),
    OPT_BOOL("sign"),
    OPT_CLEANUP(),
    OPT_STRING("local-user"),
    OPT__FORCE(0),
    OPT_BOOL("create-reflog"),
    OPT_GROUP(),
    OPT_COLUMN("column"),
    OPT_CONTAINS(),
    OPT_NO_CONTAINS(),
    OPT_WITH(),
    OPT_WITHOUT(),
    OPT_MERGED(),
    OPT_NO_MERGED(),
    OPT_BOOL("omit-empty"),
    OPT_REF_SORT(),
    option(Type::Callback, "points-at", PARSE_OPT_LASTARG_DEFAULT),
    OPT_STRING("format"),
    OPT__COLOR(),
    OPT_BOOL("ignore-case"),
];
