use crate::gitcomp::*;

/// `options[]` (builtin/update-index.c:937-1095).
pub(super) const UPDATE_INDEX_OPTIONS: &[Opt] = &[
    OPT_BIT(NULL),
    OPT_BIT("ignore-submodules"),
    OPT_SET_INT("add"),
    OPT_SET_INT("replace"),
    OPT_SET_INT("remove"),
    OPT_BIT("unmerged"),
    OPT_CALLBACK_F("refresh", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_CALLBACK_F("really-refresh", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    option(Type::LowlevelCallback, "cacheinfo", PARSE_OPT_NOARG | PARSE_OPT_NONEG | PARSE_OPT_LITERAL_ARGHELP),
    OPT_CALLBACK_F("chmod", PARSE_OPT_NONEG),
    option(Type::SetInt, "assume-unchanged", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    option(Type::SetInt, "no-assume-unchanged", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    option(Type::SetInt, "skip-worktree", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    option(Type::SetInt, "no-skip-worktree", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_BOOL("ignore-skip-worktree-entries"),
    OPT_SET_INT("info-only"),
    OPT_SET_INT("force-remove"),
    OPT_BOOL(NULL),
    option(Type::LowlevelCallback, "stdin", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    option(Type::LowlevelCallback, "index-info", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    option(Type::LowlevelCallback, "unresolve", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    option(Type::LowlevelCallback, "again", PARSE_OPT_NONEG | PARSE_OPT_NOARG),
    OPT_BIT("ignore-missing"),
    OPT_SET_INT("verbose"),
    OPT_CALLBACK_F("clear-resolve-undo", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    OPT_INTEGER("index-version"),
    OPT_SET_INT("show-index-version"),
    OPT_BOOL("split-index"),
    OPT_BOOL("untracked-cache"),
    OPT_SET_INT("test-untracked-cache"),
    OPT_SET_INT("force-untracked-cache"),
    OPT_SET_INT("force-write-index"),
    OPT_BOOL("fsmonitor"),
    option(Type::SetInt, "fsmonitor-valid", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
    option(Type::SetInt, "no-fsmonitor-valid", PARSE_OPT_NOARG | PARSE_OPT_NONEG),
];
