//! Subcommand routing for the shadow `git` binary.
//!
//! Two namespaces share one dispatch table:
//!   * **superset** verbs (`z*`) — the novel coordination layer, [`superset`].
//!   * **git-compat** porcelain — stock git subcommands served via gitoxide,
//!     ported incrementally, [`porcelain`].

use crate::{porcelain, superset};
use anyhow::Result;
use std::process::ExitCode;

/// zvcs-native extension verbs — the superset that stock git does not have.
pub const SUPERSET_VERBS: &[&str] = &["zsync", "zbump", "zdaemon"];

pub fn run(sub: &str, args: &[String]) -> Result<ExitCode> {
    match sub {
        // ---- superset (novel) ----
        "zsync" => superset::zsync(args),
        "zbump" => superset::zbump(args),
        "zdaemon" => superset::zdaemon(args),

        // ---- BEGIN generated porcelain arms (scripts/wire_dispatch.pl) ----
        "add" => porcelain::add(args),
        "am" => porcelain::am(args),
        "annotate" => porcelain::annotate(args),
        "apply" => porcelain::apply(args),
        "archive" => porcelain::archive(args),
        "backfill" => porcelain::backfill(args),
        "bisect" => porcelain::bisect(args),
        "blame" => porcelain::blame(args),
        "branch" => porcelain::branch(args),
        "bundle" => porcelain::bundle(args),
        "cat-file" => porcelain::cat_file(args),
        "check-attr" => porcelain::check_attr(args),
        "check-ignore" => porcelain::check_ignore(args),
        "check-mailmap" => porcelain::check_mailmap(args),
        "check-ref-format" => porcelain::check_ref_format(args),
        "checkout" => porcelain::checkout(args),
        "cherry" => porcelain::cherry(args),
        "cherry-pick" => porcelain::cherry_pick(args),
        "clean" => porcelain::clean(args),
        "clone" => porcelain::clone(args),
        "commit" => porcelain::commit(args),
        "commit-graph" => porcelain::commit_graph(args),
        "commit-tree" => porcelain::commit_tree(args),
        "config" => porcelain::config(args),
        "count-objects" => porcelain::count_objects(args),
        "credential" => porcelain::credential(args),
        "credential-cache" => porcelain::credential_cache(args),
        "credential-cache--daemon" => porcelain::credential_cache__daemon(args),
        "credential-netrc" => porcelain::credential_netrc(args),
        "credential-osxkeychain" => porcelain::credential_osxkeychain(args),
        "credential-store" => porcelain::credential_store(args),
        "daemon" => porcelain::daemon(args),
        "describe" => porcelain::describe(args),
        "diff" => porcelain::diff(args),
        "diff-files" => porcelain::diff_files(args),
        "diff-index" => porcelain::diff_index(args),
        "diff-tree" => porcelain::diff_tree(args),
        "difftool" => porcelain::difftool(args),
        "fast-export" => porcelain::fast_export(args),
        "fast-import" => porcelain::fast_import(args),
        "fetch" => porcelain::fetch(args),
        "fetch-pack" => porcelain::fetch_pack(args),
        "fmt-merge-msg" => porcelain::fmt_merge_msg(args),
        "for-each-ref" => porcelain::for_each_ref(args),
        "format-patch" => porcelain::format_patch(args),
        "fsck" => porcelain::fsck(args),
        "fsmonitor--daemon" => porcelain::fsmonitor__daemon(args),
        "gc" => porcelain::gc(args),
        "grep" => porcelain::grep(args),
        "hash-object" => porcelain::hash_object(args),
        "http-backend" => porcelain::http_backend(args),
        "http-fetch" => porcelain::http_fetch(args),
        "http-push" => porcelain::http_push(args),
        "index-pack" => porcelain::index_pack(args),
        "init" => porcelain::init(args),
        "interpret-trailers" => porcelain::interpret_trailers(args),
        "log" => porcelain::log(args),
        "ls-files" => porcelain::ls_files(args),
        "ls-remote" => porcelain::ls_remote(args),
        "ls-tree" => porcelain::ls_tree(args),
        "maintenance" => porcelain::maintenance(args),
        "merge" => porcelain::merge(args),
        "merge-base" => porcelain::merge_base(args),
        "merge-file" => porcelain::merge_file(args),
        "merge-index" => porcelain::merge_index(args),
        "merge-tree" => porcelain::merge_tree(args),
        "mergetool" => porcelain::mergetool(args),
        "mktag" => porcelain::mktag(args),
        "mktree" => porcelain::mktree(args),
        "multi-pack-index" => porcelain::multi_pack_index(args),
        "mv" => porcelain::mv(args),
        "name-rev" => porcelain::name_rev(args),
        "notes" => porcelain::notes(args),
        "pack-objects" => porcelain::pack_objects(args),
        "pack-refs" => porcelain::pack_refs(args),
        "patch-id" => porcelain::patch_id(args),
        "prune" => porcelain::prune(args),
        "prune-packed" => porcelain::prune_packed(args),
        "pull" => porcelain::pull(args),
        "push" => porcelain::push(args),
        "range-diff" => porcelain::range_diff(args),
        "read-tree" => porcelain::read_tree(args),
        "rebase" => porcelain::rebase(args),
        "receive-pack" => porcelain::receive_pack(args),
        "reflog" => porcelain::reflog(args),
        "refs" => porcelain::refs(args),
        "remote" => porcelain::remote(args),
        "remote-ext" => porcelain::remote_ext(args),
        "remote-fd" => porcelain::remote_fd(args),
        "remote-ftp" => porcelain::remote_ftp(args),
        "remote-ftps" => porcelain::remote_ftps(args),
        "remote-http" => porcelain::remote_http(args),
        "remote-https" => porcelain::remote_https(args),
        "repack" => porcelain::repack(args),
        "replace" => porcelain::replace(args),
        "repo" => porcelain::repo(args),
        "request-pull" => porcelain::request_pull(args),
        "rerere" => porcelain::rerere(args),
        "reset" => porcelain::reset(args),
        "restore" => porcelain::restore(args),
        "rev-list" => porcelain::rev_list(args),
        "rev-parse" => porcelain::rev_parse(args),
        "revert" => porcelain::revert(args),
        "rm" => porcelain::rm(args),
        "send-pack" => porcelain::send_pack(args),
        "shortlog" => porcelain::shortlog(args),
        "show" => porcelain::show(args),
        "show-branch" => porcelain::show_branch(args),
        "show-index" => porcelain::show_index(args),
        "show-ref" => porcelain::show_ref(args),
        "sparse-checkout" => porcelain::sparse_checkout(args),
        "stage" => porcelain::stage(args),
        "stash" => porcelain::stash(args),
        "status" => porcelain::status(args),
        "stripspace" => porcelain::stripspace(args),
        "submodule" => porcelain::submodule(args),
        "switch" => porcelain::switch(args),
        "symbolic-ref" => porcelain::symbolic_ref(args),
        "tag" => porcelain::tag(args),
        "unpack-file" => porcelain::unpack_file(args),
        "unpack-objects" => porcelain::unpack_objects(args),
        "update-index" => porcelain::update_index(args),
        "update-ref" => porcelain::update_ref(args),
        "update-server-info" => porcelain::update_server_info(args),
        "upload-archive" => porcelain::upload_archive(args),
        "upload-pack" => porcelain::upload_pack(args),
        "var" => porcelain::var(args),
        "verify-commit" => porcelain::verify_commit(args),
        "verify-pack" => porcelain::verify_pack(args),
        "verify-tag" => porcelain::verify_tag(args),
        "whatchanged" => porcelain::whatchanged(args),
        "worktree" => porcelain::worktree(args),
        "write-tree" => porcelain::write_tree(args),
        // ---- END generated porcelain arms ----

        // Not yet ported. No fallthrough to stock git — this is a from-scratch engine.
        _ => anyhow::bail!("not yet ported (superset verbs: {})", SUPERSET_VERBS.join(", ")),
    }
}
