//! Subcommand routing for the shadow `git` binary.
//!
//! Two namespaces share one dispatch table:
//!   * **superset** verbs (`z*`) — the novel coordination layer, [`superset`].
//!   * **git-compat** porcelain — stock git subcommands served via gitoxide,
//!     ported incrementally, [`porcelain`].

use crate::{porcelain, superset};
use anyhow::Result;
use std::process::ExitCode;

/// zvcs-native extension verbs — the superset that stock git does not have.
pub const SUPERSET_VERBS: &[&str] = &[
    "zsync", "zbump", "zdaemon", "zrepos", "zreindex", "zjobs", "zjob", "zcommit", "zpush",
    "zrepl", "zclaim", "zunclaim", "zwho",
];

pub fn run(sub: &str, args: &[String]) -> Result<ExitCode> {
    match sub {
        // ---- superset (novel) ----
        "zsync" => superset::zsync(args),
        "zbump" => superset::zbump(args),
        "zdaemon" => superset::zdaemon(args),
        "zrepos" => superset::zrepos(args),
        "zreindex" => superset::zreindex(args),
        "zjobs" => superset::zjobs(args),
        "zjob" => superset::zjob(args),
        "zcommit" => superset::zcommit(args),
        "zpush" => superset::zpush(args),
        "zrepl" => superset::zrepl(args),
        "zclaim" => superset::zclaim(args),
        "zunclaim" => superset::zunclaim(args),
        "zwho" => superset::zwho(args),

        // ---- BEGIN generated porcelain arms (scripts/wire_dispatch.pl) ----
        "add" => porcelain::add(args),
        "am" => porcelain::am(args),
        "annotate" => porcelain::annotate(args),
        "apply" => porcelain::apply(args),
        "archimport" => porcelain::archimport(args),
        "archive" => porcelain::archive(args),
        "backfill" => porcelain::backfill(args),
        "bisect" => porcelain::bisect(args),
        "blame" => porcelain::blame(args),
        "branch" => porcelain::branch(args),
        "bugreport" => porcelain::bugreport(args),
        "bundle" => porcelain::bundle(args),
        "cat-file" => porcelain::cat_file(args),
        "check-attr" => porcelain::check_attr(args),
        "check-ignore" => porcelain::check_ignore(args),
        "check-mailmap" => porcelain::check_mailmap(args),
        "check-ref-format" => porcelain::check_ref_format(args),
        "checkout" => porcelain::checkout(args),
        "checkout--worker" => porcelain::checkout__worker(args),
        "checkout-index" => porcelain::checkout_index(args),
        "cherry" => porcelain::cherry(args),
        "cherry-pick" => porcelain::cherry_pick(args),
        "clean" => porcelain::clean(args),
        "clone" => porcelain::clone(args),
        "column" => porcelain::column(args),
        "commit" => porcelain::commit(args),
        "commit-graph" => porcelain::commit_graph(args),
        "commit-tree" => porcelain::commit_tree(args),
        "config" => porcelain::config(args),
        "count-objects" => porcelain::count_objects(args),
        "credential" => porcelain::credential(args),
        "credential-cache" => porcelain::credential_cache(args),
        "credential-cache--daemon" => porcelain::credential_cache__daemon(args),
        "credential-netrc" => porcelain::credential_netrc(args),
        "credential-osxkeychain" => porcelain::credential_osxkeychain(args),
        "credential-store" => porcelain::credential_store(args),
        "cvsexportcommit" => porcelain::cvsexportcommit(args),
        "cvsimport" => porcelain::cvsimport(args),
        "cvsserver" => porcelain::cvsserver(args),
        "daemon" => porcelain::daemon(args),
        "describe" => porcelain::describe(args),
        "diagnose" => porcelain::diagnose(args),
        "diff" => porcelain::diff(args),
        "diff-files" => porcelain::diff_files(args),
        "diff-index" => porcelain::diff_index(args),
        "diff-pairs" => porcelain::diff_pairs(args),
        "diff-tree" => porcelain::diff_tree(args),
        "difftool" => porcelain::difftool(args),
        "difftool--helper" => porcelain::difftool__helper(args),
        "fast-export" => porcelain::fast_export(args),
        "fast-import" => porcelain::fast_import(args),
        "fetch" => porcelain::fetch(args),
        "fetch-pack" => porcelain::fetch_pack(args),
        "filter-branch" => porcelain::filter_branch(args),
        "fmt-merge-msg" => porcelain::fmt_merge_msg(args),
        "for-each-ref" => porcelain::for_each_ref(args),
        "for-each-repo" => porcelain::for_each_repo(args),
        "format-patch" => porcelain::format_patch(args),
        "format-rev" => porcelain::format_rev(args),
        "fsck" => porcelain::fsck(args),
        "fsck-objects" => porcelain::fsck_objects(args),
        "fsmonitor--daemon" => porcelain::fsmonitor__daemon(args),
        "gc" => porcelain::gc(args),
        "get-tar-commit-id" => porcelain::get_tar_commit_id(args),
        "grep" => porcelain::grep(args),
        "hash-object" => porcelain::hash_object(args),
        "help" => porcelain::help(args),
        "history" => porcelain::history(args),
        "hook" => porcelain::hook(args),
        "http-backend" => porcelain::http_backend(args),
        "http-fetch" => porcelain::http_fetch(args),
        "http-push" => porcelain::http_push(args),
        "imap-send" => porcelain::imap_send(args),
        "index-pack" => porcelain::index_pack(args),
        "init" => porcelain::init(args),
        "init-db" => porcelain::init_db(args),
        "instaweb" => porcelain::instaweb(args),
        "interpret-trailers" => porcelain::interpret_trailers(args),
        "jump" => porcelain::jump(args),
        "last-modified" => porcelain::last_modified(args),
        "log" => porcelain::log(args),
        "ls-files" => porcelain::ls_files(args),
        "ls-remote" => porcelain::ls_remote(args),
        "ls-tree" => porcelain::ls_tree(args),
        "mailinfo" => porcelain::mailinfo(args),
        "mailsplit" => porcelain::mailsplit(args),
        "maintenance" => porcelain::maintenance(args),
        "merge" => porcelain::merge(args),
        "merge-base" => porcelain::merge_base(args),
        "merge-file" => porcelain::merge_file(args),
        "merge-index" => porcelain::merge_index(args),
        "merge-octopus" => porcelain::merge_octopus(args),
        "merge-one-file" => porcelain::merge_one_file(args),
        "merge-ours" => porcelain::merge_ours(args),
        "merge-recursive" => porcelain::merge_recursive(args),
        "merge-recursive-ours" => porcelain::merge_recursive_ours(args),
        "merge-recursive-theirs" => porcelain::merge_recursive_theirs(args),
        "merge-resolve" => porcelain::merge_resolve(args),
        "merge-subtree" => porcelain::merge_subtree(args),
        "merge-tree" => porcelain::merge_tree(args),
        "mergetool" => porcelain::mergetool(args),
        "mktag" => porcelain::mktag(args),
        "mktree" => porcelain::mktree(args),
        "multi-pack-index" => porcelain::multi_pack_index(args),
        "mv" => porcelain::mv(args),
        "name-rev" => porcelain::name_rev(args),
        "notes" => porcelain::notes(args),
        "p4" => porcelain::p4(args),
        "pack-objects" => porcelain::pack_objects(args),
        "pack-redundant" => porcelain::pack_redundant(args),
        "pack-refs" => porcelain::pack_refs(args),
        "patch-id" => porcelain::patch_id(args),
        "pickaxe" => porcelain::pickaxe(args),
        "prune" => porcelain::prune(args),
        "prune-packed" => porcelain::prune_packed(args),
        "pull" => porcelain::pull(args),
        "push" => porcelain::push(args),
        "quiltimport" => porcelain::quiltimport(args),
        "range-diff" => porcelain::range_diff(args),
        "read-tree" => porcelain::read_tree(args),
        "rebase" => porcelain::rebase(args),
        "receive-pack" => porcelain::receive_pack(args),
        "reflog" => porcelain::reflog(args),
        "refs" => porcelain::refs(args),
        "remote" => porcelain::remote(args),
        "remote-ext" => porcelain::remote_ext(args),
        "remote-fd" => porcelain::remote_fd(args),
        "remote-ftp" => porcelain::remote_ftp(args),
        "remote-ftps" => porcelain::remote_ftps(args),
        "remote-http" => porcelain::remote_http(args),
        "remote-https" => porcelain::remote_https(args),
        "repack" => porcelain::repack(args),
        "replace" => porcelain::replace(args),
        "replay" => porcelain::replay(args),
        "repo" => porcelain::repo(args),
        "request-pull" => porcelain::request_pull(args),
        "rerere" => porcelain::rerere(args),
        "reset" => porcelain::reset(args),
        "restore" => porcelain::restore(args),
        "rev-list" => porcelain::rev_list(args),
        "rev-parse" => porcelain::rev_parse(args),
        "revert" => porcelain::revert(args),
        "rm" => porcelain::rm(args),
        "send-email" => porcelain::send_email(args),
        "send-pack" => porcelain::send_pack(args),
        "sh-i18n--envsubst" => porcelain::sh_i18n__envsubst(args),
        "shell" => porcelain::shell(args),
        "shortlog" => porcelain::shortlog(args),
        "show" => porcelain::show(args),
        "show-branch" => porcelain::show_branch(args),
        "show-index" => porcelain::show_index(args),
        "show-ref" => porcelain::show_ref(args),
        "sparse-checkout" => porcelain::sparse_checkout(args),
        "stage" => porcelain::stage(args),
        "stash" => porcelain::stash(args),
        "status" => porcelain::status(args),
        "stripspace" => porcelain::stripspace(args),
        "submodule" => porcelain::submodule(args),
        "submodule--helper" => porcelain::submodule__helper(args),
        "subtree" => porcelain::subtree(args),
        "switch" => porcelain::switch(args),
        "symbolic-ref" => porcelain::symbolic_ref(args),
        "tag" => porcelain::tag(args),
        "unpack-file" => porcelain::unpack_file(args),
        "unpack-objects" => porcelain::unpack_objects(args),
        "update-index" => porcelain::update_index(args),
        "update-ref" => porcelain::update_ref(args),
        "update-server-info" => porcelain::update_server_info(args),
        "upload-archive" => porcelain::upload_archive(args),
        "upload-archive--writer" => porcelain::upload_archive__writer(args),
        "upload-pack" => porcelain::upload_pack(args),
        "url-parse" => porcelain::url_parse(args),
        "var" => porcelain::var(args),
        "verify-commit" => porcelain::verify_commit(args),
        "verify-pack" => porcelain::verify_pack(args),
        "verify-tag" => porcelain::verify_tag(args),
        "version" => porcelain::version(args),
        "web--browse" => porcelain::web__browse(args),
        "whatchanged" => porcelain::whatchanged(args),
        "worktree" => porcelain::worktree(args),
        "write-tree" => porcelain::write_tree(args),
        // ---- END generated porcelain arms ----

        // Not yet ported. No fallthrough to stock git — this is a from-scratch engine.
        _ => anyhow::bail!("not yet ported (superset verbs: {})", SUPERSET_VERBS.join(", ")),
    }
}
