//! Subcommand routing for the shadow `git` binary.
//!
//! Two namespaces share one dispatch table:
//!   * **superset** verbs (`z*`) — the novel coordination layer, [`superset`].
//!   * **git-compat** porcelain — stock git subcommands served via gitoxide,
//!     ported incrementally, [`porcelain`].

use crate::{porcelain, superset};
use anyhow::Result;
use std::process::ExitCode;

/// zvcs-native extension verbs — the superset that stock git does not have.
pub const SUPERSET_VERBS: &[&str] = &[
    "zsync", "zbump", "zdaemon", "zrepos", "zreindex", "zjobs", "zjob", "zcommit", "zpush",
    "zrepl", "zclaim", "zunclaim", "zwho", "zstatus", "zlog", "zundo", "zsnapshot", "zrestore",
    "zsnapshots", "zworktree", "zstash", "zunstash", "zstashes", "zup", "zforeach", "zhook",
    "ztrigger", "zwatch", "zdashed", "zverbs", "zcd", "zpwd", "zls", "zenv", "zunset", "zecho",
    "zdoctor", "zmkdir", "ztouch", "zrm", "zcp", "zmv", "zcat", "zln",
    "zheads", "zdirty", "zbranches", "ztags", "zremotes", "zsize", "zage", "zpull",
    "zgrep", "zahead", "zbehind", "zauthors", "zhot", "zconflicts",
    "zfetch", "zgc", "zfsck", "zprune", "zcheckout", "ztagall", "zcommitall", "zpushall", "zclean",
    "zwait", "zqueue", "zbarrier",
    "zstale", "zlast", "zbig", "zfiles", "zdivergent", "zorphans", "zsessions", "zidle", "zdashboard",
];

/// Every git-compat porcelain verb this dispatch table serves, generated from
/// the porcelain module set alongside the match arms below (scripts/wire_dispatch.pl)
/// so the two can never drift. Consumed by [`is_verb`].
pub const PORCELAIN_VERBS: &[&str] = &[
    // ---- BEGIN generated porcelain verbs (scripts/wire_dispatch.pl) ----
    "add",
    "am",
    "annotate",
    "apply",
    "archimport",
    "archive",
    "backfill",
    "bisect",
    "blame",
    "branch",
    "bugreport",
    "bundle",
    "cat-file",
    "check-attr",
    "check-ignore",
    "check-mailmap",
    "check-ref-format",
    "checkout",
    "checkout--worker",
    "checkout-index",
    "cherry",
    "cherry-pick",
    "clean",
    "clone",
    "column",
    "commit",
    "commit-graph",
    "commit-tree",
    "config",
    "count-objects",
    "credential",
    "credential-cache",
    "credential-cache--daemon",
    "credential-netrc",
    "credential-osxkeychain",
    "credential-store",
    "cvsexportcommit",
    "cvsimport",
    "cvsserver",
    "daemon",
    "describe",
    "diagnose",
    "diff",
    "diff-files",
    "diff-index",
    "diff-pairs",
    "diff-tree",
    "difftool",
    "difftool--helper",
    "fast-export",
    "fast-import",
    "fetch",
    "fetch-pack",
    "filter-branch",
    "fmt-merge-msg",
    "for-each-ref",
    "for-each-repo",
    "format-patch",
    "format-rev",
    "fsck",
    "fsck-objects",
    "fsmonitor--daemon",
    "gc",
    "get-tar-commit-id",
    "grep",
    "hash-object",
    "help",
    "history",
    "hook",
    "http-backend",
    "http-fetch",
    "http-push",
    "imap-send",
    "index-pack",
    "init",
    "init-db",
    "instaweb",
    "interpret-trailers",
    "jump",
    "last-modified",
    "log",
    "ls-files",
    "ls-remote",
    "ls-tree",
    "mailinfo",
    "mailsplit",
    "maintenance",
    "merge",
    "merge-base",
    "merge-file",
    "merge-index",
    "merge-octopus",
    "merge-one-file",
    "merge-ours",
    "merge-recursive",
    "merge-recursive-ours",
    "merge-recursive-theirs",
    "merge-resolve",
    "merge-subtree",
    "merge-tree",
    "mergetool",
    "mktag",
    "mktree",
    "multi-pack-index",
    "mv",
    "name-rev",
    "notes",
    "p4",
    "pack-objects",
    "pack-redundant",
    "pack-refs",
    "patch-id",
    "pickaxe",
    "prune",
    "prune-packed",
    "pull",
    "push",
    "quiltimport",
    "range-diff",
    "read-tree",
    "rebase",
    "receive-pack",
    "reflog",
    "refs",
    "remote",
    "remote-ext",
    "remote-fd",
    "remote-ftp",
    "remote-ftps",
    "remote-http",
    "remote-https",
    "repack",
    "replace",
    "replay",
    "repo",
    "request-pull",
    "rerere",
    "reset",
    "restore",
    "rev-list",
    "rev-parse",
    "revert",
    "rm",
    "send-email",
    "send-pack",
    "sh-i18n--envsubst",
    "shell",
    "shortlog",
    "show",
    "show-branch",
    "show-index",
    "show-ref",
    "sparse-checkout",
    "stage",
    "stash",
    "status",
    "stripspace",
    "submodule",
    "submodule--helper",
    "subtree",
    "switch",
    "symbolic-ref",
    "tag",
    "unpack-file",
    "unpack-objects",
    "update-index",
    "update-ref",
    "update-server-info",
    "upload-archive",
    "upload-archive--writer",
    "upload-pack",
    "url-parse",
    "var",
    "verify-commit",
    "verify-pack",
    "verify-tag",
    "version",
    "web--browse",
    "whatchanged",
    "worktree",
    "write-tree",
    // ---- END generated porcelain verbs ----
];

/// Whether `sub` names a verb [`run`] dispatches — a superset verb or a ported
/// porcelain command. Alias expansion uses this to stop at a real command
/// (builtins win over an `alias.<cmd>` of the same name, exactly as git does)
/// rather than mistaking it for an alias.
pub fn is_verb(sub: &str) -> bool {
    SUPERSET_VERBS.contains(&sub) || PORCELAIN_VERBS.contains(&sub)
}

/// One-line usage for each z-verb, printed on `-h`/`--help`. `None` for anything
/// that is not a z-verb, so the dispatcher leaves other commands' `-h` alone.
fn z_usage(sub: &str) -> Option<&'static str> {
    Some(match sub {
        "zsync" => "usage: git zsync — fetch and fast-forward every submodule to origin/main",
        "zbump" => "usage: git zbump [<submodule-path>...] — forward-only submodule gitlink bumps",
        "zdaemon" => "usage: git zdaemon <start|stop|restart|status|info|ping|log>",
        "zrepos" => "usage: git zrepos [<pattern>...] — list indexed repos; patterns filter by case-insensitive substring",
        "zreindex" => "usage: git zreindex [--sync|--async] [<path>...] — (re)crawl for git repos and refresh the index",
        "zdashed" => "usage: git zdashed [<dir>] — install a git-<verb> symlink for every builtin",
        "zjobs" => "usage: git zjobs [-n <count>] — list recent ledger jobs (newest first)",
        "zjob" => "usage: git zjob <id> | git zjob <stop|restart> <id> — show or control a job",
        "zcommit" => "usage: git zcommit [<path>...] -m <msg> [--push] — queue an atomic staged-commit job",
        "zpush" => "usage: git zpush [<refspec>] — queue an async push job with a network-free ff pre-flight",
        "zrepl" => "usage: git zrepl — interactive console over every zvcs command (z-verbs + git porcelain)",
        "zclaim" => "usage: git zclaim [<path>] — lease a repo for this session",
        "zunclaim" => "usage: git zunclaim [--force] [<path>] — release a lease on a repo",
        "zwho" => "usage: git zwho — list active claims (who is working what)",
        "zstatus" => "usage: git zstatus [--all] — cached working-tree status of indexed repos",
        "zlog" => "usage: git zlog [-n <count>] — machine-wide reflog timeline across all indexed repos",
        "zundo" => "usage: git zundo [<path>] — rewind a repo one reflog step (reset --hard to previous HEAD)",
        "zsnapshot" => "usage: git zsnapshot <name> — record the tree's HEADs as a restore point",
        "zrestore" => "usage: git zrestore <name> — reset the whole tree back to a snapshot",
        "zsnapshots" => "usage: git zsnapshots — list snapshot names and their repo counts",
        "zworktree" => "usage: git zworktree <add <name>|list|remove <name>> — tree-wide private worktrees",
        "zstash" => "usage: git zstash [<name>] — stash every dirty repo in the tree under <name>",
        "zunstash" => "usage: git zunstash [<name>] — pop the tree-wide stash back (LIFO)",
        "zstashes" => "usage: git zstashes — list tree-wide stashes and their repo counts",
        "zup" => "usage: git zup [<path>] — reconcile the tree at cwd (or <path>) to latest",
        "zforeach" => "usage: git zforeach [<pattern>...|--repo <p>|--dirty|--ahead|--behind|--claimed|--session <s>] -- <command>...",
        "zhook" => "usage: git zhook <set <command>|unset|show|list|test>",
        "ztrigger" => "usage: git ztrigger <DIR> <command>... [--throttle <dur>] | git ztrigger <list|rm DIR|test DIR|tail|top> — run a command on any file change in DIR (leading-edge throttle, default 500ms; tail/top show fires live)",
        "zwatch" => "usage: git zwatch <DIR> | git zwatch <list|rm DIR> — watch DIR (index + cached status) without a command",
        "zverbs" => "usage: git zverbs — list every zvcs extension verb and its usage",
        "zcd" => "usage: git zcd [<dir>|-] — change the working directory (for the zrepl console)",
        "zpwd" => "usage: git zpwd — print the working directory",
        "zls" => "usage: git zls [-alrt] [<path>] — git-aware directory listing (per-file status like eza --git)",
        "zenv" => "usage: git zenv [<NAME=VALUE>...|<NAME>...] — print, set, or query environment variables",
        "zunset" => "usage: git zunset <NAME>... — remove environment variables",
        "zecho" => "usage: git zecho [-n] [<arg>...] — print arguments joined by a space",
        "zdoctor" => "usage: git zdoctor — health check of the zvcs environment (shadow, daemon, ledger, man pages)",
        "zmkdir" => "usage: git zmkdir [-p] <dir>... — create directories",
        "ztouch" => "usage: git ztouch <file>... — create files or bump their mtime",
        "zrm" => "usage: git zrm [-r] [-f] <path>... — remove files/directories (filesystem, not git rm)",
        "zcp" => "usage: git zcp [-r] <src>... <dst> — copy files/directories",
        "zmv" => "usage: git zmv <src>... <dst> — move/rename files/directories",
        "zcat" => "usage: git zcat <file>... — print file contents to stdout",
        "zln" => "usage: git zln [-s] <target> <link> — create a hard link or symlink (-s)",
        "zheads" => "usage: git zheads [selectors] — HEAD branch/id (+dirty) of each indexed repo, in parallel",
        "zdirty" => "usage: git zdirty [selectors] — list indexed repos with uncommitted tracked changes, in parallel",
        "zbranches" => "usage: git zbranches [selectors] — local branches of each indexed repo, in parallel",
        "ztags" => "usage: git ztags [selectors] — tag count of each indexed repo, in parallel",
        "zremotes" => "usage: git zremotes [selectors] — remotes and fetch URLs of each indexed repo",
        "zsize" => "usage: git zsize [selectors] — on-disk .git size of each indexed repo (largest first)",
        "zage" => "usage: git zage [selectors] — how long ago each indexed repo's HEAD commit was made",
        "zpull" => "usage: git zpull [selectors] — parallel fetch + fast-forward of every indexed repo (ff-only)",
        "zgrep" => "usage: git zgrep [selectors] [-i] <pattern> — parallel regex search of tracked content across indexed repos",
        "zahead" => "usage: git zahead [selectors] — indexed repos with commits not yet on their upstream",
        "zbehind" => "usage: git zbehind [selectors] — indexed repos whose upstream is ahead of them",
        "zauthors" => "usage: git zauthors [selectors] — commit counts by author across indexed repos, ranked",
        "zhot" => "usage: git zhot [selectors] [<days>] — indexed repos ranked by commits in the last <days> (default 30)",
        "zconflicts" => "usage: git zconflicts [selectors] — indexed repos mid-merge/rebase/cherry-pick/revert/bisect or with conflicts",
        "zfetch" => "usage: git zfetch [selectors] — parallel git fetch across every indexed repo",
        "zgc" => "usage: git zgc [selectors] — parallel git gc across every indexed repo",
        "zfsck" => "usage: git zfsck [selectors] — parallel git fsck across every indexed repo",
        "zprune" => "usage: git zprune [selectors] — parallel git prune across every indexed repo",
        "zcheckout" => "usage: git zcheckout [selectors] <branch> — check out <branch> in every indexed repo that has it",
        "ztagall" => "usage: git ztagall [selectors] <tag> — create <tag> at HEAD in every indexed repo",
        "zcommitall" => "usage: git zcommitall [selectors] -m <msg> — commit tracked changes (commit -a) in every dirty repo",
        "zpushall" => "usage: git zpushall [selectors] — push every indexed repo that is ahead of its upstream",
        "zclean" => "usage: git zclean -f [selectors] — remove untracked files (git clean -fd) in every indexed repo (-f required)",
        "zwait" => "usage: git zwait [<path>] — block until the repo's async jobs drain",
        "zqueue" => "usage: git zqueue — list queued/running async jobs",
        "zbarrier" => "usage: git zbarrier — block until the whole async job queue is idle",
        "zstale" => "usage: git zstale [selectors] [<days>] — indexed repos whose HEAD is older than <days> (default 90)",
        "zlast" => "usage: git zlast [selectors] — indexed repos ordered by HEAD commit time, newest first",
        "zbig" => "usage: git zbig [selectors] [<n>] — largest tracked files across indexed repos (top <n>, default 20)",
        "zfiles" => "usage: git zfiles [selectors] — tracked file count of each indexed repo (largest first)",
        "zdivergent" => "usage: git zdivergent [selectors] — indexed repos both ahead of and behind their upstream",
        "zorphans" => "usage: git zorphans [selectors] — indexed repos with no remote configured",
        "zsessions" => "usage: git zsessions — active sessions ranked by repos held",
        "zidle" => "usage: git zidle [selectors] — indexed repos with no active claim (free to pick up)",
        "zdashboard" => "usage: git zdashboard — instant one-screen health summary from the status cache + ledger",
        _ => return None,
    })
}

/// `git zverbs` — print every superset (`z*`) verb with its one-line usage. The
/// text is [`z_usage`] itself, minus the `usage: git ` lead-in, so the listing is
/// the same source of truth each verb's own `-h` prints and can never drift.
fn print_verbs() -> Result<ExitCode> {
    for verb in SUPERSET_VERBS {
        if let Some(usage) = z_usage(verb) {
            println!("{}", usage.strip_prefix("usage: git ").unwrap_or(usage));
        }
    }
    Ok(ExitCode::SUCCESS)
}

pub fn run(sub: &str, args: &[String]) -> Result<ExitCode> {
    // Every z-verb answers `-h`/`--help` with a one-line usage, uniformly and
    // before dispatch. `z_usage` returns `None` for anything that is not a known
    // z-verb, so this never intercepts a porcelain command's own `-h`.
    if sub.starts_with('z') && args.iter().any(|a| a == "-h" || a == "--help") {
        if let Some(usage) = z_usage(sub) {
            println!("{usage}");
            return Ok(ExitCode::SUCCESS);
        }
    }
    match sub {
        // ---- superset (novel) ----
        "zsync" => superset::zsync(args),
        "zbump" => superset::zbump(args),
        "zdaemon" => superset::zdaemon(args),
        "zrepos" => superset::zrepos(args),
        "zreindex" => superset::zreindex(args),
        "zdashed" => superset::zdashed(args),
        "zjobs" => superset::zjobs(args),
        "zjob" => superset::zjob(args),
        "zcommit" => superset::zcommit(args),
        "zpush" => superset::zpush(args),
        "zrepl" => superset::zrepl(args),
        "zclaim" => superset::zclaim(args),
        "zunclaim" => superset::zunclaim(args),
        "zwho" => superset::zwho(args),
        "zstatus" => superset::zstatus(args),
        "zlog" => superset::zlog(args),
        "zundo" => superset::zundo(args),
        "zsnapshot" => superset::zsnapshot(args),
        "zrestore" => superset::zrestore(args),
        "zsnapshots" => superset::zsnapshots(args),
        "zworktree" => superset::zworktree(args),
        "zstash" => superset::zstash(args),
        "zunstash" => superset::zunstash(args),
        "zstashes" => superset::zstashes(args),
        "zup" => superset::zup(args),
        "zforeach" => superset::zforeach(args),
        "zhook" => superset::zhook(args),
        "ztrigger" => superset::ztrigger(args),
        "zwatch" => superset::zwatch(args),
        "zverbs" => print_verbs(),
        "zcd" => superset::zcd(args),
        "zpwd" => superset::zpwd(args),
        "zls" => superset::zls(args),
        "zenv" => superset::zenv(args),
        "zunset" => superset::zunset(args),
        "zecho" => superset::zecho(args),
        "zdoctor" => superset::zdoctor(args),
        "zmkdir" => superset::zmkdir(args),
        "ztouch" => superset::ztouch(args),
        "zrm" => superset::zrm(args),
        "zcp" => superset::zcp(args),
        "zmv" => superset::zmv(args),
        "zcat" => superset::zcat(args),
        "zln" => superset::zln(args),
        "zheads" => superset::zheads(args),
        "zdirty" => superset::zdirty(args),
        "zbranches" => superset::zbranches(args),
        "ztags" => superset::ztags(args),
        "zremotes" => superset::zremotes(args),
        "zsize" => superset::zsize(args),
        "zage" => superset::zage(args),
        "zpull" => superset::zpull(args),
        "zgrep" => superset::zgrep(args),
        "zahead" => superset::zahead(args),
        "zbehind" => superset::zbehind(args),
        "zauthors" => superset::zauthors(args),
        "zhot" => superset::zhot(args),
        "zconflicts" => superset::zconflicts(args),
        "zfetch" => superset::zfetch(args),
        "zgc" => superset::zgc(args),
        "zfsck" => superset::zfsck(args),
        "zprune" => superset::zprune(args),
        "zcheckout" => superset::zcheckout(args),
        "ztagall" => superset::ztagall(args),
        "zcommitall" => superset::zcommitall(args),
        "zpushall" => superset::zpushall(args),
        "zclean" => superset::zclean(args),
        "zwait" => superset::zwait(args),
        "zqueue" => superset::zqueue(args),
        "zbarrier" => superset::zbarrier(args),
        "zstale" => superset::zstale(args),
        "zlast" => superset::zlast(args),
        "zbig" => superset::zbig(args),
        "zfiles" => superset::zfiles(args),
        "zdivergent" => superset::zdivergent(args),
        "zorphans" => superset::zorphans(args),
        "zsessions" => superset::zsessions(args),
        "zidle" => superset::zidle(args),
        "zdashboard" => superset::zdashboard(args),

        // ---- BEGIN generated porcelain arms (scripts/wire_dispatch.pl) ----
        "add" => porcelain::add(args),
        "am" => porcelain::am(args),
        "annotate" => porcelain::annotate(args),
        "apply" => porcelain::apply(args),
        "archimport" => porcelain::archimport(args),
        "archive" => porcelain::archive(args),
        "backfill" => porcelain::backfill(args),
        "bisect" => porcelain::bisect(args),
        "blame" => porcelain::blame(args),
        "branch" => porcelain::branch(args),
        "bugreport" => porcelain::bugreport(args),
        "bundle" => porcelain::bundle(args),
        "cat-file" => porcelain::cat_file(args),
        "check-attr" => porcelain::check_attr(args),
        "check-ignore" => porcelain::check_ignore(args),
        "check-mailmap" => porcelain::check_mailmap(args),
        "check-ref-format" => porcelain::check_ref_format(args),
        "checkout" => porcelain::checkout(args),
        "checkout--worker" => porcelain::checkout__worker(args),
        "checkout-index" => porcelain::checkout_index(args),
        "cherry" => porcelain::cherry(args),
        "cherry-pick" => porcelain::cherry_pick(args),
        "clean" => porcelain::clean(args),
        "clone" => porcelain::clone(args),
        "column" => porcelain::column(args),
        "commit" => porcelain::commit(args),
        "commit-graph" => porcelain::commit_graph(args),
        "commit-tree" => porcelain::commit_tree(args),
        "config" => porcelain::config(args),
        "count-objects" => porcelain::count_objects(args),
        "credential" => porcelain::credential(args),
        "credential-cache" => porcelain::credential_cache(args),
        "credential-cache--daemon" => porcelain::credential_cache__daemon(args),
        "credential-netrc" => porcelain::credential_netrc(args),
        "credential-osxkeychain" => porcelain::credential_osxkeychain(args),
        "credential-store" => porcelain::credential_store(args),
        "cvsexportcommit" => porcelain::cvsexportcommit(args),
        "cvsimport" => porcelain::cvsimport(args),
        "cvsserver" => porcelain::cvsserver(args),
        "daemon" => porcelain::daemon(args),
        "describe" => porcelain::describe(args),
        "diagnose" => porcelain::diagnose(args),
        "diff" => porcelain::diff(args),
        "diff-files" => porcelain::diff_files(args),
        "diff-index" => porcelain::diff_index(args),
        "diff-pairs" => porcelain::diff_pairs(args),
        "diff-tree" => porcelain::diff_tree(args),
        "difftool" => porcelain::difftool(args),
        "difftool--helper" => porcelain::difftool__helper(args),
        "fast-export" => porcelain::fast_export(args),
        "fast-import" => porcelain::fast_import(args),
        "fetch" => porcelain::fetch(args),
        "fetch-pack" => porcelain::fetch_pack(args),
        "filter-branch" => porcelain::filter_branch(args),
        "fmt-merge-msg" => porcelain::fmt_merge_msg(args),
        "for-each-ref" => porcelain::for_each_ref(args),
        "for-each-repo" => porcelain::for_each_repo(args),
        "format-patch" => porcelain::format_patch(args),
        "format-rev" => porcelain::format_rev(args),
        "fsck" => porcelain::fsck(args),
        "fsck-objects" => porcelain::fsck_objects(args),
        "fsmonitor--daemon" => porcelain::fsmonitor__daemon(args),
        "gc" => porcelain::gc(args),
        "get-tar-commit-id" => porcelain::get_tar_commit_id(args),
        "grep" => porcelain::grep(args),
        "hash-object" => porcelain::hash_object(args),
        "help" => porcelain::help(args),
        "history" => porcelain::history(args),
        "hook" => porcelain::hook(args),
        "http-backend" => porcelain::http_backend(args),
        "http-fetch" => porcelain::http_fetch(args),
        "http-push" => porcelain::http_push(args),
        "imap-send" => porcelain::imap_send(args),
        "index-pack" => porcelain::index_pack(args),
        "init" => porcelain::init(args),
        "init-db" => porcelain::init_db(args),
        "instaweb" => porcelain::instaweb(args),
        "interpret-trailers" => porcelain::interpret_trailers(args),
        "jump" => porcelain::jump(args),
        "last-modified" => porcelain::last_modified(args),
        "log" => porcelain::log(args),
        "ls-files" => porcelain::ls_files(args),
        "ls-remote" => porcelain::ls_remote(args),
        "ls-tree" => porcelain::ls_tree(args),
        "mailinfo" => porcelain::mailinfo(args),
        "mailsplit" => porcelain::mailsplit(args),
        "maintenance" => porcelain::maintenance(args),
        "merge" => porcelain::merge(args),
        "merge-base" => porcelain::merge_base(args),
        "merge-file" => porcelain::merge_file(args),
        "merge-index" => porcelain::merge_index(args),
        "merge-octopus" => porcelain::merge_octopus(args),
        "merge-one-file" => porcelain::merge_one_file(args),
        "merge-ours" => porcelain::merge_ours(args),
        "merge-recursive" => porcelain::merge_recursive(args),
        "merge-recursive-ours" => porcelain::merge_recursive_ours(args),
        "merge-recursive-theirs" => porcelain::merge_recursive_theirs(args),
        "merge-resolve" => porcelain::merge_resolve(args),
        "merge-subtree" => porcelain::merge_subtree(args),
        "merge-tree" => porcelain::merge_tree(args),
        "mergetool" => porcelain::mergetool(args),
        "mktag" => porcelain::mktag(args),
        "mktree" => porcelain::mktree(args),
        "multi-pack-index" => porcelain::multi_pack_index(args),
        "mv" => porcelain::mv(args),
        "name-rev" => porcelain::name_rev(args),
        "notes" => porcelain::notes(args),
        "p4" => porcelain::p4(args),
        "pack-objects" => porcelain::pack_objects(args),
        "pack-redundant" => porcelain::pack_redundant(args),
        "pack-refs" => porcelain::pack_refs(args),
        "patch-id" => porcelain::patch_id(args),
        "pickaxe" => porcelain::pickaxe(args),
        "prune" => porcelain::prune(args),
        "prune-packed" => porcelain::prune_packed(args),
        "pull" => porcelain::pull(args),
        "push" => porcelain::push(args),
        "quiltimport" => porcelain::quiltimport(args),
        "range-diff" => porcelain::range_diff(args),
        "read-tree" => porcelain::read_tree(args),
        "rebase" => porcelain::rebase(args),
        "receive-pack" => porcelain::receive_pack(args),
        "reflog" => porcelain::reflog(args),
        "refs" => porcelain::refs(args),
        "remote" => porcelain::remote(args),
        "remote-ext" => porcelain::remote_ext(args),
        "remote-fd" => porcelain::remote_fd(args),
        "remote-ftp" => porcelain::remote_ftp(args),
        "remote-ftps" => porcelain::remote_ftps(args),
        "remote-http" => porcelain::remote_http(args),
        "remote-https" => porcelain::remote_https(args),
        "repack" => porcelain::repack(args),
        "replace" => porcelain::replace(args),
        "replay" => porcelain::replay(args),
        "repo" => porcelain::repo(args),
        "request-pull" => porcelain::request_pull(args),
        "rerere" => porcelain::rerere(args),
        "reset" => porcelain::reset(args),
        "restore" => porcelain::restore(args),
        "rev-list" => porcelain::rev_list(args),
        "rev-parse" => porcelain::rev_parse(args),
        "revert" => porcelain::revert(args),
        "rm" => porcelain::rm(args),
        "send-email" => porcelain::send_email(args),
        "send-pack" => porcelain::send_pack(args),
        "sh-i18n--envsubst" => porcelain::sh_i18n__envsubst(args),
        "shell" => porcelain::shell(args),
        "shortlog" => porcelain::shortlog(args),
        "show" => porcelain::show(args),
        "show-branch" => porcelain::show_branch(args),
        "show-index" => porcelain::show_index(args),
        "show-ref" => porcelain::show_ref(args),
        "sparse-checkout" => porcelain::sparse_checkout(args),
        "stage" => porcelain::stage(args),
        "stash" => porcelain::stash(args),
        "status" => porcelain::status(args),
        "stripspace" => porcelain::stripspace(args),
        "submodule" => porcelain::submodule(args),
        "submodule--helper" => porcelain::submodule__helper(args),
        "subtree" => porcelain::subtree(args),
        "switch" => porcelain::switch(args),
        "symbolic-ref" => porcelain::symbolic_ref(args),
        "tag" => porcelain::tag(args),
        "unpack-file" => porcelain::unpack_file(args),
        "unpack-objects" => porcelain::unpack_objects(args),
        "update-index" => porcelain::update_index(args),
        "update-ref" => porcelain::update_ref(args),
        "update-server-info" => porcelain::update_server_info(args),
        "upload-archive" => porcelain::upload_archive(args),
        "upload-archive--writer" => porcelain::upload_archive__writer(args),
        "upload-pack" => porcelain::upload_pack(args),
        "url-parse" => porcelain::url_parse(args),
        "var" => porcelain::var(args),
        "verify-commit" => porcelain::verify_commit(args),
        "verify-pack" => porcelain::verify_pack(args),
        "verify-tag" => porcelain::verify_tag(args),
        "version" => porcelain::version(args),
        "web--browse" => porcelain::web__browse(args),
        "whatchanged" => porcelain::whatchanged(args),
        "worktree" => porcelain::worktree(args),
        "write-tree" => porcelain::write_tree(args),
        // ---- END generated porcelain arms ----

        // An unrecognized verb: a typo or a name this engine has no command for.
        // The CLI never reaches here (it routes unknowns through the external
        // `git-<verb>` / autocorrect path in lib.rs); direct callers like `zrepl`
        // do, so give git's own honest wording rather than implying the verb is a
        // real command merely awaiting a port.
        _ => anyhow::bail!("is not a git command. See 'git --help'."),
    }
}
