//! The pack protocol itself: the four wire verbs as *servers*, the bytes they
//! read and write, and the version negotiation that decides which dialect they
//! speak.
//!
//! Every other transport module in the corpus measures a **client**. This one
//! measures the wire: `upload-pack` and `receive-pack` driven by a pkt-line
//! request written into the case as a byte literal, `git daemon` serving one
//! request over stdin, and the `GIT_PROTOCOL` handshake that selects v0, v1 or
//! v2 before either end has said anything else.
//!
//! # How this divides territory with the five adjacent modules
//!
//! * **`fetch_clone.rs`** owns `fetch`, `clone`, `bundle`, `ls-remote` and the
//!   *option surface* of the four pack verbs against `Shape::BehindRemote`'s
//!   peer. Its `upload_pack`, `send_pack`, `receive_pack` and `fetch_pack`
//!   groups run every one of them with **stdin closed**, so what they measure is
//!   the advertisement a server prints before it reads anything and the report a
//!   client prints after. It never writes a request. Its `protocol.version`
//!   cases are three `fetch origin main:refs/heads/x` invocations and one
//!   `-c protocol.version=2` apiece on `upload-pack`, `send-pack` and
//!   `fetch-pack`; that is the whole of the version axis in the corpus, and it
//!   is entirely *client-side config*. This module owns the other half — the
//!   `GIT_PROTOCOL` variable, which is how the version is actually negotiated,
//!   and which no case in the corpus set before.
//! * **`transport_local.rs`** owns the self-referential spelling of the same
//!   verbs (`fetch .`, `push .`, `upload-archive`) on the shapes with no peer.
//!   Its header records that both ends of every one of its cases is the *same*
//!   binary running as a client; nothing there drives a server directly.
//! * **`branch_remote.rs`** owns `push` and the remote-tracking bookkeeping
//!   underneath it, including `--receive-pack=git-receive-pack`.
//! * **`refspec_algebra.rs`** owns the refspec **grammar** — which name matches
//!   which, and where it lands. The two cases here that carry a refspec
//!   (`send-pack --all`, `send-pack --mirror`) are not about matching: `--all`
//!   and `--mirror` name a *ref set* rather than a pattern, and what they
//!   measure is which set the verb chose and whether it forced.
//! * **`interchange.rs`** owns bundles — the offline spelling of the same object
//!   transfer, with no protocol at all.
//!
//! # Why a request has to be a literal, and how the lengths were checked
//!
//! A server is only measurable if something speaks to it, and the harness's one
//! channel into a case is `Case::stdin`, which is `&'static [u8]`. So every
//! request below is a pkt-line stream written out by hand: a four-hex length
//! that *includes its own four bytes*, then the payload; `0000` is a flush and
//! `0001` a delimiter. Each was generated by a length-computing script, written
//! to a file, and replayed against stock 2.55.0 before being transcribed here —
//! a length that is one byte wrong does not fail loudly, it makes the server
//! read a truncated command and answer a question nobody asked, on both sides,
//! identically.
//!
//! The object ids inside them are the peer's, and they are fixed facts of
//! [`Shape::BehindRemote`]: `refs/heads/main` is
//! `91bfcd8dad4adbba6d1110e504c5bd1929984f2c` and `refs/heads/div` is
//! `79f764eb810204174b975d237db6fd14984a72bd` — the same two ids
//! `refspec_algebra.rs`'s header quotes, verified again here by rebuilding the
//! shape from `fixture.rs`'s recipe with stock 2.55.0.
//!
//! # What is NOT measurable here, established by measurement rather than by
//! taste
//!
//! * **A crossed client/server pair.** The highest-value question in this
//!   territory — stock's client talking to the port's server — is not
//!   expressible in this harness, and no case below pretends otherwise. A `Case`
//!   is one argv run twice, once per binary, and the *server* a transport spawns
//!   is chosen by the client: measured with a `git-upload-pack` shim on `PATH`,
//!   stock's `fetch-pack` resolves the helper through its own `GIT_EXEC_PATH`
//!   and never sees the shim, while the port's resolves it through `PATH` and
//!   hits it twice. So on **both** sides of every `fetch-pack ./.remote.git`
//!   case in the corpus the far end is stock's `git-upload-pack`, and the only
//!   way to change that is `--upload-pack=<path>`, which would have to name an
//!   absolute path — the same path on both sides, which crosses nothing. The
//!   substitute this module ships instead is to drive the port's server half
//!   *directly* with the bytes a stock client would have sent, and compare the
//!   bytes it answers with. That is the same wire, minus the second process.
//! * **`git daemon` as a listener.** A port, a pid and an accept loop; none of
//!   the three is comparable. `--inetd` is the same server reading one request
//!   from stdin and is fully deterministic — verified, twice per side, with no
//!   timestamp, pid or socket path anywhere in its output — so that is the
//!   spelling [`daemon_inetd`] uses and the listening mode appears nowhere.
//! * **`receive.certNonceSeed`.** It puts `push-cert=<unix timestamp>-<hmac>` in
//!   the advertisement. `fetch_clone.rs` excluded it for that reason and it is
//!   excluded here for the same one.
//! * **A v0 `want`/`done` that transfers a real pack.** Measured and rejected:
//!   `upload-pack --stateless-rpc ./.remote.git` fed a bare `want`+`done` gives
//!   stock three different SHA-1s over three runs, because the pack it builds is
//!   not byte-stable. The two pack-bearing requests that *are* here
//!   ([`V0_WANT_HAVE_DONE`] and [`V2_FETCH_WANT_HAVE`]) both carry a `have` for
//!   the object they `want`, so the pack is empty and its bytes are a constant —
//!   verified eight times and five times respectively against stock, identical
//!   every run, and twice more against the port.
//! * **`send-pack --force-with-lease=<ref>` against the peer.** Stock 2.55.0
//!   **crashes** on it here: exit 139, `fatal: the remote end hung up
//!   unexpectedly`, reproducible. A case pinned on a stock segfault measures the
//!   oracle, not the port, so it is recorded here and not shipped.
//! * **`--timeout=<n>`.** Real seconds. `fetch_clone.rs` already carries the one
//!   spelling that returns without waiting (`--timeout=1 --advertise-refs`);
//!   nothing here adds another.
//!
//! # Determinism of what *is* here
//!
//! Every case below was run twice against stock in a hand-built copy of its
//! shape and twice against the port, and the four answers compared on stdout,
//! stderr, exit code and repository state. The one candidate that failed that
//! gate is the bare `want`/`done` named above, and it was dropped rather than
//! weakened. `--shallow-since` appears only with a literal ISO date on either
//! side of the fixtures' pinned commit clock (`env::harden` fixes every commit
//! at `1700000000`), never with an approxidate that reads the wall clock.

use crate::fixture::Shape;
use crate::runner::{Case, ConfigEntry, ConfigScope};

/// [`Case::strict`] with a stdin payload: the two constructors do not compose,
/// and half this module needs both.
fn strict_stdin(
    cmd: &'static str,
    args: &[&str],
    shape: Shape,
    stdin: &'static [u8],
) -> Case {
    let mut case = Case::with_stdin(cmd, args, shape, stdin);
    case.compare_stderr = true;
    case
}

/// Append this subsystem's cases to the corpus.
pub fn cases(out: &mut Vec<Case>) {
    protocol_version_selection(out);
    server_version_line(out);
    upload_pack_v2_capabilities(out);
    upload_pack_v2_commands(out);
    upload_pack_v0_requests(out);
    upload_pack_hidden_refs(out);
    receive_pack_reports(out);
    receive_pack_advertisement(out);
    fetch_pack_shallow_wire(out);
    fetch_pack_diag_url(out);
    send_pack_ref_selection(out);
    send_pack_wire_modes(out);
    ls_remote_protocol(out);
    daemon_inetd(out);
}

// ---------------------------------------------------------------------------
// pkt-line request literals
// ---------------------------------------------------------------------------

/// v2 `ls-refs` asking for both decorations. Answers `HEAD` with
/// `symref-target:` and every ref with its peeled id where it has one.
const V2_LS_REFS: &[u8] =
    b"0014command=ls-refs\n0017object-format=sha1\n00010009peel\n000csymrefs\n0000";

/// v2 `ls-refs` narrowed to `refs/heads/`, which is the argument every real v2
/// client sends and the one a server that ignores prefixes answers too widely.
const V2_LS_REFS_PREFIX: &[u8] =
    b"0014command=ls-refs\n0017object-format=sha1\n0001000csymrefs\n001bref-prefix refs/heads/\n0000";

/// v2 `ls-refs` with `unborn`. Only interesting against a repository whose
/// `HEAD` points at a ref that does not exist, which is exactly the peer of
/// [`Shape::BehindRemote`]: stock answers
/// `unborn HEAD symref-target:refs/heads/master`, a line no other case in the
/// corpus can produce.
const V2_LS_REFS_UNBORN: &[u8] =
    b"0014command=ls-refs\n0017object-format=sha1\n0001000csymrefs\n000bunborn\n0000";

/// v2 `ls-refs` carrying a `server-option`. The v2 advertisement claims
/// `server-option`; this is the request that makes the server prove it accepts
/// one rather than merely listing the word.
const V2_LS_REFS_SERVER_OPTION: &[u8] =
    b"0014command=ls-refs\n0017object-format=sha1\n001aserver-option=count=1\n0001000csymrefs\n0000";

/// A v2 command the server does not have. `fatal: invalid command 'frobnicate'`
/// and exit 128 on stock.
const V2_BOGUS_COMMAND: &[u8] =
    b"0017command=frobnicate\n0017object-format=sha1\n00010000";

/// A v2 request with capabilities and a delimiter but no `command=` at all.
const V2_NO_COMMAND: &[u8] = b"0017object-format=sha1\n00010000";

/// A flush and nothing else: the client that connected and left. Distinct from
/// the closed stdin every `fetch_clone.rs` server case uses, which is EOF
/// without a flush — a different branch in the reader.
const FLUSH: &[u8] = b"0000";

/// v2 `object-info` for one commit's size. Gated on
/// `transfer.advertiseObjectInfo`; both the gated and the ungated spelling are
/// cases, because the refusal is as much a wire fact as the answer.
const V2_OBJECT_INFO: &[u8] =
    b"0018command=object-info\n0017object-format=sha1\n00010009size\n0031oid 91bfcd8dad4adbba6d1110e504c5bd1929984f2c\n0000";

/// v2 `fetch` wanting an object it already has. The `have` is what makes the
/// resulting pack empty and therefore byte-stable; without it this request is
/// not measurable — see the module header.
const V2_FETCH_WANT_HAVE: &[u8] =
    b"0012command=fetch\n0017object-format=sha1\n0001000ethin-pack\n000eofs-delta\n0032want 91bfcd8dad4adbba6d1110e504c5bd1929984f2c\n0032have 91bfcd8dad4adbba6d1110e504c5bd1929984f2c\n0009done\n0000";

/// The v0 spelling of the same negotiation: `want` with a capability list, a
/// flush, a matching `have`, `done`. Answers `ACK … common`, `ACK …`, then the
/// side-band-framed empty pack.
const V0_WANT_HAVE_DONE: &[u8] =
    b"0078want 91bfcd8dad4adbba6d1110e504c5bd1929984f2c multi_ack_detailed side-band-64k thin-pack ofs-delta agent=git/parity\n00000032have 91bfcd8dad4adbba6d1110e504c5bd1929984f2c\n0009done\n";

/// A v0 `want` for an object the server does not have. The answer is an `ERR`
/// pkt-line on **stdout** — a wire frame, not a diagnostic — beside a local
/// message on stderr.
const V0_WANT_UNKNOWN: &[u8] =
    b"006ewant 0000000000000000000000000000000000000001 multi_ack_detailed side-band-64k ofs-delta agent=git/parity\n00000009done\n";

/// Delete `refs/heads/div` on the peer, asking for `report-status-v2`.
///
/// A deletion is the one push command that needs **no pack**, which is what
/// makes a receive-pack request expressible as a literal at all: git sends the
/// pack only when at least one command creates or updates a ref.
const RP_DELETE_V2: &[u8] =
    b"009579f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\0report-status-v2 side-band-64k agent=git/parity\n0000";

/// The same deletion asking for the **v1** `report-status`, so the two report
/// dialects are separable.
const RP_DELETE_V1: &[u8] =
    b"009279f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\0report-status side-band-64k agent=git/parity\n0000";

/// The same deletion with `report-status` and **no side band**, so the report
/// arrives unframed.
const RP_DELETE_PLAIN: &[u8] =
    b"007379f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\0report-status\n0000";

/// The same deletion with **no capabilities at all**: the client asked for no
/// report, so a correct server performs the delete and says nothing.
const RP_DELETE_NO_CAPS: &[u8] =
    b"006579f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\n0000";

/// A deletion of a ref that is not there. The `ng <ref> <reason>` line this
/// produces is a wire field a client parses, not prose.
const RP_DELETE_MISSING: &[u8] =
    b"008579f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/nope\0report-status-v2 side-band-64k\n0000";

/// Two deletions under `atomic`, the second of which cannot succeed. Both must
/// come back `ng … atomic transaction failed` and **neither** may land.
const RP_DELETE_ATOMIC: &[u8] =
    b"008b79f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\0report-status-v2 side-band-64k atomic\n006679f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/nope\n0000";

/// A deletion whose client claimed `push-options` and then sent one. The
/// server did not advertise the capability, so the section is a protocol
/// violation the server has to notice.
const RP_DELETE_PUSH_OPTION: &[u8] =
    b"009179f764eb810204174b975d237db6fd14984a72bd 0000000000000000000000000000000000000000 refs/heads/div\0report-status-v2 side-band-64k push-options\n00000008k=v\n0000";

/// A command line that is not `<old> <new> <ref>`.
const RP_GARBAGE: &[u8] = b"000cgarbage\n0000";

/// A `git daemon` request for the peer, in the shape the daemon protocol
/// defines: `<verb> <path>\0host=<host>\0`.
const DAEMON_UPLOAD_PACK: &[u8] = b"0030git-upload-pack /.remote.git\0host=localhost\0";

/// The same request with the v2 extension: a second NUL-terminated block
/// carrying `version=2`, which is how a v2 client negotiates over `git://`.
const DAEMON_UPLOAD_PACK_V2: &[u8] =
    b"003bgit-upload-pack /.remote.git\0host=localhost\0\0version=2\0";

/// `git-receive-pack` over the daemon, which is disabled by default.
const DAEMON_RECEIVE_PACK: &[u8] = b"0031git-receive-pack /.remote.git\0host=localhost\0";

/// A daemon request naming a repository that is not there.
const DAEMON_NO_SUCH_REPO: &[u8] = b"002dgit-upload-pack /nope.git\0host=localhost\0";

/// A daemon request for a service the daemon does not offer.
const DAEMON_BOGUS_SERVICE: &[u8] = b"002fgit-frobnicate /.remote.git\0host=localhost\0";

// ---------------------------------------------------------------------------
// Version negotiation
// ---------------------------------------------------------------------------

/// `GIT_PROTOCOL`, and the values of `protocol.version` git refuses.
///
/// `GIT_PROTOCOL` is the variable the *client* sets on the server process to say
/// which dialect it speaks; it is how every real v2 connection is established,
/// and `env::harden` clears the environment so no case in the corpus had it set.
/// `fetch_clone.rs` covers `protocol.version` as client configuration on
/// `fetch`; none of that reaches the handshake this variable drives.
///
/// The two refusals are pinned strictly because the message is the behaviour: an
/// unparseable `protocol.version` has to name the key and the value, and a port
/// that answers with its own library's wording gives a user nothing to grep for.
/// Measured on stock 2.55.0:
///
/// ```text
/// $ git -c protocol.version=99 ls-remote .
/// fatal: unknown value for config 'protocol.version': 99
/// ```
///
/// `--server-option` on a v0 connection is the third: server options are a v2
/// feature, and the refusal carries a `hint:` line and a second `fatal:` for the
/// hangup that follows.
fn protocol_version_selection(out: &mut Vec<Case>) {
    for version in ["0", "1", "2"] {
        out.push(
            Case::new("ls-remote", &["ls-remote", "--symref", "."], Shape::BehindRemote)
                .with_env(&[("GIT_PROTOCOL", &format!("version={version}"))]),
        );
        out.push(
            Case::strict("fetch", &["fetch", "origin"], Shape::BehindRemote)
                .with_env(&[("GIT_PROTOCOL", &format!("version={version}"))]),
        );
    }
    // A value the handshake cannot parse, delivered through the variable rather
    // than through config: git ignores it and stays on v0 rather than dying,
    // which is the opposite of what the config key does.
    out.push(
        Case::new("ls-remote", &["ls-remote", "--symref", "."], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=nonsense")]),
    );
    out.push(
        Case::new("ls-remote", &["ls-remote", "--symref", "."], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=2:extra")]),
    );

    // The config key's own refusals.
    for version in ["99", "bogus", ""] {
        out.push(
            Case::strict("ls-remote", &["ls-remote", "."], Shape::BehindRemote)
                .with_config(&[("protocol.version", version)]),
        );
    }

    // `feature.experimental` moves the default protocol version in some git
    // releases; whether it does in 2.55.0 is exactly what this pins.
    out.push(
        Case::new("ls-remote", &["ls-remote", "--symref", "."], Shape::BehindRemote)
            .with_config(&[("feature.experimental", "true")]),
    );

    // Server options across the version boundary: accepted on v2, refused on v0
    // and v1 with a message that has to name the version requirement.
    for version in ["0", "1", "2"] {
        out.push(
            Case::strict("fetch", &["fetch", "--server-option=x", "origin"], Shape::BehindRemote)
                .with_config(&[("protocol.version", version)]),
        );
    }
    // Push options across the same boundary. The peer advertises none, so both
    // versions refuse — but through different code, and the v0 refusal carries
    // the hangup line the v2 one does not.
    for version in ["0", "2"] {
        out.push(
            Case::strict(
                "push",
                &["push", "--push-option=x", "./.remote.git", "refs/heads/div:refs/heads/sent"],
                Shape::BehindRemote,
            )
            .with_config(&[("protocol.version", version)]),
        );
    }
}

/// The `version <n>` pkt-line a server emits before its advertisement.
///
/// This is the first thing on the wire and the whole of the server's half of the
/// handshake: when the client set `GIT_PROTOCOL=version=1` the server must
/// answer `000eversion 1` and then the v0 advertisement, and when it set
/// `version=2` it must answer `000eversion 2` and a capability list instead of
/// refs. A server that skips the line leaves a client that negotiated v1 reading
/// the ref advertisement as a version string.
///
/// Both verbs, both modes, and the junk values, because the port gets one of
/// these wrong and not the other — which is only visible if both are asked.
fn server_version_line(out: &mut Vec<Case>) {
    for version in ["0", "1", "2"] {
        let env = [("GIT_PROTOCOL", format!("version={version}"))];
        let env: Vec<(&str, &str)> = env.iter().map(|(k, v)| (*k, v.as_str())).collect();
        out.push(
            Case::strict("upload-pack", &["upload-pack", "."], Shape::BehindRemote)
                .with_env(&env),
        );
        out.push(
            Case::strict("receive-pack", &["receive-pack", "."], Shape::BehindRemote)
                .with_env(&env),
        );
        out.push(
            Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::BehindRemote)
                .with_env(&env),
        );
        out.push(
            Case::new(
                "receive-pack",
                &["receive-pack", "--advertise-refs", "."],
                Shape::BehindRemote,
            )
            .with_env(&env),
        );
    }

    // The peer, whose `HEAD` is dangling: under v0 that removes the `HEAD` line
    // and the `symref=HEAD:` capability, and under v2 it is invisible until a
    // client asks `ls-refs` with `unborn`.
    out.push(
        Case::strict("receive-pack", &["receive-pack", "./.remote.git"], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=1")]),
    );
    out.push(
        Case::new(
            "upload-pack",
            &["upload-pack", "--advertise-refs", "./.remote.git"],
            Shape::BehindRemote,
        )
        .with_env(&[("GIT_PROTOCOL", "version=2")]),
    );

    // A version the server cannot parse: it must fall back rather than fail.
    out.push(
        Case::strict("receive-pack", &["receive-pack", "."], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=nonsense")]),
    );
    out.push(
        Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=2:junk")]),
    );

    // `--http-backend-info-refs` is the third advertisement spelling — the one
    // `git http-backend` uses for `GET /info/refs` — and no case in the corpus
    // had ever run it. Measured on stock 2.55.0 it is byte-identical to
    // `--advertise-refs` under v0, v1 and v2 alike, and that equality is the
    // claim: a port that implements one spelling and not the other breaks it on
    // the exit code before it breaks it on a byte.
    out.push(
        Case::new(
            "upload-pack",
            &["upload-pack", "--http-backend-info-refs", "."],
            Shape::BehindRemote,
        ),
    );
    out.push(
        Case::new(
            "upload-pack",
            &["upload-pack", "--http-backend-info-refs", "./.remote.git"],
            Shape::BehindRemote,
        ),
    );
    out.push(
        Case::new(
            "upload-pack",
            &["upload-pack", "--http-backend-info-refs", "."],
            Shape::BehindRemote,
        )
        .with_env(&[("GIT_PROTOCOL", "version=2")]),
    );
    out.push(
        Case::new(
            "upload-pack",
            &["upload-pack", "--http-backend-info-refs", "."],
            Shape::BehindRemote,
        )
        .with_env(&[("GIT_PROTOCOL", "version=1")]),
    );
}

/// The v2 capability advertisement, and the six configuration keys that change
/// it.
///
/// The v2 advertisement is a *contract*: every token in it is a promise that the
/// server will answer a command or accept an argument. A server that advertises
/// a capability it does not implement is a wire break no porcelain test can see,
/// and a server that omits one it does implement makes every client fall back.
/// Each key below adds or removes exactly one token, and the case is the whole
/// list around it.
///
/// All of these are `GIT_PROTOCOL`-driven, so none collides with
/// `fetch_clone.rs`'s `-c protocol.version=2 upload-pack --advertise-refs .`,
/// which measures the *opposite* claim — that the server's own config must not
/// select a version.
fn upload_pack_v2_capabilities(out: &mut Vec<Case>) {
    let v2 = [("GIT_PROTOCOL", "version=2")];
    for (key, value) in [
        ("uploadpack.allowFilter", "true"),
        ("uploadpack.allowRefInWant", "true"),
        ("uploadpack.allowSidebandAll", "true"),
        ("uploadpack.advertiseBundleURIs", "true"),
        ("transfer.advertiseObjectInfo", "true"),
        ("uploadpack.allowAnySHA1InWant", "true"),
        ("uploadpack.hiderefs", "refs/remotes"),
        ("transfer.hiderefs", "refs/heads/div"),
    ] {
        out.push(
            Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::BehindRemote)
                .with_env(&v2)
                .with_config(&[(key, value)]),
        );
    }

    // The advertisement is a function of the repository as well as of the
    // config: a shallow repository, a packed ref store and a tag chain each
    // produce a different one, and none of the three had ever been asked in v2.
    for shape in [Shape::Packed, Shape::TagChain, Shape::Shallow, Shape::Octopus] {
        out.push(
            Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], shape)
                .with_env(&v2),
        );
    }
    // The v0 advertisement of a shallow repository carries `shallow <oid>` lines
    // that no other shape produces, and the corpus never asked for it.
    out.push(Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::Shallow));
    // `TagChain` is the only shape whose advertisement has `^{}` peel lines in
    // it, and one of its tags points at a **blob** rather than at a commit. That
    // is the whole reason this case is here: both gits emit
    // `refs/tags/blobtag^{}` naming the blob, and a peeler written for the
    // commit case alone drops exactly that one line while getting the other four
    // tags right — which is invisible in every `tag`, `for-each-ref` and
    // `ls-remote` case in the corpus, because none of them is the
    // advertisement.
    out.push(Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::TagChain));
    out.push(Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::Promisor));
}

/// v2 commands, driven by a request on stdin.
///
/// This is the group the module exists for: the server reads a real request and
/// writes a real response, and both are compared byte for byte. `ls-refs` with
/// `symrefs`/`peel`/`ref-prefix`/`unborn` covers the four arguments the command
/// takes; `object-info` covers the command that is gated behind a config key;
/// `fetch` covers the negotiation, kept byte-stable by wanting only what the
/// request already `have`s.
fn upload_pack_v2_commands(out: &mut Vec<Case>) {
    let v2 = [("GIT_PROTOCOL", "version=2")];
    let srpc = ["upload-pack", "--stateless-rpc", "."];
    let srpc_peer = ["upload-pack", "--stateless-rpc", "./.remote.git"];

    for (payload, shape) in [
        (V2_LS_REFS, Shape::BehindRemote),
        (V2_LS_REFS, Shape::Packed),
        (V2_LS_REFS, Shape::TagChain),
        (V2_LS_REFS, Shape::AmbiguousRef),
        (V2_LS_REFS, Shape::Shallow),
        (V2_LS_REFS_PREFIX, Shape::BehindRemote),
        (V2_LS_REFS_PREFIX, Shape::TagChain),
        (V2_LS_REFS_SERVER_OPTION, Shape::BehindRemote),
    ] {
        out.push(Case::with_stdin("upload-pack", &srpc, shape, payload).with_env(&v2));
    }

    // The peer's `HEAD` is dangling, so `unborn` is the only way any client can
    // learn what it points at. Both spellings, because the answer differs: on
    // the fixture `HEAD` resolves and `unborn` changes nothing.
    out.push(
        Case::with_stdin("upload-pack", &srpc_peer, Shape::BehindRemote, V2_LS_REFS_UNBORN)
            .with_env(&v2),
    );
    out.push(
        Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, V2_LS_REFS_UNBORN)
            .with_env(&v2),
    );
    out.push(
        Case::with_stdin("upload-pack", &srpc_peer, Shape::BehindRemote, V2_LS_REFS).with_env(&v2),
    );

    // `object-info`, gated and ungated. The refusal is `fatal: invalid command`
    // at exit 128, which is the same refusal an unknown command gets — so the
    // gate is only observable with both halves present.
    out.push(
        Case::strict("upload-pack", &srpc, Shape::BehindRemote)
            .with_env(&v2)
            .with_config(&[("transfer.advertiseObjectInfo", "true")]),
    );
    out.push(
        Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, V2_OBJECT_INFO)
            .with_env(&v2)
            .with_config(&[("transfer.advertiseObjectInfo", "true")]),
    );
    out.push(
        Case::strict("upload-pack", &srpc, Shape::BehindRemote)
            .with_env(&v2)
            .with_config(&[("transfer.advertiseObjectInfo", "false")]),
    );

    // The three malformed requests, strict: the diagnostic is the behaviour.
    out.push(
        Case::strict("upload-pack", &srpc, Shape::BehindRemote)
            .with_env(&v2)
            .with_config(&[("uploadpack.allowFilter", "false")]),
    );
    for payload in [V2_BOGUS_COMMAND, V2_NO_COMMAND] {
        out.push(
            Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, payload).with_env(&v2),
        );
    }
    // A flush and nothing else: a clean disconnect, which must exit 0 in silence
    // rather than reporting a hangup.
    out.push(Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, FLUSH).with_env(&v2));

    // The negotiation, with the pack kept empty so its bytes are a constant.
    out.push(
        Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, V2_FETCH_WANT_HAVE)
            .with_env(&v2),
    );
}

/// The v0 request/response cycle, driven the same way.
///
/// v0 is what every server still answers by default and what a client gets when
/// it sets nothing, so its `ACK`/`NAK` sequence and its side-band framing are
/// the wire most transports actually use. Nothing in the corpus had ever written
/// a v0 request.
fn upload_pack_v0_requests(out: &mut Vec<Case>) {
    let srpc = ["upload-pack", "--stateless-rpc", "."];
    let srpc_peer = ["upload-pack", "--stateless-rpc", "./.remote.git"];
    let plain_peer = ["upload-pack", "./.remote.git"];

    // `ACK <oid> common`, `ACK <oid>`, then the empty pack framed on side-band 1
    // and the server's progress on side-band 2.
    out.push(Case::with_stdin("upload-pack", &srpc_peer, Shape::BehindRemote, V0_WANT_HAVE_DONE));
    out.push(Case::with_stdin("upload-pack", &plain_peer, Shape::BehindRemote, V0_WANT_HAVE_DONE));

    // A `want` the server cannot satisfy. The `ERR` frame lands on stdout; the
    // local diagnostic is on stderr, so this one is strict.
    out.push(strict_stdin("upload-pack", &srpc_peer, Shape::BehindRemote, V0_WANT_UNKNOWN));

    // Flush-only, in both modes and against both repositories.
    out.push(Case::with_stdin("upload-pack", &srpc, Shape::BehindRemote, FLUSH));
    out.push(Case::with_stdin("upload-pack", &srpc_peer, Shape::BehindRemote, FLUSH));
    out.push(Case::with_stdin("upload-pack", &["upload-pack", "."], Shape::BehindRemote, FLUSH));
}

/// `uploadpack.hiderefs` and `transfer.hiderefs`, including the one pattern that
/// hides `HEAD` itself.
///
/// `fetch_clone.rs` covers `uploadpack.hiderefs=refs/remotes`, which removes two
/// ordinary refs. Hiding `HEAD` is a different code path: the advertisement's
/// *first* line carries the capability list, so removing `HEAD` moves the
/// capabilities onto whatever ref now leads. Measured on stock 2.55.0 over
/// `Shape::BehindRemote`, `-c uploadpack.hiderefs=HEAD upload-pack
/// --advertise-refs .` leads with `refs/heads/div` and keeps
/// `symref=HEAD:refs/heads/main` in the capability list — the ref is hidden, the
/// symref hint is not.
fn upload_pack_hidden_refs(out: &mut Vec<Case>) {
    for (key, value) in [
        ("uploadpack.hiderefs", "HEAD"),
        ("uploadpack.hiderefs", "refs/heads"),
        ("uploadpack.hiderefs", "refs"),
        ("transfer.hiderefs", "refs/remotes"),
        ("transfer.hiderefs", "refs/heads/div"),
    ] {
        out.push(
            Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::BehindRemote)
                .with_config(&[(key, value)]),
        );
    }
    // A negated pattern: hide everything, then unhide one namespace. `!` is the
    // half of the syntax a port that treats the value as a plain prefix drops.
    out.push(
        Case::new("upload-pack", &["upload-pack", "--advertise-refs", "."], Shape::BehindRemote)
            .with_scoped_config(vec![
                ConfigEntry::set(ConfigScope::Repo, "uploadpack.hiderefs", "refs"),
                ConfigEntry::set(ConfigScope::Repo, "uploadpack.hiderefs", "!refs/heads"),
            ]),
    );
}

/// `receive-pack` answering a real push, and the `report-status`/
/// `report-status-v2` reply it writes back.
///
/// A deletion is the only push command that needs no pack, and that is what
/// makes this group possible at all — see [`RP_DELETE_V2`]. Every case here
/// therefore writes on the peer or refuses to, and `runner::probe_peer` reads
/// the peer's refs back, so "said `ok` and did nothing" is caught.
///
/// The `ng <ref> <reason>` string is the field under test. It is not a
/// diagnostic: `send-pack` parses it, `transport-helper` re-emits it, and a
/// client shows it to a user as the reason a push was rejected. Stock 2.55.0's
/// vocabulary is `reference does not exist`, `incorrect old value provided`,
/// `atomic transaction failed` and `deletion prohibited`.
///
/// **Two of those moved between git versions and the alt-oracle will say so.**
/// Measured by hand: `/usr/bin/git` 2.50.1 answers the generic
/// `ng <ref> failed to update ref` where 2.55.0 answers
/// `reference does not exist` and `incorrect old value provided`. So a failure
/// on those two cases is a `version-skew` verdict *only* if the port matches
/// 2.50.1 — and it does not: it answers a third string of its own, in both
/// cases, which is what makes them defects rather than skew.
fn receive_pack_reports(out: &mut Vec<Case>) {
    let peer = ["receive-pack", "./.remote.git"];
    let peer_srpc = ["receive-pack", "--stateless-rpc", "./.remote.git"];
    let here = ["receive-pack", "."];

    // The four report dialects for one successful deletion.
    for payload in [RP_DELETE_V2, RP_DELETE_V1, RP_DELETE_PLAIN, RP_DELETE_NO_CAPS] {
        out.push(Case::with_stdin("receive-pack", &peer, Shape::BehindRemote, payload));
    }
    out.push(Case::with_stdin("receive-pack", &peer_srpc, Shape::BehindRemote, RP_DELETE_V2));

    // Refusals, each with a different `ng` reason.
    out.push(Case::with_stdin("receive-pack", &peer, Shape::BehindRemote, RP_DELETE_MISSING));
    out.push(Case::with_stdin("receive-pack", &peer, Shape::BehindRemote, RP_DELETE_ATOMIC));
    out.push(Case::with_stdin("receive-pack", &peer, Shape::BehindRemote, RP_DELETE_PUSH_OPTION));
    // The peer's `div` is not the fixture's `div`, so this same request against
    // the fixture is an old-value mismatch rather than a deletion.
    out.push(Case::with_stdin("receive-pack", &here, Shape::BehindRemote, RP_DELETE_V2));
    // A command line that is not a command line.
    out.push(strict_stdin("receive-pack", &peer, Shape::BehindRemote, RP_GARBAGE));

    // The receiving repository's policy, delivered at `Repo` scope because that
    // is the only scope the receiving end reads — `-c` on this argv is on the
    // server's own command line and so happens to work, but the file is what a
    // real deployment writes and what `fetch_clone.rs` established as the
    // spelling for `receive.*`.
    for (key, value) in [
        ("receive.denyDeletes", "true"),
        ("receive.denyNonFastForwards", "true"),
        ("receive.fsckObjects", "true"),
        ("receive.unpackLimit", "1"),
    ] {
        out.push(
            Case::with_stdin("receive-pack", &peer, Shape::BehindRemote, RP_DELETE_V2)
                .with_scoped_config(vec![ConfigEntry::set(ConfigScope::Repo, key, value)]),
        );
    }
    // A flush and nothing else: the client connected, read the advertisement and
    // left. Exit 0 and no report, which is different from the EOF the corpus's
    // existing `receive-pack .` cases produce.
    out.push(strict_stdin("receive-pack", &here, Shape::BehindRemote, FLUSH));
    out.push(strict_stdin("receive-pack", &peer, Shape::BehindRemote, FLUSH));
}

/// The `receive.*` keys that change the **advertisement** rather than the
/// outcome, at `Repo` scope.
///
/// Each of these adds or removes one capability token, and the capability list
/// is the contract a client negotiates against: `receive.advertisePushOptions`
/// adds `push-options`, `receive.advertiseAtomic=false` removes `atomic`. A
/// server that keeps the token and drops the behaviour, or the reverse, is a
/// wire break; the advertisement half is what this group pins and the behaviour
/// half is [`receive_pack_reports`].
///
/// `receive.certNonceSeed` is deliberately absent — it puts a clock reading in
/// the advertisement.
fn receive_pack_advertisement(out: &mut Vec<Case>) {
    for (key, value) in [
        ("receive.advertisePushOptions", "true"),
        ("receive.advertisePushOptions", "false"),
        ("receive.advertiseAtomic", "false"),
        ("receive.denyDeletes", "true"),
        ("receive.denyNonFastForwards", "true"),
        ("receive.maxInputSize", "1"),
        ("receive.procReceiveRefs", "refs/for"),
        ("receive.shallowUpdate", "true"),
    ] {
        out.push(
            Case::strict("receive-pack", &["receive-pack", "."], Shape::BehindRemote)
                .with_scoped_config(vec![ConfigEntry::set(ConfigScope::Repo, key, value)]),
        );
    }
    // `receive.hiderefs`, the third member of the `hiderefs` family, which no
    // case in the corpus set.
    for value in ["refs/remotes", "HEAD"] {
        out.push(
            Case::strict("receive-pack", &["receive-pack", "."], Shape::BehindRemote)
                .with_config(&[("receive.hiderefs", value)]),
        );
    }
}

/// `fetch-pack`'s shallow arguments, which are the ones that turn into
/// `deepen`, `deepen-since` and `deepen-not` lines on the wire.
///
/// `fetch_clone.rs` covers `--depth=1` and nothing else of this family. The
/// three that are missing are the three the server has to translate: a
/// `--shallow-since` cutoff becomes `deepen-since <unix time>`, a
/// `--shallow-exclude` becomes `deepen-not <ref>` and is validated *by the
/// server* against its own ref store, and `--deepen` is relative rather than
/// absolute.
///
/// Both dates are literals on either side of the fixtures' pinned commit clock —
/// `env::harden` fixes every commit at `1700000000`, so `2005-01-01` is before
/// the whole history on every machine and forever and `2030-01-01` is after it.
/// Neither reads the wall clock.
fn fetch_pack_shallow_wire(out: &mut Vec<Case>) {
    let peer = "./.remote.git";
    for args in [
        vec!["fetch-pack", "--all", "--shallow-since=2005-01-01", peer],
        vec!["fetch-pack", "--all", "--shallow-exclude=refs/heads/main", peer],
        vec!["fetch-pack", "--all", "--depth=2", peer],
        vec!["fetch-pack", "--all", "--depth=1", "--deepen-relative", peer],
        vec!["fetch-pack", "--all", "--no-thin", peer],
        vec!["fetch-pack", "--all", "--lock-pack", peer],
        vec!["fetch-pack", "--all", "--check-self-contained-and-connected", peer],
    ] {
        out.push(Case::new("fetch-pack", &args, Shape::BehindRemote));
    }
    // Two refusals the *server* produces and the client has to relay: a cutoff
    // that excludes everything, and a `deepen-not` naming a ref the server does
    // not have. Strict, because the relayed message is the whole answer.
    out.push(Case::strict(
        "fetch-pack",
        &["fetch-pack", "--all", "--shallow-since=2030-01-01", peer],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "fetch-pack",
        &["fetch-pack", "--all", "--shallow-exclude=refs/heads/nope", peer],
        Shape::BehindRemote,
    ));
    // The same requests one version up, where they are `deepen-since`/
    // `deepen-not` arguments of the v2 `fetch` command rather than v0 request
    // lines — a different encoder on both ends.
    out.push(
        Case::new(
            "fetch-pack",
            &["fetch-pack", "--all", "--shallow-since=2005-01-01", peer],
            Shape::BehindRemote,
        )
        .with_env(&[("GIT_PROTOCOL", "version=2")]),
    );
    out.push(
        Case::new("fetch-pack", &["fetch-pack", "--all", "--depth=2", peer], Shape::BehindRemote)
            .with_config(&[("protocol.version", "2")]),
    );
}

/// `--diag-url`: the URL parser, printed and not connected to.
///
/// This is the one place in the corpus a non-local URL is safe, and the safety
/// is a measured fact rather than an assumption. `fetch-pack --diag-url` prints
/// its decomposition and returns before any transport is constructed: stock
/// 2.55.0 answers `Diag: protocol=ssh` / `userandhost=host` / `port=NONE` /
/// `path=/path` for `ssh://host/path` and exits 0 immediately, and the port
/// refuses with a `not ported` message and exits 1 immediately. Neither resolves
/// a hostname — checked on both binaries by hand, which is the bar
/// `fetch_clone.rs`'s header sets for a URL appearing in this corpus at all.
///
/// `fetch_clone.rs` already carries `--diag-url ./.remote.git`, which is the
/// `protocol=file` line. Every spelling here is a *different* transport, which
/// is what the parser is for.
fn fetch_pack_diag_url(out: &mut Vec<Case>) {
    for url in [
        "ssh://host/path",
        "ssh://user@host:2222/path",
        "host:path",
        "user@host:path",
        "git://host/path",
        "git://host:9418/path",
        "ext::cat %S",
        "../elsewhere.git",
    ] {
        out.push(Case::strict("fetch-pack", &["fetch-pack", "--diag-url", url], Shape::BehindRemote));
    }
}

/// `send-pack`'s ref *selection*: `--all` and `--mirror`, which name a set
/// rather than match a pattern.
///
/// Not refspec grammar and so not `refspec_algebra.rs`'s: `--all` means
/// "everything under `refs/heads/`" and `--mirror` means "everything under
/// `refs/`", and both questions are which set the verb built and whether it
/// applied force. Both destinations write on the peer, which `probe_peer` reads
/// back, so a wrong set is caught in state and not only in the report.
///
/// The fixture is built so neither is a fast-forward: the local `div` and `main`
/// diverge from the peer's, so a correct `--all` and a correct `--mirror` both
/// come back `! [rejected] … (non-fast-forward)` and leave the peer untouched.
fn send_pack_ref_selection(out: &mut Vec<Case>) {
    out.push(Case::strict("send-pack", &["send-pack", "--all", "./.remote.git"], Shape::BehindRemote));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--mirror", "./.remote.git"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--all", "--force", "./.remote.git"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--mirror", "--dry-run", "./.remote.git"],
        Shape::BehindRemote,
    ));
    // Atomic with one command that cannot succeed: stock rolls the whole
    // transaction back, so `refs/heads/ok` must not exist on the peer
    // afterwards. The peer probe is the half of this that cannot be faked.
    out.push(Case::strict(
        "send-pack",
        &[
            "send-pack",
            "--atomic",
            "./.remote.git",
            "refs/heads/main:refs/heads/div",
            "refs/heads/div:refs/heads/ok",
        ],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &[
            "send-pack",
            "./.remote.git",
            "refs/heads/main:refs/heads/div",
            "refs/heads/div:refs/heads/ok",
        ],
        Shape::BehindRemote,
    ));
}

/// The `send-pack` modes that change the protocol rather than the ref set.
///
/// * `--helper-status` replaces the human report with the machine one a remote
///   helper consumes: one `ok <ref>` or `error <ref> <reason>` per ref *the
///   client considered*, on stdout. It is a wire format with a parser at the far
///   end (`transport-helper.c`), so it is measured on stdout like an
///   advertisement and not like prose.
/// * `--stateless-rpc` says stdin and stdout **are** the connection. With the
///   harness's closed stdin there is nothing to read, so the correct answer is a
///   refusal — a server-side flag on a client verb is exactly the kind of thing
///   a port accepts and ignores.
/// * `--push-option` and `--signed` both require a capability the peer does not
///   advertise, so both are refusals; they are here because the refusal is the
///   negotiation.
/// * `--thin`/`--no-thin` change what is in the pack rather than what is said
///   about it, and the peer probe reads the object store back.
fn send_pack_wire_modes(out: &mut Vec<Case>) {
    let here_sent = ["send-pack", ".", "refs/heads/div:refs/heads/sent"];

    out.push(Case::new(
        "send-pack",
        &["send-pack", "--helper-status", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));
    out.push(Case::new(
        "send-pack",
        &["send-pack", "--helper-status", "./.remote.git", "refs/heads/main:refs/heads/div"],
        Shape::BehindRemote,
    ));
    out.push(Case::new(
        "send-pack",
        &["send-pack", "--helper-status", "--dry-run", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));

    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--stateless-rpc", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--stateless-rpc", "--helper-status", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));

    for opt in ["--push-option=one", "--signed=true", "--signed=if-asked", "--signed=false"] {
        let mut args = vec!["send-pack", opt];
        args.extend_from_slice(&here_sent[1..]);
        out.push(Case::strict("send-pack", &args, Shape::BehindRemote));
    }
    // `receive.advertisePushOptions` on the *receiving* repository, which is the
    // fixture itself here — the one arrangement in which a push option can
    // actually be delivered rather than refused.
    out.push(
        Case::strict(
            "send-pack",
            &["send-pack", "--push-option=one", ".", "refs/heads/div:refs/heads/sent"],
            Shape::BehindRemote,
        )
        .with_scoped_config(vec![ConfigEntry::set(
            ConfigScope::Repo,
            "receive.advertisePushOptions",
            "true",
        )]),
    );

    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--no-thin", "./.remote.git", "refs/heads/div:refs/heads/thin"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--thin", "./.remote.git", "refs/heads/div:refs/heads/thin"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--progress", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));
    out.push(Case::strict(
        "send-pack",
        &["send-pack", "--receive-pack=false", ".", "refs/heads/div:refs/heads/sent"],
        Shape::BehindRemote,
    ));
}

/// `ls-remote` as a protocol client: the version axis and the server-option
/// pass-through.
///
/// `fetch_clone.rs` owns `ls-remote`'s option surface — `--symref`, `--heads`,
/// `--tags`, `--refs`, `--sort`, `--exit-code`, `--get-url`, patterns. What it
/// never varies is the *protocol* underneath, and `ls-remote` is the one verb
/// whose entire output is the advertisement, which makes it the cheapest place
/// to see a version difference.
fn ls_remote_protocol(out: &mut Vec<Case>) {
    for version in ["0", "1", "2"] {
        out.push(
            Case::new("ls-remote", &["ls-remote", "--symref", "./.remote.git"], Shape::BehindRemote)
                .with_config(&[("protocol.version", version)]),
        );
    }
    // Server options: accepted and forwarded on v2, refused on v0. Strict, since
    // the refusal is the whole observable.
    out.push(
        Case::new("ls-remote", &["ls-remote", "-o", "count=1", "."], Shape::BehindRemote)
            .with_config(&[("protocol.version", "2")]),
    );
    out.push(
        Case::strict("ls-remote", &["ls-remote", "-o", "count=1", "."], Shape::BehindRemote)
            .with_config(&[("protocol.version", "0")]),
    );
    out.push(
        Case::new(
            "ls-remote",
            &["ls-remote", "--server-option=count=1", "--server-option=count=2", "."],
            Shape::BehindRemote,
        )
        .with_config(&[("protocol.version", "2")]),
    );
    // v2 against a peer whose `HEAD` is unborn: the `unborn` extension is how
    // v2 reports it, and `--symref` is where it surfaces.
    out.push(
        Case::new("ls-remote", &["ls-remote", "--symref", "origin"], Shape::BehindRemote)
            .with_env(&[("GIT_PROTOCOL", "version=2")]),
    );
}

/// `git daemon` serving exactly one request from stdin.
///
/// The listening daemon is not measurable — a port, a pid, an accept loop — but
/// `--inetd` is the same server reading one request off stdin and writing the
/// answer to stdout, with nothing time- or process-dependent anywhere in it.
/// Verified twice per side: identical bytes, identical exit codes, no timestamp,
/// no pid, no socket path.
///
/// The verb's *protocol* was unmeasured. `misc_commands.rs` carries seven
/// `daemon` cases and all seven are option parsing on `Shape::Linear` — no
/// request reaches any of them, so nothing in the corpus had ever asked the
/// daemon a question. The four here are its whole contract: which service was
/// asked for, whether the repository is exported, what the virtual path resolves
/// to under `--base-path`, and what an unknown service gets.
fn daemon_inetd(out: &mut Vec<Case>) {
    let inetd = ["daemon", "--inetd", "--export-all", "--base-path=."];
    let inetd_closed = ["daemon", "--inetd", "--base-path=."];

    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, DAEMON_UPLOAD_PACK));
    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, DAEMON_UPLOAD_PACK_V2));
    // Without `--export-all` the peer has no `git-daemon-export-ok`, so the
    // answer is an `ERR` frame rather than an advertisement.
    out.push(Case::with_stdin("daemon", &inetd_closed, Shape::BehindRemote, DAEMON_UPLOAD_PACK));
    // `receive-pack` over the daemon is disabled by default and has to be turned
    // on by name.
    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, DAEMON_RECEIVE_PACK));
    out.push(Case::with_stdin(
        "daemon",
        &["daemon", "--inetd", "--export-all", "--enable=receive-pack", "--base-path=."],
        Shape::BehindRemote,
        DAEMON_RECEIVE_PACK,
    ));
    // A repository that is not there, a service that does not exist, and a
    // client that flushed without asking anything.
    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, DAEMON_NO_SUCH_REPO));
    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, DAEMON_BOGUS_SERVICE));
    out.push(Case::with_stdin("daemon", &inetd, Shape::BehindRemote, FLUSH));
    // Option parsing with no request at all is `misc_commands.rs`'s: it already
    // carries `daemon --inetd --port=1234`, `--detach --inetd`, `--port=not-a-number`
    // and four more, all on `Shape::Linear`. Nothing here repeats them, and
    // `--strict-paths`/`--forbid-override` are left out for the same reason the
    // group is eight cases and not eleven: while the verb is unported every one of
    // them is the same refusal, and eight already say so.
}
