//! `git difftool` — show changes using an external diff tool.
//! **The tool launcher itself is not ported: those paths bail.**
//!
//! `difftool` is a front-end that computes a diff and then hands each changed
//! path to an *external program*. Its stdout is whatever that program writes, so
//! there is no git-owned output to reproduce for the launching paths. What is
//! ported here is the surface that is byte-verifiable without launching
//! anything (all checked against git 2.55.0):
//!
//!   * `-h` → git's 813-byte usage block on **stdout**, exit 129. This is
//!     handled by `parse_options` before any repository setup, so it works
//!     outside a repository and inside a bare one.
//!   * a value-taking option with no value → `error: option `<name>' requires a
//!     value` (long form) or ``error: switch `<c>' requires a value`` (short
//!     form) on stderr, exit 129 — also before repository setup.
//!   * no repository/worktree → `fatal: difftool requires worktree or
//!     --no-index`, exit 128.
//!   * a bare repository → `fatal: this operation must be run in a work tree`,
//!     exit 128.
//!   * `--tool=` / `--extcmd=` with an empty value → `fatal: no <tool> given for
//!     --tool=<tool>` / `fatal: no <cmd> given for --extcmd=<cmd>`, exit 128.
//!     These fire *after* the worktree check, matching the C.
//!   * `git difftool [-y|--no-prompt] [-d|--dir-diff]` with no revision and no
//!     pathspec, in a worktree whose unstaged diff is empty → no output, exit 0.
//!     git launches no tool in that case, so this is the one launching-shaped
//!     invocation with a fully determined result.
//!
//! Everything else bails. The missing substrate, concretely:
//!
//!   1. **The tool database.** Choosing and invoking a tool is implemented as
//!      POSIX shell: `git-difftool--helper` sources `git-mergetool--lib`, which
//!      sources one script per tool out of `$(git --exec-path)/mergetools/`
//!      (24 files in the 2.55.0 install this was checked against). Each script
//!      supplies that tool's `diff_cmd`, `merge_cmd` and availability probe.
//!      Nothing in the vendored crates under `src/ported` carries any of it —
//!      there is no tool registry, no `diff_cmd` table, and no equivalent of
//!      `git-mergetool--lib`'s fallback ordering over `diff.tool`,
//!      `merge.tool`, `diff.guitool`, `merge.guitool` and the built-in default.
//!   2. **`--tool-help`.** Its output is generated by enumerating that same
//!      `mergetools/` directory, partitioning it by whether each tool's binary
//!      is present on `PATH`, and appending the user's `difftool.<t>.cmd`
//!      entries. It is therefore a function of the git *installation* and of
//!      user config, not of the repository, and cannot be derived from the
//!      vendored crates at all.
//!   3. **The temporary checkout.** Both the per-file mode and `--dir-diff`
//!      materialise the pre-/post-image into a `mktemp -d` directory and export
//!      it as `$LOCAL`/`$REMOTE`/`$BASE`/`$MERGED`. That directory name is
//!      random, so even `--extcmd=echo` — the one invocation whose child output
//!      is predictable — cannot be byte-matched: stock git prints a path
//!      containing fresh entropy on every run.
//!   4. **Prompting.** Without `-y`, git writes a prompt to stderr and reads a
//!      reply from the terminal before each file. That is interactive by
//!      construction and has no non-interactive equivalent.
//!
//! These paths are deliberately not approximated. A `difftool` invocation that
//! returned 0 without launching a tool would be indistinguishable from a
//! successful one that did, while leaving the user's diff unreviewed — the
//! worst failure mode for a harness that compares exit codes.

use anyhow::{bail, Result};
use std::process::ExitCode;

/// Stock git's `difftool` usage block, byte-for-byte (813 bytes, git 2.55.0),
/// including the trailing blank line. Printed on `-h` (stdout).
const USAGE: &str = concat!(
    "usage: git difftool [<options>] [<commit> [<commit>]] [--] [<path>...]\n",
    "\n",
    "\x20   -g, --[no-]gui        use `diff.guitool` instead of `diff.tool`\n",
    "\x20   -d, --[no-]dir-diff   perform a full-directory diff\n",
    "\x20   -y, --no-prompt       do not prompt before launching a diff tool\n",
    "\x20   --[no-]symlinks       use symlinks in dir-diff mode\n",
    "\x20   -t, --[no-]tool <tool>\n",
    "\x20                         use the specified diff tool\n",
    "\x20   --[no-]tool-help      print a list of diff tools that may be used with `--tool`\n",
    "\x20   --[no-]trust-exit-code\n",
    "\x20                         make 'git-difftool' exit when an invoked diff tool returns a non-zero exit code\n",
    "\x20   -x, --[no-]extcmd <command>\n",
    "\x20                         specify a custom command for viewing diffs\n",
    "\x20   --no-index            passed to `diff`\n",
    "\x20   --index               opposite of --no-index\n",
    "\n",
);

/// The options that take a separate value argument, as `(long, short)`.
const VALUE_OPTS: [(&str, char); 2] = [("tool", 't'), ("extcmd", 'x')];

/// What the parsed command line asks for, as far as this module tracks it.
#[derive(Default)]
struct Opts {
    /// `--tool-help` was given.
    tool_help: bool,
    /// `--tool=`/`-t` value, if any. `Some("")` means an explicitly empty value.
    tool: Option<String>,
    /// `--extcmd=`/`-x` value, if any. `Some("")` means an explicitly empty value.
    extcmd: Option<String>,
    /// `--no-index` was given (`difftool` then diffs two paths outside any repo).
    no_index: bool,
    /// Any argument that is not one of the options `difftool` itself defines:
    /// revisions, pathspecs, and the `git diff` options it forwards. Tracked so
    /// the empty-diff fast path can refuse to fire when the diff it would have
    /// to compute is not the plain unstaged one.
    others: Vec<String>,
}

/// `git difftool` — argument validation and the empty-diff case only; launching
/// a diff tool is not ported.
///
/// See the module documentation for the exact set of invocations that are
/// reproduced byte-for-byte, and for the substrate the rest would need.
pub fn difftool(args: &[String]) -> Result<ExitCode> {
    // Dispatch includes the verb at index 0. `difftool`'s own positionals are
    // revisions and paths, so a leading literal `difftool` is unambiguous only
    // as the verb; strip exactly one.
    let args = match args.first().map(String::as_str) {
        Some("difftool") => &args[1..],
        _ => args,
    };

    // Phase 1 — parse_options. `-h`, and every "requires a value" diagnostic,
    // are emitted here, before git looks at the repository at all.
    let mut opts = Opts::default();
    let mut end_of_opts = false;
    let mut i = 0;
    while i < args.len() {
        let a = args[i].as_str();

        if end_of_opts {
            opts.others.push(a.to_owned());
            i += 1;
            continue;
        }

        match a {
            "--" => {
                end_of_opts = true;
                // A bare trailing `--` is not itself a pathspec; anything after
                // it is, and lands in `others` on the next iterations.
            }
            "-h" => {
                print!("{USAGE}");
                return Ok(ExitCode::from(129));
            }
            "--tool-help" => opts.tool_help = true,
            "--no-tool-help" => opts.tool_help = false,
            "-d" | "--dir-diff" | "--no-dir-diff" => {}
            "-y" | "--no-prompt" | "--prompt" => {}
            "-g" | "--gui" | "--no-gui" => {}
            "--symlinks" | "--no-symlinks" => {}
            "--trust-exit-code" | "--no-trust-exit-code" => {}
            "--no-index" => opts.no_index = true,
            "--index" => opts.no_index = false,
            "--no-tool" => opts.tool = None,
            "--no-extcmd" => opts.extcmd = None,

            // `--tool <v>` / `--extcmd <v>`: a separate value argument.
            _ if VALUE_OPTS.iter().any(|(l, _)| a.strip_prefix("--") == Some(*l)) => {
                let name = &a[2..];
                let short = short_for(name);
                let Some(v) = args.get(i + 1) else {
                    return Ok(usage_error(&format!("option `{name}' requires a value")));
                };
                store_value(&mut opts, short, v.clone());
                i += 1;
            }
            // `--tool=<v>` / `--extcmd=<v>`, including an empty `<v>`; the
            // emptiness is diagnosed later, after the worktree check.
            _ if VALUE_OPTS
                .iter()
                .any(|(l, _)| a.starts_with(&format!("--{l}="))) =>
            {
                let (name, v) = a[2..].split_once('=').unwrap_or((&a[2..], ""));
                store_value(&mut opts, short_for(name), v.to_owned());
            }

            _ if a.starts_with("--") => {
                // git forwards unrecognised long options to `git diff`, which
                // reports them against *its own* usage block. Reproducing that
                // here would duplicate `diff`'s surface and drift from it, so
                // refuse instead of guessing.
                bail!(
                    "unsupported flag {a:?} — difftool forwards unknown options to `git diff` \
                     (ported: -h, -y/--no-prompt, --prompt, -d/--dir-diff, -g/--gui, --symlinks, \
                     --trust-exit-code, -t/--tool, -x/--extcmd, --tool-help, --index/--no-index)"
                );
            }

            // Clustered short switches, e.g. `-yd` or `-t vimdiff`.
            _ if a.len() > 1 && a.starts_with('-') => {
                let mut chars = a[1..].chars();
                while let Some(c) = chars.next() {
                    match c {
                        'h' => {
                            print!("{USAGE}");
                            return Ok(ExitCode::from(129));
                        }
                        'y' | 'g' | 'd' => {}
                        't' | 'x' => {
                            // The value is the rest of the cluster if non-empty,
                            // otherwise the next argument.
                            let rest: String = chars.by_ref().collect();
                            if rest.is_empty() {
                                let Some(v) = args.get(i + 1) else {
                                    return Ok(usage_error(&format!(
                                        "switch `{c}' requires a value"
                                    )));
                                };
                                store_value(&mut opts, c, v.clone());
                                i += 1;
                            } else {
                                store_value(&mut opts, c, rest);
                            }
                        }
                        _ => bail!(
                            "unsupported flag {:?} — difftool forwards unknown switches to \
                             `git diff` (ported: -h, -y, -d, -g, -t, -x)",
                            format!("-{c}")
                        ),
                    }
                }
            }

            _ => opts.others.push(a.to_owned()),
        }
        i += 1;
    }

    // `--tool-help` is answered right after parsing, before repository setup —
    // it works outside a repository and in a bare one. Its content is not
    // derivable here; see the module docs.
    if opts.tool_help {
        bail!(
            "--tool-help is not ported: its listing is produced by enumerating \
             $(git --exec-path)/mergetools/ and probing each tool's binary on PATH, and no such \
             tool database exists in the vendored crates"
        );
    }

    // Phase 2 — repository setup. Both diagnostics are git's own, exit 128.
    let repo = match gix::discover(".") {
        Ok(repo) => repo,
        Err(_) => {
            if opts.no_index {
                bail!(
                    "--no-index is not ported: it still materialises both sides into a temporary \
                     directory and launches an external tool"
                );
            }
            eprintln!("fatal: difftool requires worktree or --no-index");
            return Ok(ExitCode::from(128));
        }
    };
    if repo.workdir().is_none() {
        eprintln!("fatal: this operation must be run in a work tree");
        return Ok(ExitCode::from(128));
    }

    // Phase 3 — the empty-value checks, which the C performs after setup.
    if opts.tool.as_deref() == Some("") {
        eprintln!("fatal: no <tool> given for --tool=<tool>");
        return Ok(ExitCode::from(128));
    }
    if opts.extcmd.as_deref() == Some("") {
        eprintln!("fatal: no <cmd> given for --extcmd=<cmd>");
        return Ok(ExitCode::from(128));
    }
    if opts.no_index {
        bail!(
            "--no-index is not ported: it still materialises both sides into a temporary \
             directory and launches an external tool"
        );
    }

    // Phase 4 — the one launching-shaped invocation with a determined result:
    // plain `git difftool` (optionally `-y`/`-d`) with no revision and no
    // pathspec, over a worktree that has nothing unstaged. git computes the
    // diff, finds it empty, launches no tool, prints nothing and exits 0.
    //
    // Any other argument shape would need a different diff than the plain
    // index-vs-worktree one (a revision range, `--cached`, a pathspec), so it
    // falls through to the bail rather than answering from the wrong diff.
    let plain = opts.others.is_empty() && opts.tool.is_none() && opts.extcmd.is_none();
    if plain && !has_unstaged(&repo)? {
        return Ok(ExitCode::SUCCESS);
    }

    bail!(
        "difftool is not ported: selecting and running a diff tool is implemented as POSIX shell \
         (git-difftool--helper sourcing git-mergetool--lib and one script per tool from \
         $(git --exec-path)/mergetools/), the pre-/post-images are staged into a mktemp directory \
         whose randomised path appears in the tool's own output, and without -y git prompts on the \
         terminal — none of which the vendored crates provide \
         (ported: -h, usage errors, the worktree/bare diagnostics, --tool=/--extcmd= empty-value \
         diagnostics, and the empty-diff exit-0 case)"
    )
}

/// The short letter a value-taking long option is spelled with (`tool` → `t`),
/// or `'\0'` for a name that is not one of them.
fn short_for(long: &str) -> char {
    VALUE_OPTS
        .iter()
        .find(|(l, _)| *l == long)
        .map(|(_, s)| *s)
        .unwrap_or('\0')
}

/// Record a `--tool`/`--extcmd` value, keyed by the option's short letter.
fn store_value(opts: &mut Opts, short: char, value: String) {
    match short {
        't' => opts.tool = Some(value),
        'x' => opts.extcmd = Some(value),
        _ => {}
    }
}

/// git's parse-options failure shape for `difftool`: `error: <msg>` on stderr,
/// exit 129. Unlike `-h`, no usage block follows.
fn usage_error(msg: &str) -> ExitCode {
    eprintln!("error: {msg}");
    ExitCode::from(129)
}

/// Whether the worktree differs from the index — i.e. whether plain `git diff`
/// would produce anything, and so whether `difftool` would launch a tool.
///
/// Untracked files are ignored (`git diff` does not report them), as are
/// `NeedsUpdate` entries, which signal only that a stat cache line is racily
/// stale and not that the content changed. Anything else counts as a change, so
/// the answer errs towards "there is a diff" and this module bails rather than
/// claiming a clean tree it has not proven.
fn has_unstaged(repo: &gix::Repository) -> Result<bool> {
    use gix::bstr::BString;
    use gix::status::UntrackedFiles;
    use gix::status::index_worktree::Item;
    use gix::status::plumbing::index_as_worktree::EntryStatus;

    let patterns: Vec<BString> = Vec::new();
    let iter = repo
        .status(gix::progress::Discard)?
        // `git diff` never reports untracked paths, so skip the directory walk.
        .untracked_files(UntrackedFiles::None)
        .into_index_worktree_iter(patterns)?;

    for item in iter {
        match item? {
            // Racily-clean: the stat data was stale but the content matched, so
            // there is nothing for `git diff` to report.
            Item::Modification {
                status: EntryStatus::NeedsUpdate(_),
                ..
            } => {}
            // Everything else — content, mode and type changes, deletions,
            // intent-to-add entries and conflicts — is a diff git would show.
            _ => return Ok(true),
        }
    }
    Ok(false)
}
