//! `git difftool` — show changes using an external diff tool.
//! **The tool launcher itself is not ported: those paths bail.**
//!
//! `difftool` is a front-end that computes a diff and then hands each changed
//! path to an *external program*. Its stdout is whatever that program writes, so
//! there is no git-owned output to reproduce for the launching paths. What is
//! ported here is the surface that is byte-verifiable without launching
//! anything (all checked against git 2.55.0):
//!
//!   * `-h` → git's 813-byte usage block on **stdout**, exit 129. This is
//!     handled by `parse_options` before any repository setup, so it works
//!     outside a repository and inside a bare one.
//!   * a value-taking option with no value → `error: option `<name>' requires a
//!     value` (long form) or ``error: switch `<c>' requires a value`` (short
//!     form) on stderr, exit 129 — also before repository setup.
//!   * no repository/worktree → `fatal: difftool requires worktree or
//!     --no-index`, exit 128.
//!   * a bare repository → `fatal: this operation must be run in a work tree`,
//!     exit 128.
//!   * `--tool=` / `--extcmd=` with an empty value → `fatal: no <tool> given for
//!     --tool=<tool>` / `fatal: no <cmd> given for --extcmd=<cmd>`, exit 128.
//!     These fire *after* the worktree check, matching the C.
//!   * An invocation whose *whole* diff is empty → no output, exit 0. git
//!     launches no tool when there is nothing to show, and the shapes whose
//!     entire diff can be computed here are reproduced: plain (index vs
//!     worktree), `--cached [<rev>]` (a tree vs the index), one revision (a
//!     tree vs the worktree), and two revisions (tree vs tree). `--tool`,
//!     `--extcmd`, `-d`, `-g` and `-y` do not change whether the diff is empty
//!     and so do not disable this. A pathspec-narrowed diff, an unresolvable
//!     revision, or three or more revisions cannot be computed exactly and fall
//!     through to the bail rather than answering from the wrong diff.
//!   * `git difftool --no-index <a> <b>`: the two paths are compared directly
//!     (no repository). A path that cannot be `lstat`ed → `error: Could not
//!     access '<path>'`, exit 1; two paths identical in type, mode and bytes →
//!     no output, exit 0. A differing pair, a directory pair, or any count
//!     other than two falls through to the bail.
//!
//! Everything else bails. The missing substrate, concretely:
//!
//!   1. **The tool database.** Choosing and invoking a tool is implemented as
//!      POSIX shell: `git-difftool--helper` sources `git-mergetool--lib`, which
//!      sources one script per tool out of `$(git --exec-path)/mergetools/`
//!      (24 files in the 2.55.0 install this was checked against). Each script
//!      supplies that tool's `diff_cmd`, `merge_cmd` and availability probe.
//!      Nothing in the vendored crates under `src/ported` carries any of it —
//!      there is no tool registry, no `diff_cmd` table, and no equivalent of
//!      `git-mergetool--lib`'s fallback ordering over `diff.tool`,
//!      `merge.tool`, `diff.guitool`, `merge.guitool` and the built-in default.
//!   2. **`--tool-help`.** Its output is generated by enumerating that same
//!      `mergetools/` directory, partitioning it by whether each tool's binary
//!      is present on `PATH`, and appending the user's `difftool.<t>.cmd`
//!      entries. It is therefore a function of the git *installation* and of
//!      user config, not of the repository, and cannot be derived from the
//!      vendored crates at all.
//!   3. **The temporary checkout.** Both the per-file mode and `--dir-diff`
//!      materialise the pre-/post-image into a `mktemp -d` directory and export
//!      it as `$LOCAL`/`$REMOTE`/`$BASE`/`$MERGED`. That directory name is
//!      random, so even `--extcmd=echo` — the one invocation whose child output
//!      is predictable — cannot be byte-matched: stock git prints a path
//!      containing fresh entropy on every run.
//!   4. **Prompting.** Without `-y`, git writes a prompt to stderr and reads a
//!      reply from the terminal before each file. That is interactive by
//!      construction and has no non-interactive equivalent.
//!
//! These paths are deliberately not approximated. A `difftool` invocation that
//! returned 0 without launching a tool would be indistinguishable from a
//! successful one that did, while leaving the user's diff unreviewed — the
//! worst failure mode for a harness that compares exit codes.

use anyhow::{bail, Result};
use std::process::ExitCode;

/// Stock git's `difftool` usage block, byte-for-byte (813 bytes, git 2.55.0),
/// including the trailing blank line. Printed on `-h` (stdout).
const USAGE: &str = concat!(
    "usage: git difftool [<options>] [<commit> [<commit>]] [--] [<path>...]\n",
    "\n",
    "\x20   -g, --[no-]gui        use `diff.guitool` instead of `diff.tool`\n",
    "\x20   -d, --[no-]dir-diff   perform a full-directory diff\n",
    "\x20   -y, --no-prompt       do not prompt before launching a diff tool\n",
    "\x20   --[no-]symlinks       use symlinks in dir-diff mode\n",
    "\x20   -t, --[no-]tool <tool>\n",
    "\x20                         use the specified diff tool\n",
    "\x20   --[no-]tool-help      print a list of diff tools that may be used with `--tool`\n",
    "\x20   --[no-]trust-exit-code\n",
    "\x20                         make 'git-difftool' exit when an invoked diff tool returns a non-zero exit code\n",
    "\x20   -x, --[no-]extcmd <command>\n",
    "\x20                         specify a custom command for viewing diffs\n",
    "\x20   --no-index            passed to `diff`\n",
    "\x20   --index               opposite of --no-index\n",
    "\n",
);

/// The options that take a separate value argument, as `(long, short)`.
const VALUE_OPTS: [(&str, char); 2] = [("tool", 't'), ("extcmd", 'x')];

/// What the parsed command line asks for, as far as this module tracks it.
#[derive(Default)]
struct Opts {
    /// `--tool-help` was given.
    tool_help: bool,
    /// `--tool=`/`-t` value, if any. `Some("")` means an explicitly empty value.
    tool: Option<String>,
    /// `--extcmd=`/`-x` value, if any. `Some("")` means an explicitly empty value.
    extcmd: Option<String>,
    /// `--no-index` was given (`difftool` then diffs two paths outside any repo).
    no_index: bool,
    /// `--cached`/`--staged`: diff the named tree (or HEAD) against the index,
    /// never the worktree.
    cached: bool,
    /// A `--` separator was seen, so `others` after it are pathspecs. The
    /// empty-diff fast path only fires when it can compute the *whole* diff, so
    /// it declines whenever a pathspec could narrow the comparison.
    saw_separator: bool,
    /// Any argument that is not one of the options `difftool` itself defines:
    /// revisions, pathspecs, and the `git diff` options it forwards. Tracked so
    /// the empty-diff fast path can refuse to fire when the diff it would have
    /// to compute is not the plain unstaged one.
    others: Vec<String>,
}

/// `git difftool` — argument validation and the empty-diff case only; launching
/// a diff tool is not ported.
///
/// See the module documentation for the exact set of invocations that are
/// reproduced byte-for-byte, and for the substrate the rest would need.
pub fn difftool(args: &[String]) -> Result<ExitCode> {
    // Dispatch includes the verb at index 0. `difftool`'s own positionals are
    // revisions and paths, so a leading literal `difftool` is unambiguous only
    // as the verb; strip exactly one.
    let args = match args.first().map(String::as_str) {
        Some("difftool") => &args[1..],
        _ => args,
    };

    // Phase 1 — parse_options. `-h`, and every "requires a value" diagnostic,
    // are emitted here, before git looks at the repository at all.
    let mut opts = Opts::default();
    let mut end_of_opts = false;
    let mut i = 0;
    while i < args.len() {
        let a = args[i].as_str();

        if end_of_opts {
            opts.others.push(a.to_owned());
            i += 1;
            continue;
        }

        match a {
            "--" => {
                end_of_opts = true;
                opts.saw_separator = true;
                // A bare trailing `--` is not itself a pathspec; anything after
                // it is, and lands in `others` on the next iterations.
            }
            "-h" => {
                print!("{USAGE}");
                return Ok(ExitCode::from(129));
            }
            "--tool-help" => opts.tool_help = true,
            "--no-tool-help" => opts.tool_help = false,
            "-d" | "--dir-diff" | "--no-dir-diff" => {}
            "-y" | "--no-prompt" | "--prompt" => {}
            "-g" | "--gui" | "--no-gui" => {}
            "--symlinks" | "--no-symlinks" => {}
            "--trust-exit-code" | "--no-trust-exit-code" => {}
            "--no-index" => opts.no_index = true,
            "--index" => opts.no_index = false,
            "--cached" | "--staged" => opts.cached = true,
            "--no-tool" => opts.tool = None,
            "--no-extcmd" => opts.extcmd = None,

            // `--tool <v>` / `--extcmd <v>`: a separate value argument.
            _ if VALUE_OPTS.iter().any(|(l, _)| a.strip_prefix("--") == Some(*l)) => {
                let name = &a[2..];
                let short = short_for(name);
                let Some(v) = args.get(i + 1) else {
                    return Ok(usage_error(&format!("option `{name}' requires a value")));
                };
                store_value(&mut opts, short, v.clone());
                i += 1;
            }
            // `--tool=<v>` / `--extcmd=<v>`, including an empty `<v>`; the
            // emptiness is diagnosed later, after the worktree check.
            _ if VALUE_OPTS
                .iter()
                .any(|(l, _)| a.starts_with(&format!("--{l}="))) =>
            {
                let (name, v) = a[2..].split_once('=').unwrap_or((&a[2..], ""));
                store_value(&mut opts, short_for(name), v.to_owned());
            }

            _ if a.starts_with("--") => {
                // git forwards unrecognised long options to `git diff`, which
                // reports them against *its own* usage block. Reproducing that
                // here would duplicate `diff`'s surface and drift from it, so
                // refuse instead of guessing.
                bail!(
                    "unsupported flag {a:?} — difftool forwards unknown options to `git diff` \
                     (ported: -h, -y/--no-prompt, --prompt, -d/--dir-diff, -g/--gui, --symlinks, \
                     --trust-exit-code, -t/--tool, -x/--extcmd, --tool-help, --index/--no-index)"
                );
            }

            // Clustered short switches, e.g. `-yd` or `-t vimdiff`.
            _ if a.len() > 1 && a.starts_with('-') => {
                let mut chars = a[1..].chars();
                while let Some(c) = chars.next() {
                    match c {
                        'h' => {
                            print!("{USAGE}");
                            return Ok(ExitCode::from(129));
                        }
                        'y' | 'g' | 'd' => {}
                        't' | 'x' => {
                            // The value is the rest of the cluster if non-empty,
                            // otherwise the next argument.
                            let rest: String = chars.by_ref().collect();
                            if rest.is_empty() {
                                let Some(v) = args.get(i + 1) else {
                                    return Ok(usage_error(&format!(
                                        "switch `{c}' requires a value"
                                    )));
                                };
                                store_value(&mut opts, c, v.clone());
                                i += 1;
                            } else {
                                store_value(&mut opts, c, rest);
                            }
                        }
                        _ => bail!(
                            "unsupported flag {:?} — difftool forwards unknown switches to \
                             `git diff` (ported: -h, -y, -d, -g, -t, -x)",
                            format!("-{c}")
                        ),
                    }
                }
            }

            _ => opts.others.push(a.to_owned()),
        }
        i += 1;
    }

    // `--tool-help` is answered right after parsing, before repository setup —
    // it works outside a repository and in a bare one. Its content is not
    // derivable here; see the module docs.
    if opts.tool_help {
        bail!(
            "--tool-help is not ported: its listing is produced by enumerating \
             $(git --exec-path)/mergetools/ and probing each tool's binary on PATH, and no such \
             tool database exists in the vendored crates"
        );
    }

    // `--no-index` compares two filesystem paths directly and needs no
    // repository, so it is answered before repository setup — matching git,
    // which accepts `git difftool --no-index a b` both inside and outside a repo.
    if opts.no_index {
        return no_index(&opts.others);
    }

    // Phase 2 — repository setup. Both diagnostics are git's own, exit 128.
    let repo = match gix::discover(".") {
        Ok(repo) => repo,
        Err(_) => {
            eprintln!("fatal: difftool requires worktree or --no-index");
            return Ok(ExitCode::from(128));
        }
    };
    if repo.workdir().is_none() {
        eprintln!("fatal: this operation must be run in a work tree");
        return Ok(ExitCode::from(128));
    }

    // Phase 3 — the empty-value checks, which the C performs after setup.
    if opts.tool.as_deref() == Some("") {
        eprintln!("fatal: no <tool> given for --tool=<tool>");
        return Ok(ExitCode::from(128));
    }
    if opts.extcmd.as_deref() == Some("") {
        eprintln!("fatal: no <cmd> given for --extcmd=<cmd>");
        return Ok(ExitCode::from(128));
    }

    // Phase 4 — when the diff `difftool` would show is empty, git launches no
    // tool, prints nothing and exits 0. `--tool`/`--extcmd`/`-d`/`-g`/`-y` do
    // not change *whether* the diff is empty, so they do not gate this. The one
    // thing that determines the answer is the revision/pathspec shape; the
    // shapes below are the ones whose whole diff can be computed exactly here.
    //
    // `is_empty == Some(true)` is only returned when the *entire* diff has been
    // proven empty, so a false positive (a spurious exit 0 that skips a real
    // review) is impossible. Shapes that cannot be computed exactly — a
    // pathspec-narrowed diff, an unresolvable revision, three or more
    // revisions — yield `None` and fall through to the honest bail rather than
    // guessing from the wrong diff.
    let is_empty: Option<bool> = if opts.saw_separator {
        // A `--` means the trailing `others` are pathspecs that would narrow the
        // comparison; the narrowed diff is not computed here.
        None
    } else if opts.cached {
        // `--cached [<rev>]`: the <rev> tree (default HEAD) against the index.
        match opts.others.as_slice() {
            [] => Some(index_matches_tree(&repo, repo.head_tree_id_or_empty()?.detach())?),
            [rev] => match resolve_tree(&repo, rev) {
                Some(t) => Some(index_matches_tree(&repo, t)?),
                None => None,
            },
            _ => None,
        }
    } else {
        match opts.others.as_slice() {
            // Plain `git difftool`: the index against the worktree.
            [] => Some(!has_unstaged(&repo)?),
            // One revision: <rev> against the worktree. Empty iff the worktree
            // equals <rev>'s tree, which holds exactly when <rev> equals the
            // index *and* the index equals the worktree. (A token that does not
            // resolve as a revision may be a pathspec, so decline it.)
            [rev] => match resolve_tree(&repo, rev) {
                Some(t) => Some(index_matches_tree(&repo, t)? && !has_unstaged(&repo)?),
                None => None,
            },
            // Two revisions: their two trees. Because trees are content
            // addressed, the diff is empty exactly when the tree ids are equal.
            [a, b] => match (resolve_tree(&repo, a), resolve_tree(&repo, b)) {
                (Some(ta), Some(tb)) => Some(ta == tb),
                _ => None,
            },
            _ => None,
        }
    };
    if is_empty == Some(true) {
        return Ok(ExitCode::SUCCESS);
    }

    bail!(
        "difftool would launch a diff tool here: with a non-empty diff it stages the pre-/post-images \
         into a mktemp directory whose randomised path appears in the tool's own output, selects the \
         tool through POSIX shell (git-difftool--helper sourcing git-mergetool--lib and one script per \
         tool from $(git --exec-path)/mergetools/), and without -y prompts on the terminal — none of \
         which the vendored crates provide \
         (ported: -h, usage errors, the worktree/bare diagnostics, --tool=/--extcmd= empty-value \
         diagnostics, --no-index for two paths, and the empty-diff exit-0 case for the plain, \
         --cached, one-revision and two-revision shapes)"
    )
}

/// `--no-index`: compare two filesystem paths directly, the way
/// `git diff --no-index` does, with no repository involved.
///
/// The determinable results are reproduced exactly:
///   * a path that cannot be `lstat`ed → `error: Could not access '<path>'` on
///     stderr, exit 1 (git checks the two paths in argv order);
///   * two paths with identical content, mode and type → exit 0, no output, the
///     same as any empty diff.
///
/// A pair that differs would materialise both sides and launch a tool (the
/// randomised-tempdir / interactive case), and any path count other than two
/// prints `git diff --no-index`'s own parse-options usage block — `git diff`'s
/// option surface, not `difftool`'s. Both fall through to the bail.
fn no_index(paths: &[String]) -> Result<ExitCode> {
    if let [a, b] = paths {
        // Accessibility, in argv order, using `lstat` so a broken symlink counts
        // as present (matching git, which does not follow the link here).
        for p in [a, b] {
            if std::fs::symlink_metadata(p).is_err() {
                eprintln!("error: Could not access '{p}'");
                return Ok(ExitCode::from(1));
            }
        }
        if paths_identical(a, b)? {
            return Ok(ExitCode::SUCCESS);
        }
        bail!(
            "--no-index: {a:?} and {b:?} differ (or are directories), so difftool would stage both \
             sides into a mktemp directory and launch a tool — a randomised path in the tool's own \
             output, with an interactive prompt without -y"
        );
    }
    bail!(
        "--no-index with {} path argument(s) prints `git diff --no-index`'s parse-options usage \
         block on stderr (exit 129); that block is `git diff`'s option surface, produced by its \
         parser rather than difftool's",
        paths.len()
    )
}

/// Whether two filesystem paths are diff-identical to `git diff --no-index`:
/// same type, same mode and same bytes. Directories and any type/mode mismatch
/// return `false` so the caller declines rather than claiming a spurious exit 0.
fn paths_identical(a: &str, b: &str) -> Result<bool> {
    use std::os::unix::fs::PermissionsExt;
    let (ma, mb) = (std::fs::symlink_metadata(a)?, std::fs::symlink_metadata(b)?);
    if ma.file_type().is_symlink() && mb.file_type().is_symlink() {
        return Ok(std::fs::read_link(a)? == std::fs::read_link(b)?);
    }
    if ma.is_file() && mb.is_file() {
        let exec_a = ma.permissions().mode() & 0o111 != 0;
        let exec_b = mb.permissions().mode() & 0o111 != 0;
        return Ok(exec_a == exec_b && std::fs::read(a)? == std::fs::read(b)?);
    }
    Ok(false)
}

/// The tree id a revision resolves to, or `None` if the argument is not a
/// revision (it may be a pathspec, which the caller then declines to guess at).
fn resolve_tree(repo: &gix::Repository, spec: &str) -> Option<gix::ObjectId> {
    repo.rev_parse_single(spec)
        .ok()?
        .object()
        .ok()?
        .peel_to_tree()
        .ok()
        .map(|t| t.id)
}

/// Whether the index is byte-for-byte the given tree — i.e. whether
/// `git diff --cached <tree>` would be empty. Compares every stage-0 entry by
/// path, mode and blob id in both directions; a conflicted or intent-to-add
/// entry, or any path present on only one side, counts as a difference.
fn index_matches_tree(repo: &gix::Repository, tree: gix::ObjectId) -> Result<bool> {
    use gix::bstr::BString;
    use gix::ObjectId;
    use std::collections::BTreeMap;

    let base = repo.index_from_tree(&tree)?;
    let backing = base.path_backing();
    let mut want: BTreeMap<BString, (u32, ObjectId)> = base
        .entries()
        .iter()
        .map(|e| (e.path_in(backing).to_owned(), (e.mode.bits(), e.id)))
        .collect();

    let index = repo.index_or_empty()?;
    let state: &gix::index::State = &index;
    for e in state.entries() {
        if e.stage_raw() != 0 {
            return Ok(false);
        }
        let path = e.path(state).to_owned();
        match want.remove(&path) {
            Some((mode, id)) if mode == e.mode.bits() && id == e.id => {}
            _ => return Ok(false),
        }
    }
    Ok(want.is_empty())
}

/// The short letter a value-taking long option is spelled with (`tool` → `t`),
/// or `'\0'` for a name that is not one of them.
fn short_for(long: &str) -> char {
    VALUE_OPTS
        .iter()
        .find(|(l, _)| *l == long)
        .map(|(_, s)| *s)
        .unwrap_or('\0')
}

/// Record a `--tool`/`--extcmd` value, keyed by the option's short letter.
fn store_value(opts: &mut Opts, short: char, value: String) {
    match short {
        't' => opts.tool = Some(value),
        'x' => opts.extcmd = Some(value),
        _ => {}
    }
}

/// git's parse-options failure shape for `difftool`: `error: <msg>` on stderr,
/// exit 129. Unlike `-h`, no usage block follows.
fn usage_error(msg: &str) -> ExitCode {
    eprintln!("error: {msg}");
    ExitCode::from(129)
}

/// Whether the worktree differs from the index — i.e. whether plain `git diff`
/// would produce anything, and so whether `difftool` would launch a tool.
///
/// Untracked files are ignored (`git diff` does not report them), as are
/// `NeedsUpdate` entries, which signal only that a stat cache line is racily
/// stale and not that the content changed. Anything else counts as a change, so
/// the answer errs towards "there is a diff" and this module bails rather than
/// claiming a clean tree it has not proven.
fn has_unstaged(repo: &gix::Repository) -> Result<bool> {
    use gix::bstr::BString;
    use gix::status::UntrackedFiles;
    use gix::status::index_worktree::Item;
    use gix::status::plumbing::index_as_worktree::EntryStatus;

    let patterns: Vec<BString> = Vec::new();
    let iter = repo
        .status(gix::progress::Discard)?
        // `git diff` never reports untracked paths, so skip the directory walk.
        .untracked_files(UntrackedFiles::None)
        .into_index_worktree_iter(patterns)?;

    for item in iter {
        match item? {
            // Racily-clean: the stat data was stale but the content matched, so
            // there is nothing for `git diff` to report.
            Item::Modification {
                status: EntryStatus::NeedsUpdate(_),
                ..
            } => {}
            // Everything else — content, mode and type changes, deletions,
            // intent-to-add entries and conflicts — is a diff git would show.
            _ => return Ok(true),
        }
    }
    Ok(false)
}
