//! git-compatible porcelain, served natively via the vendored gitoxide
//! crates. One module per subcommand, ported incrementally. Each is the
//! drop-in equivalent of the stock `git` subcommand of the same name, so
//! tools on PATH (RustRover, gh, cargo) see identical behavior against the
//! same on-disk `.git`.

mod add;
mod am;
mod annotate;
mod apply;
mod archive;
mod backfill;
mod bisect;
mod blame;
mod branch;
mod bundle;
mod cat_file;
mod check_attr;
mod check_ignore;
mod check_mailmap;
mod check_ref_format;
mod checkout;
mod cherry;
mod cherry_pick;
mod clean;
mod clone;
mod commit;
mod commit_graph;
mod commit_tree;
mod config;
mod count_objects;
mod credential;
mod credential_cache;
mod credential_cache__daemon;
mod credential_netrc;
mod credential_osxkeychain;
mod credential_store;
mod daemon;
mod describe;
mod diff;
mod diff_files;
mod diff_index;
mod diff_tree;
mod difftool;
mod fast_export;
mod fast_import;
mod fetch;
mod fetch_pack;
mod fmt_merge_msg;
mod for_each_ref;
mod format_patch;
mod fsck;
mod fsmonitor__daemon;
mod gc;
mod grep;
mod hash_object;
mod http_backend;
mod http_fetch;
mod http_push;
mod index_pack;
mod init;
mod interpret_trailers;
mod log;
mod ls_files;
mod ls_remote;
mod ls_tree;
mod maintenance;
mod merge;
mod merge_base;
mod merge_file;
mod merge_index;
mod merge_tree;
mod mergetool;
mod mktag;
mod mktree;
mod multi_pack_index;
mod mv;
mod name_rev;
mod notes;
mod pack_objects;
mod pack_refs;
mod patch_id;
mod prune;
mod prune_packed;
mod pull;
mod push;
mod range_diff;
mod read_tree;
mod rebase;
mod receive_pack;
mod reflog;
mod refs;
mod remote;
mod remote_ext;
mod remote_fd;
mod remote_ftp;
mod remote_ftps;
mod remote_http;
mod remote_https;
mod repack;
mod replace;
mod repo;
mod request_pull;
mod rerere;
mod reset;
mod restore;
mod rev_list;
mod rev_parse;
mod revert;
mod rm;
mod send_pack;
mod shortlog;
mod show;
mod show_branch;
mod show_index;
mod show_ref;
mod sparse_checkout;
mod stage;
mod stash;
mod status;
mod stripspace;
mod submodule;
mod switch;
mod symbolic_ref;
mod tag;
mod unpack_file;
mod unpack_objects;
mod update_index;
mod update_ref;
mod update_server_info;
mod upload_archive;
mod upload_pack;
mod var;
mod verify_commit;
mod verify_pack;
mod verify_tag;
mod whatchanged;
mod worktree;
mod write_tree;

pub use add::add;
pub use am::am;
pub use annotate::annotate;
pub use apply::apply;
pub use archive::archive;
pub use backfill::backfill;
pub use bisect::bisect;
pub use blame::blame;
pub use branch::branch;
pub use bundle::bundle;
pub use cat_file::cat_file;
pub use check_attr::check_attr;
pub use check_ignore::check_ignore;
pub use check_mailmap::check_mailmap;
pub use check_ref_format::check_ref_format;
pub use checkout::checkout;
pub use cherry::cherry;
pub use cherry_pick::cherry_pick;
pub use clean::clean;
pub use clone::clone;
pub use commit::commit;
pub use commit_graph::commit_graph;
pub use commit_tree::commit_tree;
pub use config::config;
pub use count_objects::count_objects;
pub use credential::credential;
pub use credential_cache::credential_cache;
pub use credential_cache__daemon::credential_cache__daemon;
pub use credential_netrc::credential_netrc;
pub use credential_osxkeychain::credential_osxkeychain;
pub use credential_store::credential_store;
pub use daemon::daemon;
pub use describe::describe;
pub use diff::diff;
pub use diff_files::diff_files;
pub use diff_index::diff_index;
pub use diff_tree::diff_tree;
pub use difftool::difftool;
pub use fast_export::fast_export;
pub use fast_import::fast_import;
pub use fetch::fetch;
pub use fetch_pack::fetch_pack;
pub use fmt_merge_msg::fmt_merge_msg;
pub use for_each_ref::for_each_ref;
pub use format_patch::format_patch;
pub use fsck::fsck;
pub use fsmonitor__daemon::fsmonitor__daemon;
pub use gc::gc;
pub use grep::grep;
pub use hash_object::hash_object;
pub use http_backend::http_backend;
pub use http_fetch::http_fetch;
pub use http_push::http_push;
pub use index_pack::index_pack;
pub use init::init;
pub use interpret_trailers::interpret_trailers;
pub use log::log;
pub use ls_files::ls_files;
pub use ls_remote::ls_remote;
pub use ls_tree::ls_tree;
pub use maintenance::maintenance;
pub use merge::merge;
pub use merge_base::merge_base;
pub use merge_file::merge_file;
pub use merge_index::merge_index;
pub use merge_tree::merge_tree;
pub use mergetool::mergetool;
pub use mktag::mktag;
pub use mktree::mktree;
pub use multi_pack_index::multi_pack_index;
pub use mv::mv;
pub use name_rev::name_rev;
pub use notes::notes;
pub use pack_objects::pack_objects;
pub use pack_refs::pack_refs;
pub use patch_id::patch_id;
pub use prune::prune;
pub use prune_packed::prune_packed;
pub use pull::pull;
pub use push::push;
pub use range_diff::range_diff;
pub use read_tree::read_tree;
pub use rebase::rebase;
pub use receive_pack::receive_pack;
pub use reflog::reflog;
pub use refs::refs;
pub use remote::remote;
pub use remote_ext::remote_ext;
pub use remote_fd::remote_fd;
pub use remote_ftp::remote_ftp;
pub use remote_ftps::remote_ftps;
pub use remote_http::remote_http;
pub use remote_https::remote_https;
pub use repack::repack;
pub use replace::replace;
pub use repo::repo;
pub use request_pull::request_pull;
pub use rerere::rerere;
pub use reset::reset;
pub use restore::restore;
pub use rev_list::rev_list;
pub use rev_parse::rev_parse;
pub use revert::revert;
pub use rm::rm;
pub use send_pack::send_pack;
pub use shortlog::shortlog;
pub use show::show;
pub use show_branch::show_branch;
pub use show_index::show_index;
pub use show_ref::show_ref;
pub use sparse_checkout::sparse_checkout;
pub use stage::stage;
pub use stash::stash;
pub use status::status;
pub use stripspace::stripspace;
pub use submodule::submodule;
pub use switch::switch;
pub use symbolic_ref::symbolic_ref;
pub use tag::tag;
pub use unpack_file::unpack_file;
pub use unpack_objects::unpack_objects;
pub use update_index::update_index;
pub use update_ref::update_ref;
pub use update_server_info::update_server_info;
pub use upload_archive::upload_archive;
pub use upload_pack::upload_pack;
pub use var::var;
pub use verify_commit::verify_commit;
pub use verify_pack::verify_pack;
pub use verify_tag::verify_tag;
pub use whatchanged::whatchanged;
pub use worktree::worktree;
pub use write_tree::write_tree;
