//! `git rebase -i`'s instruction sheet — the todo list.
//!
//! This is the port of the todo-list half of git's sequencer: the pieces of
//! `sequencer.c` and `rebase-interactive.c` that turn a revision range into a
//! `git-rebase-todo` file, hand it to the sequence editor, read the user's
//! edit back, and hand a parsed instruction stream to the executor in
//! [`super::rebase`].
//!
//! What is ported here, function by function:
//!
//! * `todo_command_info[]` — the command table, both spellings of every
//!   instruction ([`Cmd::name`] / [`Cmd::nick`]) and the classification
//!   predicates built on it (`is_noop()`, `is_fixup()`, `is_pick_or_similar()`).
//! * `parse_insn_line()` / `todo_list_parse_insn_buffer()` — [`List::parse`],
//!   including the `-C`/`-c` flags on `fixup` and `merge`, the
//!   argument-presence rules per command, `check_label_or_ref_arg()`, the
//!   `cannot '<cmd>' without a previous commit` rule that guards a leading
//!   `fixup`/`squash`, and `check_merge_commit_insn()`'s four refusals.
//! * `todo_list_to_strbuf()` — [`List::to_bytes`], with `TODO_LIST_SHORTEN_IDS`
//!   and `TODO_LIST_ABBREVIATE_CMDS`.
//! * `sequencer_make_script()` — [`make_script`], including
//!   `rebase.instructionFormat` and the ` # empty` marker.
//! * `todo_list_rearrange_squash()` — [`rearrange_squash`], the `--autosquash`
//!   engine: `fixup!`/`amend!`/`squash!` subjects matched by title, by commit
//!   name, and by subject prefix, then reordered under the commit they name.
//! * `todo_list_add_exec_commands()` — [`add_exec_commands`], `--exec`.
//! * `append_todo_help()` and `todo_list_check()` from `rebase-interactive.c`,
//!   the latter being what `rebase.missingCommitsCheck` selects between.
//!
//! The one representational difference from C: git keeps every item as a pair
//! of offsets into one flat `strbuf` so that `save_todo()` can write the user's
//! original bytes back out verbatim. Here each item owns its argument
//! ([`Item::arg`]) and the file is regenerated from the parsed items. That is
//! not a behavioral deviation, because `complete_action()` already rewrites the
//! todo file from `todo_list_to_strbuf()` output before the first instruction
//! runs, so the bytes on disk are generated bytes from that point on either way.

use anyhow::{anyhow, Result};
use gix::bstr::{BStr, BString, ByteSlice};
use gix::hash::ObjectId;
use gix::prelude::ObjectIdExt;

/// `enum todo_command`. The order is git's, because several checks in
/// `sequencer.c` are written as range comparisons over it (`command <=
/// TODO_SQUASH` selects the pick-like commands, `TODO_NOOP <= command` selects
/// the ones that do nothing). Those are spelled as predicates below rather than
/// as comparisons, but the order is kept so the two stay easy to compare.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Cmd {
    Pick,
    Revert,
    Edit,
    Reword,
    Fixup,
    Squash,
    Exec,
    Break,
    Label,
    Reset,
    Merge,
    UpdateRef,
    Noop,
    Drop,
    Comment,
    /// git's `TODO_COMMENT + 1`: a line that failed to parse. It is kept in the
    /// list so `--edit-todo` can show it back to the user unchanged.
    Invalid,
}

/// The table order of `todo_command_info[]`, which is also the order
/// `parse_insn_line()` probes commands in — `pick` before `revert`, and so on.
/// Probing in table order is load-bearing for the one-letter spellings.
const TABLE: [Cmd; 14] = [
    Cmd::Pick,
    Cmd::Revert,
    Cmd::Edit,
    Cmd::Reword,
    Cmd::Fixup,
    Cmd::Squash,
    Cmd::Exec,
    Cmd::Break,
    Cmd::Label,
    Cmd::Reset,
    Cmd::Merge,
    Cmd::UpdateRef,
    Cmd::Noop,
    Cmd::Drop,
];

impl Cmd {
    /// `todo_command_info[].str`.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Cmd::Pick => "pick",
            Cmd::Revert => "revert",
            Cmd::Edit => "edit",
            Cmd::Reword => "reword",
            Cmd::Fixup => "fixup",
            Cmd::Squash => "squash",
            Cmd::Exec => "exec",
            Cmd::Break => "break",
            Cmd::Label => "label",
            Cmd::Reset => "reset",
            Cmd::Merge => "merge",
            Cmd::UpdateRef => "update-ref",
            Cmd::Noop => "noop",
            Cmd::Drop => "drop",
            Cmd::Comment | Cmd::Invalid => "#",
        }
    }

    /// `todo_command_info[].c` — the one-letter spelling, or `None` for the
    /// commands that have none (`revert` and `noop`).
    fn nick(self) -> Option<u8> {
        match self {
            Cmd::Pick => Some(b'p'),
            Cmd::Edit => Some(b'e'),
            Cmd::Reword => Some(b'r'),
            Cmd::Fixup => Some(b'f'),
            Cmd::Squash => Some(b's'),
            Cmd::Exec => Some(b'x'),
            Cmd::Break => Some(b'b'),
            Cmd::Label => Some(b'l'),
            Cmd::Reset => Some(b't'),
            Cmd::Merge => Some(b'm'),
            Cmd::UpdateRef => Some(b'u'),
            Cmd::Drop => Some(b'd'),
            _ => None,
        }
    }

    /// `is_noop()`: `noop`, `drop` and comments do nothing but are (except for
    /// comments) still counted for progress reporting.
    pub(crate) fn is_noop(self) -> bool {
        matches!(self, Cmd::Noop | Cmd::Drop | Cmd::Comment | Cmd::Invalid)
    }

    /// `is_fixup()`.
    pub(crate) fn is_fixup(self) -> bool {
        matches!(self, Cmd::Fixup | Cmd::Squash)
    }

    /// `is_pick_or_similar()`: does this command create a (non-merge) commit?
    pub(crate) fn is_pick_or_similar(self) -> bool {
        matches!(
            self,
            Cmd::Pick | Cmd::Revert | Cmd::Edit | Cmd::Reword | Cmd::Fixup | Cmd::Squash
        )
    }

}

/// `enum todo_item_flags`.
pub(crate) const EDIT_MERGE_MSG: u32 = 1 << 0;
pub(crate) const REPLACE_FIXUP_MSG: u32 = 1 << 1;
pub(crate) const EDIT_FIXUP_MSG: u32 = 1 << 2;

/// `TODO_LIST_*` rendering flags accepted by [`List::to_bytes`].
pub(crate) const SHORTEN_IDS: u32 = 1 << 0;
pub(crate) const ABBREVIATE_CMDS: u32 = 1 << 1;

/// `struct todo_item`.
#[derive(Clone, Debug)]
pub(crate) struct Item {
    pub(crate) cmd: Cmd,
    /// The commit the instruction names, for the commands that take one.
    pub(crate) commit: Option<ObjectId>,
    /// `item->flags` — the `-C`/`-c` bits.
    pub(crate) flags: u32,
    /// `todo_item_get_arg()`: everything after the command and the object name.
    /// For a comment or an unparsable line this is the whole line.
    pub(crate) arg: BString,
}

impl Item {
    pub(crate) fn new(cmd: Cmd) -> Self {
        Item { cmd, commit: None, flags: 0, arg: BString::default() }
    }
}

/// `struct todo_list`, minus the flat buffer (see the module docs).
#[derive(Clone, Debug, Default)]
pub(crate) struct List {
    pub(crate) items: Vec<Item>,
}

impl List {
    /// `count_commands()`: everything that is not a comment.
    pub(crate) fn count_commands(&self) -> usize {
        self.items.iter().filter(|i| i.cmd != Cmd::Comment).count()
    }

    /// `todo_list_parse_insn_buffer()`.
    ///
    /// Returns the parsed list plus git's return value as a `bool`: `true` when
    /// every line parsed, `false` when at least one `error:` was printed. git
    /// keeps parsing after the first bad line — `--edit-todo` shows the user the
    /// whole file back with every complaint attached — so this does too.
    ///
    /// `fixup_okay` is `file_exists(rebase_path_done())`: once anything has been
    /// done, a leading `fixup`/`squash` has a commit to meld into and is legal.
    pub(crate) fn parse(repo: &gix::Repository, buf: &[u8], mut fixup_okay: bool) -> (List, bool) {
        let comment = comment_prefix(repo);
        let mut list = List::default();
        let mut ok = true;
        for (n, raw) in buf.split(|&b| b == b'\n').enumerate() {
            // `for (i = 1; *p; ...)` stops at the terminating NUL, so a trailing
            // newline does not yield an extra empty line.
            if raw.is_empty() && n > 0 && buf.ends_with(b"\n") {
                continue;
            }
            if raw.is_empty() && buf.is_empty() {
                continue;
            }
            // `if (p != eol && eol[-1] == '\r') eol--;`
            let line = match raw.strip_suffix(b"\r") {
                Some(s) => s,
                None => raw,
            };
            let item = match parse_insn_line(repo, comment.as_bytes(), line) {
                Ok(item) => item,
                Err(msg) => {
                    eprintln!("error: {msg}");
                    eprintln!(
                        "error: invalid line {}: {}",
                        n + 1,
                        line.as_bstr().to_str_lossy()
                    );
                    ok = false;
                    Item {
                        cmd: Cmd::Invalid,
                        commit: None,
                        flags: 0,
                        arg: line.as_bstr().to_owned(),
                    }
                }
            };
            if fixup_okay {
                // do nothing
            } else if item.cmd.is_fixup() {
                eprintln!("error: cannot '{}' without a previous commit", item.cmd.name());
                ok = false;
            } else if !item.cmd.is_noop() {
                fixup_okay = true;
            }
            list.items.push(item);
        }
        (list, ok)
    }

    /// `todo_list_to_strbuf()`. `num` caps how many items are rendered
    /// (git's `num > 0 && num < max`), which is how `skip_unnecessary_picks()`
    /// writes the `done` file.
    pub(crate) fn to_bytes(&self, repo: &gix::Repository, num: Option<usize>, flags: u32) -> Vec<u8> {
        let mut out = Vec::new();
        let max = match num {
            Some(n) if n > 0 && n < self.items.len() => n,
            _ => self.items.len(),
        };
        for item in &self.items[..max] {
            // A comment or an unparsable line is written back verbatim.
            if matches!(item.cmd, Cmd::Comment | Cmd::Invalid) {
                out.extend_from_slice(&item.arg);
                out.push(b'\n');
                continue;
            }
            match (flags & ABBREVIATE_CMDS != 0, item.cmd.nick()) {
                (true, Some(c)) => out.push(c),
                _ => out.extend_from_slice(item.cmd.name().as_bytes()),
            }
            if let Some(oid) = item.commit {
                if item.cmd == Cmd::Fixup {
                    if item.flags & EDIT_FIXUP_MSG != 0 {
                        out.extend_from_slice(b" -c");
                    } else if item.flags & REPLACE_FIXUP_MSG != 0 {
                        out.extend_from_slice(b" -C");
                    }
                }
                if item.cmd == Cmd::Merge {
                    out.extend_from_slice(if item.flags & EDIT_MERGE_MSG != 0 {
                        b" -c"
                    } else {
                        b" -C"
                    });
                }
                out.push(b' ');
                if flags & SHORTEN_IDS != 0 {
                    out.extend_from_slice(short_name(repo, oid).as_bytes());
                } else {
                    out.extend_from_slice(oid.to_string().as_bytes());
                }
            }
            if item.arg.is_empty() {
                out.push(b'\n');
            } else {
                out.push(b' ');
                out.extend_from_slice(&item.arg);
                out.push(b'\n');
            }
        }
        out
    }
}

/// `parse_insn_line()`. The `Err` payload is the text git passes to `error()`
/// before the caller's `invalid line N:` follow-up.
fn parse_insn_line(repo: &gix::Repository, comment: &[u8], line: &[u8]) -> Result<Item, String> {
    // left-trim
    let bol = &line[line.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..];

    if bol.is_empty() || bol.starts_with(comment) {
        let mut item = Item::new(Cmd::Comment);
        item.arg = bol.as_bstr().to_owned();
        return Ok(item);
    }

    let mut cmd = None;
    let mut rest: &[u8] = bol;
    for &candidate in &TABLE {
        if let Some(tail) = is_command(candidate, bol) {
            cmd = Some(candidate);
            rest = tail;
            break;
        }
    }
    let Some(cmd) = cmd else {
        let word: Vec<u8> = bol
            .iter()
            .copied()
            .take_while(|b| !matches!(b, b' ' | b'\t' | b'\r' | b'\n'))
            .collect();
        return Err(format!("invalid command '{}'", word.as_bstr().to_str_lossy()));
    };

    // Eat up extra spaces/tabs before the object name; whether there were any
    // is what distinguishes `pick` (missing argument) from `pickfoo` (already
    // rejected above, since `is_command` requires a separator).
    let padding = rest.iter().take_while(|b| matches!(b, b' ' | b'\t')).count();
    rest = &rest[padding..];

    let mut item = Item::new(cmd);

    if matches!(cmd, Cmd::Noop | Cmd::Break) {
        if !rest.is_empty() {
            return Err(format!(
                "{} does not accept arguments: '{}'",
                cmd.name(),
                rest.as_bstr().to_str_lossy()
            ));
        }
        return Ok(item);
    }

    if padding == 0 {
        return Err(format!("missing arguments for {}", cmd.name()));
    }

    if matches!(cmd, Cmd::Exec | Cmd::Label | Cmd::Reset | Cmd::UpdateRef) {
        item.arg = rest.as_bstr().to_owned();
        if matches!(cmd, Cmd::Label | Cmd::UpdateRef) {
            check_label_or_ref_arg(cmd, rest)?;
        }
        return Ok(item);
    }

    if cmd == Cmd::Fixup {
        if let Some(tail) = rest.strip_prefix(b"-C".as_slice()) {
            rest = &tail[tail.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..];
            item.flags |= REPLACE_FIXUP_MSG;
        } else if let Some(tail) = rest.strip_prefix(b"-c".as_slice()) {
            rest = &tail[tail.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..];
            item.flags |= EDIT_FIXUP_MSG;
        }
    }

    if cmd == Cmd::Merge {
        if let Some(tail) = rest.strip_prefix(b"-C".as_slice()) {
            rest = &tail[tail.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..];
        } else if let Some(tail) = rest.strip_prefix(b"-c".as_slice()) {
            rest = &tail[tail.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..];
            item.flags |= EDIT_MERGE_MSG;
        } else {
            // `merge <label>` with no commit: a brand-new merge whose message
            // the user writes.
            item.flags |= EDIT_MERGE_MSG;
            item.arg = rest.as_bstr().to_owned();
            return Ok(item);
        }
    }

    let name_len = rest
        .iter()
        .take_while(|b| !matches!(b, b' ' | b'\t' | b'\n'))
        .count();
    let (name, tail) = rest.split_at(name_len);
    let oid = resolve(repo, name)
        .ok_or_else(|| format!("could not parse '{}'", name.as_bstr().to_str_lossy()))?;
    item.commit = Some(oid);
    item.arg = tail[tail.iter().take_while(|b| matches!(b, b' ' | b'\t')).count()..]
        .as_bstr()
        .to_owned();

    // `check_merge_commit_insn()`: only `merge` and `drop` accept a merge commit.
    let is_merge_commit = repo
        .find_commit(oid)
        .map(|c| c.parent_ids().count() > 1)
        .unwrap_or(false);
    if is_merge_commit {
        match cmd {
            Cmd::Merge | Cmd::Drop => {}
            Cmd::Fixup | Cmd::Squash => {
                return Err("cannot squash merge commit into another commit".to_string())
            }
            _ => return Err(format!("'{}' does not accept merge commits", cmd.name())),
        }
    }
    Ok(item)
}

/// `is_command()`: the long spelling or the one-letter nick, either way
/// followed by a separator or end of line. Returns the rest of the line.
fn is_command(cmd: Cmd, bol: &[u8]) -> Option<&[u8]> {
    let sep = |p: &[u8]| p.first().is_none_or(|b| matches!(b, b' ' | b'\t' | b'\n' | b'\r'));
    if let Some(tail) = bol.strip_prefix(cmd.name().as_bytes()) {
        if sep(tail) {
            return Some(tail);
        }
    }
    if let Some(nick) = cmd.nick() {
        if bol.first() == Some(&nick) && sep(&bol[1..]) {
            return Some(&bol[1..]);
        }
    }
    None
}

/// `check_label_or_ref_arg()`.
fn check_label_or_ref_arg(cmd: Cmd, arg: &[u8]) -> Result<(), String> {
    let text = arg.as_bstr().to_str_lossy().into_owned();
    match cmd {
        Cmd::Label => {
            // `#` is not a valid label: `merge` uses it to separate the parents
            // from the commit subject.
            if text == "#" || gix::validate::reference::name_partial(arg.as_bstr()).is_err() {
                return Err(format!("'{text}' is not a valid label"));
            }
        }
        Cmd::UpdateRef => {
            if gix::validate::reference::name_partial(arg.as_bstr()).is_err() {
                return Err(format!("'{text}' is not a valid refname"));
            }
            if gix::validate::reference::name(arg.as_bstr()).is_err() {
                return Err(format!(
                    "update-ref requires a fully qualified refname e.g. refs/heads/{text}"
                ));
            }
        }
        _ => {}
    }
    Ok(())
}

fn resolve(repo: &gix::Repository, spec: &[u8]) -> Option<ObjectId> {
    if spec.is_empty() {
        return None;
    }
    repo.rev_parse_single(spec.as_bstr())
        .ok()
        .and_then(|id| id.object().ok())
        .and_then(|o| o.peel_to_kind(gix::object::Kind::Commit).ok())
        .map(|c| c.id)
}

/// `repo_find_unique_abbrev()` at `DEFAULT_ABBREV`.
pub(crate) fn short_name(repo: &gix::Repository, oid: ObjectId) -> String {
    oid.attach(repo).shorten_or_id().to_string()
}

/// The comment prefix git writes the todo help with: `core.commentString`, else
/// `core.commentChar`, else `#`.
///
/// `commit.rs` resolves the same three keys for `COMMIT_EDITMSG`; that copy is
/// private to the module, so this is a second reader of the same keys rather
/// than a second rule.
pub(crate) fn comment_prefix(repo: &gix::Repository) -> String {
    let snap = repo.config_snapshot();
    if let Some(v) = snap.string("core.commentString") {
        let v = v.to_string();
        if !v.is_empty() && v != "auto" {
            return v;
        }
    }
    match snap.string("core.commentChar") {
        None => "#".to_string(),
        Some(v) => {
            let s = v.to_string();
            if s.is_empty() || s == "auto" {
                "#".to_string()
            } else {
                s.chars().next().unwrap_or('#').to_string()
            }
        }
    }
}

/// `sequencer_make_script()` — the initial instruction sheet.
///
/// `commits` is the replay range oldest first, which is what `revs.reverse = 1`
/// produces. `keep_empty` is `--empty=keep`; without it a commit that changes
/// nothing is dropped from the sheet entirely, and with it the line is tagged
/// ` # empty` the way git tags it.
///
/// `revs.cherry_mark` (the patch-id equivalence that drops commits already
/// upstream) is not ported — see the `rebase` module header — so no line is
/// suppressed for being already applied and the
/// `use --reapply-cherry-picks to include skipped commits` advice never fires.
pub(crate) fn make_script(
    repo: &gix::Repository,
    commits: &[ObjectId],
    keep_empty: bool,
    abbreviate: bool,
) -> Result<Vec<u8>> {
    let format = instruction_format(repo);
    let insn = if abbreviate { "p" } else { "pick" };
    let mut out = Vec::new();
    for &oid in commits {
        let commit = repo.find_commit(oid)?;
        let empty = is_original_commit_empty(repo, &commit)?;
        if empty && !keep_empty {
            continue;
        }
        out.extend_from_slice(insn.as_bytes());
        out.push(b' ');
        out.extend_from_slice(oid.to_string().as_bytes());
        out.push(b' ');
        // The configured format already carries the leading comment prefix (see
        // `instruction_format`); everything after it is the oneline.
        let rendered = super::log::format_commit(repo, &commit, &format)?;
        out.extend_from_slice(&rendered);
        if empty {
            out.push(b' ');
            out.extend_from_slice(comment_prefix(repo).as_bytes());
            out.extend_from_slice(b" empty");
        }
        out.push(b'\n');
    }
    Ok(out)
}

/// `rebase.instructionFormat`, defaulted and normalized the way
/// `sequencer_make_script()` normalizes it: an empty or unset value becomes
/// `# %s`, and a value that does not already start with `#` is prefixed with
/// `# ` so the oneline is a comment as far as the instruction sheet's own
/// parser is concerned.
///
/// The `#` here is git's literal `#`, not `comment_line_str`; git formats the
/// default as the string `"# %s"` regardless of `core.commentChar`.
fn instruction_format(repo: &gix::Repository) -> String {
    let configured = repo
        .config_snapshot()
        .string("rebase.instructionFormat")
        .map(|v| v.to_string())
        .unwrap_or_default();
    if configured.is_empty() {
        return "# %s".to_string();
    }
    if configured.starts_with('#') {
        configured
    } else {
        format!("# {configured}")
    }
}

/// `is_original_commit_empty()`: the commit's tree equals its first parent's
/// (or, for a root, the empty tree).
pub(crate) fn is_original_commit_empty(
    repo: &gix::Repository,
    commit: &gix::Commit<'_>,
) -> Result<bool> {
    let tree = commit.tree_id()?.detach();
    match commit.parent_ids().next() {
        Some(p) => Ok(repo.find_commit(p.detach())?.tree_id()?.detach() == tree),
        None => Ok(tree == ObjectId::empty_tree(repo.object_hash())),
    }
}

/// `todo_list_add_exec_commands()` — `--exec <cmd>`.
///
/// Every `<cmd>` is inserted after each `pick`/`merge`, but *after* any
/// fixup/squash chain hanging off it, since such a chain is part of the commit
/// the pick produces.
pub(crate) fn add_exec_commands(list: &mut List, commands: &[String]) {
    if commands.is_empty() {
        return;
    }
    let base: Vec<Item> = commands
        .iter()
        .map(|c| {
            let mut item = Item::new(Cmd::Exec);
            item.arg = BString::from(c.as_str());
            item
        })
        .collect();
    let mut out: Vec<Item> = Vec::with_capacity(list.items.len() + base.len());
    let mut insert = false;
    for item in list.items.drain(..) {
        if insert && !item.cmd.is_fixup() {
            out.extend(base.iter().cloned());
            insert = false;
        }
        let is_pick = matches!(item.cmd, Cmd::Pick | Cmd::Merge);
        out.push(item);
        if is_pick {
            insert = true;
        }
    }
    if insert {
        out.extend(base.iter().cloned());
    }
    list.items = out;
}

/// `todo_list_rearrange_squash()` — `--autosquash` / `rebase.autoSquash`.
///
/// Rewrites a list that holds both `pick <id> <msg>` and
/// `pick <id> fixup!/squash!/amend! <msg>` so the latter sits immediately after
/// the former, as `fixup` (or `fixup -C` for `amend!`, or `squash`).
///
/// Every subject is re-read from the commit rather than taken from the
/// instruction line, because `rebase.instructionFormat` may have put something
/// else there.
///
/// Three ways a `fixup!` finds its target, in git's order: by exact subject, by
/// commit name when the remainder names a commit with no space in it, and by
/// subject prefix (`git commit --fixup` writes the full subject, but a
/// hand-written `fixup! Add wid` should still find `Add widget`).
pub(crate) fn rearrange_squash(repo: &gix::Repository, list: &mut List) -> Result<()> {
    let n = list.items.len();
    let mut next: Vec<isize> = vec![-1; n];
    let mut tail: Vec<isize> = vec![-1; n];
    let mut subjects: Vec<Option<String>> = vec![None; n];
    // `subject2item`: subject → index. Only the first item with a given subject
    // is recorded, matching git's `hashmap_get_from_hash` guard.
    let mut by_subject: std::collections::HashMap<String, usize> = Default::default();
    // `commit_todo`: commit id → index, for the "found by commit name" arm.
    let mut by_commit: std::collections::HashMap<ObjectId, usize> = Default::default();
    let mut rearranged = false;

    for i in 0..n {
        let (commit_id, cmd) = (list.items[i].commit, list.items[i].cmd);
        let Some(commit_id) = commit_id else { continue };
        if cmd == Cmd::Drop {
            continue;
        }
        if cmd.is_fixup() {
            return Err(anyhow!("the script was already rearranged."));
        }
        let commit = repo.find_commit(commit_id)?;
        // `format_subject(&buf, subject, " ")`: the subject with its internal
        // line wrapping folded onto one line.
        let subject = fold_subject(commit.message_raw()?);
        subjects[i] = Some(subject.clone());

        let mut target: Option<usize> = None;
        if let Some(mut p) = skip_fixupish(&subject) {
            // `fixup! fixup! <subject>` chains strip down to the real subject.
            loop {
                let trimmed = p.trim_start();
                match skip_fixupish(trimmed) {
                    Some(next_p) => p = next_p,
                    None => {
                        p = trimmed;
                        break;
                    }
                }
            }
            if let Some(&i2) = by_subject.get(p) {
                target = Some(i2);
            } else if !p.contains(' ') {
                if let Some(oid) = resolve(repo, p.as_bytes()) {
                    if let Some(&i2) = by_commit.get(&oid) {
                        target = Some(i2);
                    }
                }
            }
            if target.is_none() {
                // The remainder can be a prefix of the real subject.
                target = (0..i).find(|&i2| {
                    subjects[i2].as_deref().is_some_and(|s| s.starts_with(p))
                });
            }
        }

        if let Some(i2) = target {
            rearranged = true;
            if subject.starts_with("fixup!") {
                list.items[i].cmd = Cmd::Fixup;
            } else if subject.starts_with("amend!") {
                list.items[i].cmd = Cmd::Fixup;
                list.items[i].flags = REPLACE_FIXUP_MSG;
            } else {
                list.items[i].cmd = Cmd::Squash;
            }
            if tail[i2] < 0 {
                next[i] = next[i2];
                next[i2] = i as isize;
            } else {
                let t = tail[i2] as usize;
                next[i] = next[t];
                next[t] = i as isize;
            }
            tail[i2] = i as isize;
        } else {
            by_subject.entry(subject).or_insert(i);
        }
        by_commit.insert(commit_id, i);
    }

    if !rearranged {
        return Ok(());
    }
    let mut items: Vec<Item> = Vec::with_capacity(n);
    for i in 0..n {
        // Everything started out a `pick`; anything that is a fixup or squash
        // now was moved, and is emitted as part of its target's chain.
        if list.items[i].cmd.is_fixup() {
            continue;
        }
        let mut cur = i as isize;
        while cur >= 0 {
            items.push(list.items[cur as usize].clone());
            cur = next[cur as usize];
        }
    }
    debug_assert_eq!(items.len(), n);
    list.items = items;
    Ok(())
}

/// `skip_fixupish()`: strip a leading `fixup! `, `amend! ` or `squash! `.
fn skip_fixupish(subject: &str) -> Option<&str> {
    subject
        .strip_prefix("fixup! ")
        .or_else(|| subject.strip_prefix("amend! "))
        .or_else(|| subject.strip_prefix("squash! "))
}

/// `find_commit_subject()` + `format_subject(&buf, subject, " ")`: the message's
/// first paragraph with its newlines folded to single spaces.
fn fold_subject(message: &BStr) -> String {
    let text = message.to_str_lossy();
    let mut out = String::new();
    for line in text.lines() {
        if line.trim().is_empty() {
            break;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(line.trim_end());
    }
    out
}

/// `commit_subject_length()` (commit.c): how many bytes of `body` the subject
/// paragraph occupies, its terminating newline included — i.e. the offset of
/// the first blank line.
pub(crate) fn commit_subject_length(body: &[u8]) -> usize {
    let mut p = 0;
    while p < body.len() {
        if skip_blank_lines(&body[p..]).len() != body.len() - p {
            break; // a blank line starts here
        }
        p += match body[p..].iter().position(|&b| b == b'\n') {
            Some(off) => off + 1,
            None => body.len() - p,
        };
    }
    p
}

/// `skip_blank_lines()`: `buf` with any leading whitespace-only lines removed.
pub(crate) fn skip_blank_lines(buf: &[u8]) -> &[u8] {
    let mut rest = buf;
    loop {
        let (line, tail) = match rest.iter().position(|&b| b == b'\n') {
            Some(off) => (&rest[..off], &rest[off + 1..]),
            None => (rest, &rest[rest.len()..]),
        };
        if !line.iter().all(|b| matches!(b, b' ' | b'\t')) {
            return rest;
        }
        if line.len() == rest.len() {
            // An unterminated final line that is all blanks.
            return tail;
        }
        rest = tail;
    }
}

/// `rebase.missingCommitsCheck`.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum MissingCheck {
    Ignore,
    Warn,
    Error,
}

/// `get_missing_commit_check_level()`. An unrecognized value warns and is
/// treated as `ignore`, exactly as git does.
pub(crate) fn missing_commit_check_level(repo: &gix::Repository) -> MissingCheck {
    let Some(value) = repo.config_snapshot().string("rebase.missingCommitsCheck") else {
        return MissingCheck::Ignore;
    };
    let value = value.to_string();
    if value.eq_ignore_ascii_case("ignore") {
        MissingCheck::Ignore
    } else if value.eq_ignore_ascii_case("warn") {
        MissingCheck::Warn
    } else if value.eq_ignore_ascii_case("error") {
        MissingCheck::Error
    } else {
        eprintln!(
            "warning: unrecognized setting {value} for option rebase.missingCommitsCheck. Ignoring."
        );
        MissingCheck::Ignore
    }
}

/// `edit_todo_list_advice`.
pub(crate) const EDIT_TODO_ADVICE: &str = "You can fix this with 'git rebase --edit-todo' \
and then run 'git rebase --continue'.\n\
Or you can abort the rebase with 'git rebase --abort'.\n";

/// `todo_list_check()`: did the user drop commits by deleting lines?
///
/// Returns `true` when the rebase must stop (`rebase.missingCommitsCheck=error`
/// and something went missing). `warn` prints the same report and returns
/// `false`; `ignore` prints nothing.
pub(crate) fn check(repo: &gix::Repository, old: &List, new: &List) -> bool {
    let level = missing_commit_check_level(repo);
    if level == MissingCheck::Ignore {
        return false;
    }
    let mut seen: std::collections::HashSet<ObjectId> =
        new.items.iter().filter_map(|i| i.commit).collect();
    let mut missing = String::new();
    // "Find commits in git-rebase-todo.backup yet unseen", newer to older.
    for item in old.items.iter().rev() {
        let Some(oid) = item.commit else { continue };
        if seen.insert(oid) {
            missing.push_str(&format!(
                " - {} {}\n",
                short_name(repo, oid),
                item.arg.to_str_lossy()
            ));
        }
    }
    if missing.is_empty() {
        return false;
    }
    eprint!(
        "Warning: some commits may have been dropped accidentally.\n\
         Dropped commits (newer to older):\n{missing}"
    );
    eprint!(
        "To avoid this message, use \"drop\" to explicitly remove a commit.\n\n\
         Use 'git config rebase.missingCommitsCheck' to change the level of warnings.\n\
         The possible behaviours are: ignore, warn, error.\n\n"
    );
    eprint!("{EDIT_TODO_ADVICE}");
    level == MissingCheck::Error
}

/// `append_todo_help()` — the commented help block under the instructions.
///
/// `revisions`/`onto` are `None` for `--edit-todo`, which changes both the
/// header (absent) and the closing paragraph, matching git's `edit_todo` flag.
pub(crate) fn append_help(
    repo: &gix::Repository,
    buf: &mut Vec<u8>,
    command_count: usize,
    revisions: Option<&str>,
    onto: Option<&str>,
) {
    let comment = comment_prefix(repo);
    // Written as one literal per line: a `\`-continuation would swallow the
    // leading indentation that the continuation lines carry on purpose.
    let msg = concat!(
        "\nCommands:\n",
        "p, pick <commit> = use commit\n",
        "r, reword <commit> = use commit, but edit the commit message\n",
        "e, edit <commit> = use commit, but stop for amending\n",
        "s, squash <commit> = use commit, but meld into previous commit\n",
        "f, fixup [-C | -c] <commit> = like \"squash\" but keep only the previous\n",
        "                   commit's log message, unless -C is used, in which case\n",
        "                   keep only this commit's message; -c is same as -C but\n",
        "                   opens the editor\n",
        "x, exec <command> = run command (the rest of the line) using shell\n",
        "b, break = stop here (continue rebase later with 'git rebase --continue')\n",
        "d, drop <commit> = remove commit\n",
        "l, label <label> = label current HEAD with a name\n",
        "t, reset <label> = reset HEAD to a label\n",
        "m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]\n",
        "        create a merge commit using the original merge commit's\n",
        "        message (or the oneline, if no original merge commit was\n",
        "        specified); use -c <commit> to reword the commit message\n",
        "u, update-ref <ref> = track a placeholder for the <ref> to be updated\n",
        "                      to this position in the new commits. The <ref> is\n",
        "                      updated at the end of the rebase\n",
        "\n",
        "These lines can be re-ordered; they are executed from top to bottom.\n",
    );

    let edit_todo = revisions.is_none() || onto.is_none();
    if !edit_todo {
        buf.push(b'\n');
        let plural = if command_count == 1 { "command" } else { "commands" };
        buf.extend_from_slice(
            format!(
                "{comment} Rebase {} onto {} ({command_count} {plural})\n",
                revisions.unwrap_or_default(),
                onto.unwrap_or_default()
            )
            .as_bytes(),
        );
    }
    buf.extend_from_slice(&super::stripspace::comment_lines(
        msg.as_bytes(),
        comment.as_bytes(),
    ));

    let msg = if missing_commit_check_level(repo) == MissingCheck::Error {
        "\nDo not remove any line. Use 'drop' explicitly to remove a commit.\n"
    } else {
        "\nIf you remove a line here THAT COMMIT WILL BE LOST.\n"
    };
    buf.extend_from_slice(&super::stripspace::comment_lines(
        msg.as_bytes(),
        comment.as_bytes(),
    ));

    let msg = if edit_todo {
        concat!(
            "\nYou are editing the todo file of an ongoing interactive rebase.\n",
            "To continue rebase after editing, run:\n",
            "    git rebase --continue\n\n",
        )
    } else {
        "\nHowever, if you remove everything, the rebase will be aborted.\n\n"
    };
    buf.extend_from_slice(&super::stripspace::comment_lines(
        msg.as_bytes(),
        comment.as_bytes(),
    ));
}

/// `launch_sequence_editor()`: `GIT_SEQUENCE_EDITOR`, then `sequence.editor`,
/// then the ordinary `git_editor()` chain. Run through the shell so a
/// configured editor may carry arguments.
pub(crate) fn launch_sequence_editor(repo: &gix::Repository, path: &std::path::Path) -> Result<()> {
    let env = |k: &str| std::env::var(k).ok().filter(|v| !v.is_empty());
    let snap = repo.config_snapshot();
    let editor = env("GIT_SEQUENCE_EDITOR")
        .or_else(|| snap.string("sequence.editor").map(|v| v.to_string()))
        .or_else(|| env("GIT_EDITOR"))
        .or_else(|| snap.string("core.editor").map(|v| v.to_string()))
        .or_else(|| env("VISUAL"))
        .or_else(|| env("EDITOR"))
        .unwrap_or_else(|| "vi".to_string());
    // `:` is git's documented no-op editor and must not be shelled out to with
    // the file as an argument, or it would silently succeed anyway; running it
    // through the shell does the right thing either way.
    let status = std::process::Command::new("sh")
        .arg("-c")
        .arg(format!("{editor} \"$@\""))
        .arg(&editor)
        .arg(path)
        .status()
        .map_err(|e| anyhow!("cannot run editor '{editor}': {e}"))?;
    if !status.success() {
        return Err(anyhow!("there was a problem with the editor '{editor}'"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_command_matches_long_and_short_spellings() {
        assert_eq!(is_command(Cmd::Pick, b"pick abc"), Some(&b" abc"[..]));
        assert_eq!(is_command(Cmd::Pick, b"p abc"), Some(&b" abc"[..]));
        // A bare command with no argument still matches; the missing argument is
        // diagnosed later.
        assert_eq!(is_command(Cmd::Break, b"break"), Some(&b""[..]));
        // `pickle` is not `pick`: the separator check rejects it.
        assert_eq!(is_command(Cmd::Pick, b"pickle"), None);
        // `revert` has no nick, so a bare `r` must not resolve to it.
        assert_eq!(is_command(Cmd::Revert, b"r x"), None);
        assert_eq!(is_command(Cmd::Reword, b"r x"), Some(&b" x"[..]));
    }

    #[test]
    fn fold_subject_stops_at_the_first_blank_line() {
        assert_eq!(fold_subject(BStr::new(b"one\ntwo\n\nbody\n")), "one two");
        assert_eq!(fold_subject(BStr::new(b"only\n")), "only");
    }

    #[test]
    fn skip_fixupish_recognizes_all_three_prefixes() {
        assert_eq!(skip_fixupish("fixup! subject"), Some("subject"));
        assert_eq!(skip_fixupish("amend! subject"), Some("subject"));
        assert_eq!(skip_fixupish("squash! subject"), Some("subject"));
        assert_eq!(skip_fixupish("fixup!subject"), None);
        assert_eq!(skip_fixupish("plain subject"), None);
    }
}
