//! Build-time harvester for `git zrepl` Tab completion.
//!
//! Each porcelain verb parses its own args by matching literal option strings
//! (`"--short"`, `"-s"`) and subcommand strings (`Some("add")`, `"status" =>`).
//! That parser IS the authoritative, drift-free source of what the verb accepts,
//! so we generate the completion table FROM it rather than maintaining a parallel
//! hand-written list that rots the moment a flag is added. One file : one verb,
//! matching `dispatch.rs`'s file→verb convention (`__`→`--`, `_`→`-`).
//!
//! Precision: options are matched as a *whole* quoted literal (`"` flag `"`), so a
//! flag embedded in a message like `"unknown option --foo"` never matches — only
//! standalone flag literals do. Subcommands are taken from match-arm position
//! (`Some("w")` / `^"w" =>`), first-arg dispatch. The superset `z*` verbs are
//! NOT harvested here (their parsers span multi-verb modules); repl.rs carries
//! their spec by hand.

use std::{env, fs, path::Path};

fn main() {
    // Package root is src/extensions/; the porcelain modules live under src/.
    let dir = Path::new("src/porcelain");
    println!("cargo:rerun-if-changed=src/porcelain");

    // Options: a *whole* quoted flag literal, so a flag inside a message string
    // (`"unknown option --foo"`) never matches — only standalone `"--foo"` do.
    let opt_re = regex::Regex::new(r#""(--?[A-Za-z][A-Za-z0-9-]*)""#).unwrap();
    // Subcommands are harvested ONLY from inside a `match` block whose scrutinee is
    // subcommand dispatch — either an explicitly subcommand-named variable
    // (`sub`/`cmd`/…) or a first-positional (`X.first()...`). Both the bare
    // `"word" =>` and `Some("word") =>` arm forms are collected there (depth-1).
    // A GLOBAL `Some("word")` scan is deliberately NOT used: `Some("literal")` is
    // also value dispatch (date formats, `--track` modes, grep pattern types), so
    // scanning it everywhere harvests those values as fake subcommands. Scoping to
    // first-arg/subcommand blocks excludes value matches — their scrutinee is the
    // flag value (`match atom`, `match track_mode`), not `sub`/`first()`.
    let match_hdr = regex::Regex::new(r"match[[:space:]]+([^\n{]*?)[[:space:]]*\{").unwrap();
    let scrut_ok = regex::Regex::new(r"^(sub|subcommand|subcmd|cmd|command|verb)\b|first\(").unwrap();

    let mut entries: Vec<(String, Vec<String>, Vec<String>)> = Vec::new();
    for ent in fs::read_dir(dir).expect("read porcelain dir") {
        let path = ent.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_str().unwrap();
        if stem == "mod" {
            continue;
        }
        let verb = stem.replace("__", "\u{1}").replace('_', "-").replace('\u{1}', "--");
        let full = fs::read_to_string(&path).unwrap();
        // The parser is the source of truth — test modules are not. Drop everything
        // from the first `#[cfg(test)]` so `Some("feature")` in a test assertion
        // never lands in the completion set.
        let text = full.split("#[cfg(test)]").next().unwrap_or(&full).to_string();

        let opts = dedup_sorted(opt_re.captures_iter(&text).map(|c| c[1].to_string()));

        let mut raw_subs: Vec<String> = Vec::new();
        for hdr in match_hdr.captures_iter(&text) {
            if !scrut_ok.is_match(hdr.get(1).unwrap().as_str().trim()) {
                continue;
            }
            let open = hdr.get(0).unwrap().end() - 1; // index of the block's `{`
            harvest_block_arms(&text, open, &mut raw_subs);
        }
        // Drop the verb's own name (self-referential guard like `if a == "remote"`).
        raw_subs.retain(|s| *s != verb);
        let subs = dedup_sorted(raw_subs.into_iter());

        if opts.is_empty() && subs.is_empty() {
            continue;
        }
        entries.push((verb, opts, subs));
    }
    entries.sort();

    let mut out = String::from("// @generated by build.rs from src/porcelain/*.rs — do not edit.\n");
    out.push_str("pub static PORCELAIN_SPEC: &[(&str, &[&str], &[&str])] = &[\n");
    for (verb, opts, subs) in &entries {
        out.push_str(&format!("    ({verb:?}, &{opts:?}, &{subs:?}),\n"));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("porcelain_spec.rs");
    fs::write(dest, out).unwrap();
}

fn dedup_sorted(it: impl Iterator<Item = String>) -> Vec<String> {
    let mut v: Vec<String> = it.collect();
    v.sort();
    v.dedup();
    v
}

/// From the `{` at byte `open`, scan the balanced block and collect the heads of
/// its **depth-1** match arms — a `"word"` literal immediately followed by `=>`
/// or `|`. Depth-1 only, so nested inner matches (value dispatch inside an arm
/// body) don't leak in; string contents (with `\"` escapes) are skipped so their
/// braces/quotes never perturb the depth count.
fn harvest_block_arms(text: &str, open: usize, out: &mut Vec<String>) {
    let b = text.as_bytes();
    let mut depth: i32 = 0;
    let mut i = open;
    while i < b.len() {
        match b[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return;
                }
            }
            b'"' => {
                let start = i + 1;
                let mut j = start;
                while j < b.len() {
                    if b[j] == b'\\' {
                        j += 2;
                        continue;
                    }
                    if b[j] == b'"' {
                        break;
                    }
                    j += 1;
                }
                if depth == 1 {
                    let lit = &text[start..j.min(b.len())];
                    let after = text.get(j + 1..).unwrap_or("").trim_start();
                    let before = text.get(..i).unwrap_or("").trim_end();
                    // A subcommand arm head, in either form:
                    //   bare:  `"word" =>` / `"word" |`
                    //   Some:  `Some("word")` (an Option arm, `)` then `=>`/`|`)
                    let bare = after.starts_with("=>") || after.starts_with('|');
                    let some = before.ends_with("Some(") && after.starts_with(')');
                    let word = lit.len() >= 2
                        && lit.as_bytes()[0].is_ascii_lowercase()
                        && lit.bytes().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == b'-');
                    if word && (bare || some) {
                        out.push(lit.to_string());
                    }
                }
                i = j + 1;
                continue;
            }
            _ => {}
        }
        i += 1;
    }
}
