#!/usr/bin/env perl
# Codegen: src/parity/grammars/*.json -> src/parity/src/grammars_generated.rs
#
# The grammars are extracted per-command by reading git's own man pages. They
# say only WHAT to test; stock git remains the oracle that says whether zvcs
# agrees. So a thin grammar narrows coverage but can never turn a failure into
# a pass — which is why generating them is safe to fan out.
#
# Mutating commands are excluded from the fuzz set: random flag combinations on
# a command that writes to the repo produce cases whose *stock* behavior is
# itself ambiguous (editors, prompts), which yields noise instead of findings.
# Every exclusion is printed, because a silently dropped command reads as
# covered when it is not.

use strict;
use warnings;
use JSON::PP;
use File::Basename;

my $root = dirname(__FILE__) . '/..';
my $dir  = "$root/src/parity/grammars";
my $out  = "$root/src/parity/src/grammars_generated.rs";

opendir(my $dh, $dir) or die "cannot read $dir: $!\n";
my @files = sort grep { /\.json$/ } readdir($dh);
closedir($dh);

die "no grammar JSON files in $dir\n" unless @files;

# Only the shapes fixture.rs actually builds. An unknown shape is a typo, not a
# new fixture, so it is rejected loudly rather than silently dropped.
my %SHAPE = (
    'linear'        => 'Shape::Linear',
    'branched'      => 'Shape::Branched',
    'merged'        => 'Shape::Merged',
    'dirty'         => 'Shape::Dirty',
    'conflicted'    => 'Shape::Conflicted',
    'detached'      => 'Shape::Detached',
    'awkward-paths' => 'Shape::AwkwardPaths',
    'submodule'     => 'Shape::Submodule',
);

sub rs_str {
    my $s = shift;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    return "\"$s\"";
}

my (@entries, @skipped_mutating, @skipped_empty, @bad);

for my $f (@files) {
    my $path = "$dir/$f";
    open(my $fh, '<', $path) or die "cannot read $path: $!\n";
    my $raw = do { local $/; <$fh> };
    close($fh);

    my $g = eval { JSON::PP->new->decode($raw) };
    if ($@) { push @bad, "$f: malformed JSON ($@)"; next; }

    my $cmd = $g->{command};
    unless (defined $cmd && length $cmd) { push @bad, "$f: missing \"command\""; next; }

    if ($g->{mutating}) { push @skipped_mutating, $cmd; next; }

    my @flags = @{ $g->{flags}       // [] };
    my @pos   = @{ $g->{positionals} // [] };
    my @sh    = @{ $g->{shapes}      // [] };

    # A grammar with no flags AND no positionals generates nothing but the bare
    # subcommand; that is the honest answer for daemons and network verbs, but
    # it is not fuzzable, so it is recorded and dropped.
    unless (@flags || @pos) { push @skipped_empty, $cmd; next; }

    my @shapes;
    for my $s (@sh) {
        if (my $v = $SHAPE{$s}) { push @shapes, $v }
        else { push @bad, "$f: unknown shape \"$s\""; }
    }
    @shapes = ('Shape::Linear') unless @shapes;

    push @entries, {
        cmd    => $cmd,
        flags  => \@flags,
        pos    => \@pos,
        shapes => \@shapes,
    };
}

die "grammar errors:\n  " . join("\n  ", @bad) . "\n" if @bad;

open(my $ofh, '>', $out) or die "cannot write $out: $!\n";
print $ofh <<'HEADER';
//! Generated by scripts/gen_grammars.pl from src/parity/grammars/*.json.
//!
//! Do not edit by hand: regenerate instead. The grammars are extracted from
//! git's own documentation per command and say only which invocations to try.
//! Stock git remains the oracle for whether zvcs agrees, so widening a grammar
//! can surface failures but can never manufacture a pass.

use crate::fixture::Shape;
use crate::fuzz::Grammar;

/// Fuzz grammars for the ported subcommands, read-only ones only.
pub fn generated() -> Vec<Grammar> {
    vec![
HEADER

for my $e (@entries) {
    printf $ofh "        Grammar {\n";
    printf $ofh "            cmd: %s,\n", rs_str($e->{cmd});
    printf $ofh "            flags: &[%s],\n", join(', ', map { rs_str($_) } @{ $e->{flags} });
    printf $ofh "            positionals: &[%s],\n", join(', ', map { rs_str($_) } @{ $e->{pos} });
    printf $ofh "            shapes: &[%s],\n", join(', ', @{ $e->{shapes} });
    printf $ofh "        },\n";
}

print $ofh "    ]\n}\n";
close($ofh);

printf "generated %d grammars -> %s\n", scalar(@entries), $out;
printf "skipped %d mutating: %s\n", scalar(@skipped_mutating), join(' ', sort @skipped_mutating)
    if @skipped_mutating;
printf "skipped %d with no fuzzable surface: %s\n", scalar(@skipped_empty), join(' ', sort @skipped_empty)
    if @skipped_empty;
